### ISSUE TITLE
To be able to edit head title

### ISSUE THREAD

**Issue by maulberto3** [elimintz/justpy#10]
Hi. Self explanatory. At the top of the rendered web page, it shows JustPy with some nice icon.

It'd be good to be able to edit that.

**Comment by elimintz** [comment]
Hi, 
Thanks for using JustPy.

You can set the text by setting the `title` attribute of the page:
https://justpy.io/#/reference/webpage?id=title

To change the favicon (the icon) set the `favicon` attribute of the page to the url you want.

Let me know if this is not what you were asking.

**Comment by maulberto3** [comment]
something like `wp.title = ...` worked but not for `wp.favicon = 'http...`. Also, regarding the title, there is some pre-rendering as first it shows "JustPy" and it immediately changes to the new attribute. Any ideas why?

**Comment by elimintz** [comment]
Thank you for pointing out these two issues, much appreciated. 

In the current version the favicon can only be a local file. I changed it to accept http references also and this will be available in the version coming out next week.

Also, I fixed the problem with initial showing of "JustPy" for the next version.

The next version, 0.0.6, should be out Monday.
