### ISSUE TITLE
Split the screen using percent?

### ISSUE THREAD

**Issue by johnmudd** [elimintz/justpy#101]
I tried to follow the Tailwind [Flexbox Grids doc](https://tailwindcss.com/components/flexbox-grids/) to split the screen. It works but I'd like more flexibility that the fixed set of fractions. Is it possible to split the screen by percent?

  ```
    wp = jp.WebPage()
    d = jp.Div(classes="flex mb-4", a=wp)
    jp.Div(text="Left", classes="w-1/6 bg-gray-400 h-12", a=d)
    jp.Div(text="Right", classes="w-5/6 bg-gray-500 h-12", a=d)
```

**Comment by elimintz** [comment]
Sure, instead of the width class add the keyword argument `style='width: 32%'` if you want the width to be 32% for example.

You can see here: https://tailwindcss.com/docs/width/
what style the width classes translate to.

In the style you can insert and CSS you want.

**Comment by johnmudd** [comment]
Okay. So Tailwinds is just an alternative / abbreviated way to specify CSS. I can combine the two like this.

`jp.Div(text="left css", style='width: 50%', classes="bg-gray-400 h-24", a=wp)`

I notice that there's no runtime exception if I misspell a keyword argument. Why is that?

**Comment by elimintz** [comment]
Yes, you can combine classes with style. If you are interested in learning how to style web pages there are many good CSS introductions. Classes are an important part of CSS.

For any keyword argument, JustPy sets the corresponding attribute of the instance created and therefore there is no error. When the component is rendered, JustPy knows how to handle special attributes like style, text and classes.
