### ISSUE TITLE
div overflow?

### ISSUE THREAD

**Issue by johnmudd** [elimintz/justpy#102]
I want to make a div scrollable. Is this close? When I run it I see the border has the height of the screen which I want but the contents of the div spills below the bottom border.

`jp.Div(classes='w-7/8 m-2 p-3 border rounded-lg h-screen overflow:overflow-y-scroll'`

**Comment by elimintz** [comment]
Overflow is not a pseudo class. The example should look like this:
```python
jp.Div(classes='w-7/8 m-2 p-3 border rounded-lg h-screen overflow-y-scroll')
```

The tailwind documentation provides numerous examples and good explanations:  https://tailwindcss.com/docs/overflow/
