### ISSUE TITLE
run_method fails on custom component

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#103]
Hi Eli, 

I have a custom component and have it working, mostly. 
Now I want to call methods on the Vue comp from the python side. I use run_method to call the method (called 'fit'). To that end the python comp sets temp=False to generate an id, which is a prerequisite as I understand. 

Now I run into the problem that the javascript side reports an error when I do the run_method:
```
VM1939:1 Uncaught TypeError: Cannot read property 'fit' of undefined
    at eval (eval at <anonymous> ((index):1406), <anonymous>:1:14)
    at WebSocket.<anonymous> ((index):1476)
```
Poking at javascript variables shows that the comp_dict does NOT contain my component, but does contain a QBtn that is also on my test page (but the latter does not have temp=False).
 
Do I have to do something (beyond temp=False) to make the comp compatible with run_method? 

TIA

Marcel

**Comment by elimintz** [comment]
Hi,

Could you post the code or email it to me? I'll take a look.

Just guessing here but maybe you are using fit instead of fit(). It looks like the JS is treating it as a property and not a function.

**Comment by mjmare** [comment]
Will email it to you. Thx

**Comment by mjmare** [comment]
For the benefit of passers by: from private conversation with Eli I've learned that the only addition that one should do to have the custom component be able to respond to run_method calls is "register" the component on the JS side. Which is simply: add it to the global variable comp_dict. Like so:
```
comp_dict[this.$props.jp_props.id] = this
```
I did this in the mounted Vue.js method.
