### ISSUE TITLE
favicon fail on GAE

### ISSUE THREAD

**Issue by martinvfx** [elimintz/justpy#105]
I'm deploying my personal project to a Google App Engine after do some test localy with uvicorn. Everything i'ts fine locally, but when I put the same project on the server, it doesn't work and get two errors. 
One related with websockets, thats I'm resolving using "websockets=False" flag. 
Two: I'ts a real mistery for me. If I put a favicon ( wp.favicon="http:\\...[other\site\url\logo.png]" ) all the app stop. 
Seeing in the browser develop tools I can see _`

> favicon "Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME"

`_ 
If I quit or comment this line, everything works again.  
Somebody know why?

**Comment by elimintz** [comment]
Could you please try with the following favicon setting:
```python
wp.favicon = ''https://elimintz.github.io/favicon.png"
```

and see if it works? Just to rule out GAE related issue.

As for websockets, please see the following:
https://cloud.google.com/blog/products/application-development/introducing-websockets-support-for-app-engine-flexible-environment

Working with websockets=False is also fine if you don't need to push data to websites.

**Comment by martinvfx** [comment]
Thanks,
with your icon ( without double single quotes after address ) the app load and wokrs fine, but the blue icon it's shows only on the first reload of the page; after when I press a button, the icon disappear and noicon or generic icon is showed. 

The chrome console show:
`nanhttps://elimintz.github.io/favicon.png:1 Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME`

And if I try to put an static icon file under "/static/..." the app stop again and chrome console show:
`(index):378 Uncaught TypeError: Cannot read property 'redirect' of undefined
    at Object.success ((index):378)
    at u (jquery.js:2)
    at Object.fireWith [as resolveWith] (jquery.js:2)
    at k (jquery.js:2)
    at XMLHttpRequest.<anonymous> (jquery.js:2)`

**Comment by elimintz** [comment]
Thank you for flagging this. There is a bug in the page update. It does not check for an absolute address favicon like it does during the load and tries using a relative path which creates the error. I fixed it and it will be available in the next version which is coming out soon. 

In the meantime, I would recommend downloading the favicon and putting it in your program directory which is also the default static directory. Then just use:
`wp.favicon = "/favicon.png"`

**Comment by martinvfx** [comment]
Okay, thanks for your work. I really like JustPy 

Seem if I putt favicon in root folder it's working for now.
