### ISSUE TITLE
a documented list of styles and icons

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#106]
I could not find a list of possible style codes and icon names to use in button definition.
Is it documented in the underline frameworks?

**Comment by giodegas** [comment]
then, how to understand what this style describes? :

    'w-48 text-xl m-2 p-1 bg-blue-500 text-white'

**Comment by elimintz** [comment]
These are [tailwind](https://tailwindcss.com/) classes. JustPy comes with tailwind as the default though you can disable it and of course add your own CSS classes.

Please also see https://justpy.io/tutorial/tailwind/

Here are some button styles that I took from the tailwind documentation:

```python
class Styles:
    button_simple = 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'
    button_pill = 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full'
    button_outline = 'bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded'
    button_bordered = 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded'
    button_disabled = 'bg-blue-500 text-white font-bold py-2 px-4 rounded opacity-50 cursor-not-allowed'
    button_3d = 'bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded'
    button_elevated = 'bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow'

    input_classes = "m-2 bg-gray-200 border-2 border-gray-200 rounded w-64 py-2 px-4 text-gray-700 focus:outline-none focus:bg-white focus:border-purple-500"

```

**Comment by giodegas** [comment]
yes, I saw it, but it would be nice to have a cheat sheet of codes.
Probably like this one:
https://nerdcave.com/tailwind-cheat-sheet

but targeted to Python programmers, with codes that work well with JustPy.

**Comment by elimintz** [comment]
As far as I can tell, all the classes are supported by JustPy since it has no bearing on the Python. The classes are passed as is to the front end. If you see something that doesn't work, please let me know.
