### ISSUE TITLE
Highchart - clear series data

### ISSUE THREAD

**Issue by rroyer-xyz** [elimintz/justpy#108]
Hi - I have a use case where the user selects one or more items from a dropdown, clicks a button, and data is plotted in highcharts based on their selections. The user can continue to add and change items to plot... so the chart needs to update based on their selections. 

The place I'm stuck is clearing out the existing series data when updating the chart. Seems like no matter what I try, existing data is still retained. There's some explanation in a highcharts [post here](https://www.highcharts.com/forum/viewtopic.php?t=7048). But couldn't get a "remove" command to work (which was the recommendation in that post).

In the test below, the chart is supposed to update from showing 3 brands to just show 1 brand; however, I haven't found a way to remove the data for the existing 3 brands.

```python
import justpy as jp

my_chart_def = """
{
        chart: {
            type: 'spline'
        },
        title: {
            text: 'Trending'
        },
        xAxis: {
            categories: ['Jan 2020', 'Feb 2020', 'Mar 2020', 'Apr 2020']
        },
        yAxis: {
            title: {
                text: 'Metric'
            }
        },
        series: [{
            name: 'Facebook',
            data: [550, 520, 480, 450]
        }, {
            name: 'Google',
            data: [780, 750, 751, 760]
        }, {
            name: 'Oracle',
            data: [980, 950, 951, 960]
        }        
        ],
        credits: {
            enabled: false
        },
}
"""

def chart_test():
    wp = jp.QuasarPage()
    q_btn_trend = jp.QButton(a=wp, color="primary", icon="trending_up", label="Update Chart")                            
    trend_chart = jp.HighCharts(a=wp, classes='m-2 p-2 border', style='width: 600px')
    trend_chart.options = my_chart_def

    # replace the chart series data with new data
    def update_trend_chart(self, msg):        
        
        # tried several ways to remove the existing series data... but no luck :(
        trend_chart.options.series.pop(0)
        trend_chart.options.series.pop(0)
        trend_chart.options.series.pop(0)
        
        # add some new series data
        brand = {}
        brand['name'] = "Apple"
        brand['data'] = [480, 450, 741, 740]
        trend_chart.options.series.append(brand)

        jp.run_task(wp.update())
        
    q_btn_trend.on('click', update_trend_chart)    
    return wp

jp.justpy(chart_test)
```

**Comment by elimintz** [comment]
Please add the line:
```python
trend_chart.update_create = True
```
as the fifth line in `chart_test` and it will solve the problem. This tells the component to create a new chart on update instead of just updating the old chart which left the old series in.

I will change this in the upcoming version so this is not required by making the update one to one and deleting series that are not specified.

**Comment by rroyer-xyz** [comment]
works great... thanks!
