### ISSUE TITLE
main window close event

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#110]
How can my application know when the user closes the browser window, in any way?

It does not look like a `close` event which can be associated to a web page, from this documentation page:

https://justpy.io/tutorial/page_events/

Could it be used the `visibilitychange` event to try to guess if the window is still open?

**Comment by elimintz** [comment]
Currently the only way is to check if the websocket is still open, but it is not a good way to do so.

I will add a page close event.

**Comment by elimintz** [comment]
The way to do this is by overriding the on_disconnect method of the WebPage. This is not documented well. I will improve the documentation.

Here is a simple example:

```python
import justpy as jp

class MyPage(jp.WebPage):

    async def on_disconnect(self, websocket=None):
        await super().on_disconnect()
        # Do what you want to do on disconnect here
        print('Page disconnected')


def close_test():
    wp = MyPage()
    for i in range(10):
        jp.Div(text=f'Div {i}', a=wp, classes='bg-blue-500 text-white m-2 p-2 w-32')
    return wp

jp.justpy(close_test)

```

**Comment by giodegas** [comment]
I would like to notice the user that is closing a tab.
The on_disconnected method is activated then the browser window is already closed.
Can I prevent the closure, until the user confirms?

**Comment by elimintz** [comment]
There is no way to do it now without adding some JavaScript to the page. I will add the ability to capture the https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event in future versions.
