### ISSUE TITLE
accented italian vowel in column heading not showing in AgGrid

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#117]
If I define a column like:

    {"headerName": "Priorità", "field": "priority"}

the "à" does not show up in column heading of the **AgGrid**.

I also tried with the HTML encoding:

    {"headerName": "Priorit&agrave;", "field": "priority"}

but it does not work.

**Comment by snoodlenay** [comment]
giodegas, I just tried pasting your heading into the example I just posted on this thread, https://github.com/elimintz/justpy/issues/116#issuecomment-666588989, and it rendered without problem. Can you post an example of your code?

**Comment by giodegas** [comment]
correct, Indeed I was giving to grid_options a json string instead of a real dictionary. Thank you,
