### ISSUE TITLE
Startup message may report wrong HOST and PORT

### ISSUE THREAD

**Issue by mborus** [elimintz/justpy#12]
Hi, 

thanks for this awesome project. I'm currently working my way through the tutorial and it's great and easy to follow.

I found one smaller problem: Since port 8000 is in use on my machine, I needed to set a different port.

If you pass a host or port to the justpy function to start a server like this

     jp.justpy(hello_world, port=5100)

an incorrect port is displayed.

    @app.on_event('startup')
    async def justpy_startup():

    # ....

    print(f'JustPy ready to go on http://{HOST}:{PORT}')

At the point of the print command, the host and port values from the startup are not accessable, so either the start function should change the globals or the host and port numbers should note get printed on startup.

**Comment by elimintz** [comment]
Hi,

Great to hear that you like the project and are enjoying the tutorial!

Thanks for catching this. I made the change as you suggested (both to host and port) and it will be fixed in the version coming out next week.
