### ISSUE TITLE
cell value in AgGrid with a external link to a new window

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#120]
I would like to set content of some cells in a AgGrid with a cliccable link to a new window, displaying an external URL.
Could it be possible?

Apparently AgGrid supports it, as reported in this blog:

https://medium.com/ag-grid/enhance-your-angular-grid-reports-with-formatted-values-and-links-34fa57ca2952 

Thank you.

**Comment by elimintz** [comment]
Yes, it is possible. My internet is down because of the storm that hit the US east coast, so I'll provide an example when it is back up.

**Comment by elimintz** [comment]
Here is an example. Click the "Link" in red in the second row:

```python
import justpy as jp


grid_options = {
    'rowHeight': 200,
    'columnDefs': [
      {'headerName': "Make", 'field': "make"},
      {'headerName': "Model", 'field': "model"},
      {'headerName': "Price", 'field': "price"},
    ],
    'rowData': [
      {'make': "Toyota", 'model': "Celica", 'price': 4},
      {'make': "Ford", 'model': "Mondeo", 'price': '<a href="https://python.org"  target="_blank" class="m-2 text-red-500 text-5xl">Link</div>'},
      {'make': "Porsche", 'model': "Boxter", 'price': '<img src="https://www.python.org/static/community_logos/python-powered-h-140x182.png">'}
    ],
}

def grid_test():
    wp = jp.WebPage()
    grid = jp.AgGrid(a=wp, options=grid_options)
    grid.html_columns = [2]
    return wp

jp.justpy(grid_test)
```

Please let me know if this is what you were looking for.

**Comment by giodegas** [comment]
brilliant!
I am falling in love with Justpy!
:+1:
