### ISSUE TITLE
Can the QSelect menu go away when the user makes a selection?

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#121]
I'm noticing that when using QSelect that the user has to click outside of the field to make the menu go away after making a selection. Would it be possible for the menu to automatically go away when the user selects an option?

Thank you!

**Comment by elimintz** [comment]
I can't replicate the problem.

Does the issue show up for you with the following simple example:

```python
import justpy as jp

def select_test():
    wp = jp.QuasarPage()
    d = jp.Div(classes="q-pa-md", style="max-width: 300px", a=wp)
    s1 = jp.QSelect(label='Label', a=d, color='orange', standout=True)
    s1.options = ['Google', 'Facebook', 'Twitter', 'Apple', 'Oracle']
    return wp


jp.justpy(select_test)
```

**Comment by knoxvilledatabase** [comment]
It has to do with having a large dataset for options. I'm working towards reproducing this outside of my codebase, thank you for being patient.
