### ISSUE TITLE
Chart with multiple Y axes?

### ISSUE THREAD

**Issue by johnmudd** [elimintz/justpy#122]
It it feasible to create one chart from the following type data where all data shares the same X values (timestamp) along with one or more Y values? Some of the Y values such as the three "cpu" values share the same units (percent) and can be overlaid on the same chart. But displaying cpu along with temp (deg F) either need an extra Y axis in order to overlay or a separate sub-chart similar to the way the Stock chart shows both Open/High/Low/Close and Volume on the same chart. Ideally I'd like to let a user select which of the eight Y values to add to the chart and then my program would build the chart. The goal is to look for correlations between the different Y values.

Example: https://stackoverflow.com/a/50655786/487992

```
                     time   rxxx_cpu   pg_cpu   other_cpu   reads   writes     du   temp   ctree
0     2020-08-05 05:00:00        0.0      0.0         0.3       0       95      0    111       0
1     2020-08-05 05:00:10        0.0      1.2         0.3    2782      170     60    113       0
2     2020-08-05 05:00:20        0.0      1.0         0.3    1642      193   7024    113       0
3     2020-08-05 05:00:30        0.0      1.0         0.2    1814      156   8320    114       0
4     2020-08-05 05:00:40        0.0      1.3         0.3    1654       59   9592    114       0
...                   ...        ...      ...         ...     ...      ...    ...    ...     ...
5141  2020-08-05 19:18:40        0.0      0.5         0.3     864       85  17840    118       0
5142  2020-08-05 19:18:50        0.0      0.5         0.3     842       40  17904    118       0
5143  2020-08-05 19:19:00        0.0      0.5         0.3     744    18354  17492    118       3
5144  2020-08-05 19:19:10        0.0      0.5         0.2     488       78  17808    118       0
5145  2020-08-05 19:19:20        0.1      0.6         0.3     648      172  17932    118       3
```

**Comment by johnmudd** [comment]
Maybe I should first try to get it working with Plotly instead of JustPy. Assuming I can combine these two examples.

https://plotly.com/python/time-series/#time-series-with-range-selector-buttons
https://plotly.com/python/multiple-axes/#multiple-axes

**Comment by elimintz** [comment]
This can be done using highcharts in JustPy:
https://www.highcharts.com/demo/combo-multi-axes

**Comment by johnmudd** [comment]
Thanks
