### ISSUE TITLE
Bug: Problem with long Debounce 

### ISSUE THREAD

**Issue by snoodlenay** [elimintz/justpy#123]
In this example, there are two textareas, with debounce set to 5000. With a long timeout like this, there is a problem if you type in one box and then begin typing in another _before_ the timeout period passes. I'll leave it as a fun experiment to see what happens. 

To save some time, here are some notes:

- If you wait until the debounce threshold passes before you begin typing in another box, the wonkiness doesn't happen.
- If you are in a wonky box, and pause long enough for the timeout period to pass, and then resume typing, the wonkiness discontinues. 
- You can go back and forth from box to box, having the wonkiness follow you.

```python
import justpy as jp

form_data = {}
for section in range(3):
    form_data[f'radio_{section}'] = 1
    form_data[f'text_{section}'] = ''

def debounce_example():
    wp = jp.WebPage()

    h = jp.Div(a=wp, classes="pl-12 pr-8 flex items-center justify-between text-lg text-white flex-wrap bg-gray-800 py-6")

    block_wrapper = jp.Div(a=wp, classes="flex items-center px-5 pb-5 grid grid-cols-1")
    blocks = []
    for section in range(2):
        r = Block(section, 5000, a=block_wrapper)
        blocks.append(r)

    return wp


class Block(jp.Div):
    def __init__(self, section, debounce, **kwargs):
        super().__init__(**kwargs)
        self.section = section

        self.classes = classes=f"leading-5 ml-8 mt-3 mr-4 mb-0 items-center grid grid-cols-5"

        # heading line
        jp.Div(id=f"{self.section}-head", a=self, text=f"Debounce: {debounce} - section {section}", classes="pl-3 p-1 bg-gray-800 text-white col-span-3")

        # left column
        form_body = jp.Div(a=self, classes="p-2 pl-3 text-sm bg-gray-200 col-span-3 h-full text-gray-800")


        # text input
        self.section_input = jp.Div(a=self, classes="bg-white flex border border-gray-100 col-span-3 h-full")

        self.ta = jp.Textarea(a=self.section_input,
                                  classes="h-18 pl-3 p-1 text-sm appearance-none outline-none w-full align-top text-gray-800",
                                  )

        self.ta.on('input', self.text_input, debounce=debounce)

    def text_input(self, msg):
        print(self.ta.value)


jp.justpy(debounce_example)
```

**Comment by elimintz** [comment]
This is not a bug but the expected behavior. To get the behavior you want, change text_input to the following:

```python
    def text_input(self, msg):
        print(self.ta.value)
        return True
```

If anything but None is returned the framework does not update the page which is what you want here.

This solves the problem because on the server side the value of the text area has not been updated yet, so the previous value is put in until the debounce period ends.

If this is not clear, please let me know.

**Comment by snoodlenay** [comment]
It is sort of clear. When I look at https://justpy.io/tutorial/handling_events/ none of the examples return True, so I'm not entirely sure when I need to do that and when I don't. But if I make all of my handlers return True, all of my problems go away, so I'm happy...for now :)

**Comment by elimintz** [comment]
For simplicity sake, the choice I made was to have the framework update the page if a handler returns None. None is returned when there is no return statement in a python function. Usually, when I do something in a handler, you want the change reflected on the page so this default makes sense. 

For the occasions you don't, return True makes sure the page is not updated when the handler finishes running.

**Comment by snoodlenay** [comment]
Ah. That ties the pieces together. Thank you.
