### ISSUE TITLE
No module named 'html.parser'

### ISSUE THREAD

**Issue by andy47** [elimintz/justpy#124]
I've done something in the last day or so to break justpy. I thought I had a bug in my code but I'm seeing the same errors with a clean install in a new virtual environment. Can anyone point me at what I've done to cause this bug. Thanks.

    $ python3 -m venv .venv
    $ . .venv/bin/activate.fish
    (.venv) $ python -m pip install justpy
    ...
    Successfully installed MarkupSafe-1.1.1 addict-2.2.1 aiofiles-0.5.0 certifi-2020.6.20 chardet-3.0.4 click-7.1.2 demjson-2.2.4 h11-0.9.0 httpcore-0.10.1 httptools-0.1.1 httpx-0.14.1 idna-2.10 itsdangerous-1.1.0 jinja2-2.11.2 justpy-0.1.3 rfc3986-1.4.0 sniffio-1.1.0 starlette-0.13.7 uvicorn-0.11.8 uvloop-0.14.0 websockets-8.1
    (.venv) $ cat > hello_world.py
    import justpy as jp

    def hello_world():
        wp = jp.WebPage()
        d = jp.Div(text='Hello world!')
        wp.add(d)
        return wp

    jp.justpy(hello_world)
    ^C
    (.venv) $ python hello_world.py
    Traceback (most recent call last):
      File "hello_world.py", line 1, in <module>
        import justpy as jp
      File "/Users/andy47/Scratch/jptutorial/.venv/lib/python3.7/site-packages/justpy/__init__.py", line 1, in <module>
        from .justpy import *
      File "/Users/andy47/Scratch/jptutorial/.venv/lib/python3.7/site-packages/justpy/justpy.py", line 12, in <module>
        from .htmlcomponents import *
      File "/Users/andy47/Scratch/jptutorial/.venv/lib/python3.7/site-packages/justpy/htmlcomponents.py", line 4, in <module>
        from html.parser import HTMLParser, tagfind_tolerant, attrfind_tolerant
    ModuleNotFoundError: No module named 'html.parser'; 'html' is not a package

**Comment by elimintz** [comment]
The problem seems to be that html.parser module cannot be found:  https://docs.python.org/3/library/html.parser.html
It is a standard module in Python 3 so I am thinking maybe you have a version problem.

In the virtual environment type just `python` to get into the python console. Which version of python is activated? If it is not version 3.6 or higher, that may be your problem.

If the version is ok, please type the following:
```python
from html.parser import HTMLParser
```

Let me know if this works or if you get an error.

**Comment by andy47** [comment]
Sorry, I'm an idiot. I had created a `html.py` file in my project directory and this was being read before the standard library module. Thanks for the help.
