### ISSUE TITLE
Decorators for WebPage functions

### ISSUE THREAD

**Issue by snoodlenay** [elimintz/justpy#126]
I've been playing with decorating my functions all afternoon. I've learned that there is a _feature_ (see, I'm learning!) that seems to limit routable functions to a single argument: request. Say I want to have a decorator add an argument to my page's context. This raises `AssertionError: Function home cannot have more than one parameter`:
```python
import justpy as jp
from functools import wraps

def what_fruit(f):
    @wraps(f)
    def inner(request, fruit):
        return f(request, 'banana')
    return inner

@what_fruit
def home(request, fruit=''):
    wp = jp.WebPage()
    jp.Div(a=wp, text=fruit)
    return wp

jp.justpy(home)
```
We can use the pattern for session handling, from https://justpy.io/tutorial/sessions/, as a workaround to accomplish the same goal (below). 

```python
import justpy as jp
from functools import wraps

user_fruits = {}

def what_fruit(f):
    @wraps(f)
    def inner(request):
        global user_fruits
        user_fruits[request.session_id] = 'banana'
        return f(request)

    return inner

@what_fruit
def home(request):
    wp = jp.WebPage()
    jp.Div(a=wp, text=user_fruits[request.session_id])
    return wp

jp.justpy(home)
```
So, that's _not_ my problem. I detail this, in case I'm overlooking a feature that makes it easier to inject arguments into a routable function.

Where I'm running into trouble is forcing redirects in decorators.  The most common use case, for me, is using decorators for authorization and access control. Here's an example from an old Flask app that shows how one might test an argument and, upon failure, redirect to something else. In this case, if the id is not valid, send the person to the home page.

```python
def valid_id(f):
    @wraps(f)
    def wrapper(id, *args, **kwargs):
        bool_outcome = test_id(id)
        if bool_outcome:
            return f(id, *args, **kwargs)
        else:
            return redirect(url_for('www.home'))
    return wrapper
```

I want to make use of WebPage.redirect from within the decorator, but I have access _only to the response object_ within the decorator, and no access to the WebPage object. I can use a session or other global mapping, as above, but I would still need to repeat the routines that handle unauthorized calls, within every protected page. Is there a way to do something like the above, in JustPy?

**Comment by elimintz** [comment]
1. In the next version I can relax the requirement that request handlers have only 1 or no arguments if we reach the conclusion that this is the best option. 
Request handlers are inspected by the code before being run to check if they are async or not and as to whether there is one or zero arguments supplied: https://github.com/elimintz/justpy/blob/master/justpy/justpy.py#L139

2. I think this is what you are looking for:

```python
import justpy as jp
from functools import wraps


logged_in = {}

def test_id(id):
    return id in logged_in

def valid_id(f):
    @wraps(f)
    def wrapper(request):
        bool_outcome = test_id(request.session_id)
        if bool_outcome:
            return f(request)
        else:
            return redirect_handler()
    return wrapper

def page_ready(self, msg):
    msg.page.redirect = '/'

def redirect_handler():
    wp = jp.WebPage()
    # There will be an error if WebPage instance is empty
    wp.add(jp.Div())
    wp.on('page_ready', page_ready)
    return wp

def login_user(self, msg):
    print(msg)
    logged_in[msg.session_id] = True
    print(logged_in)

@jp.SetRoute('/login')
def login_page(request):
    wp = jp.WebPage()
    btn = jp.Button(text='Login', classes='m-4 ' + jp.Styles.button_simple, click=login_user, a=wp)
    return wp

@jp.SetRoute('/info')
@valid_id
def info_page(request):
    wp = jp.WebPage()
    jp.Div(text='Some info', classes='m-2 text-xl', a=wp)
    return wp

def home_page():
    wp = jp.WebPage()
    jp.A(text='Click to go to login page ', href='/login', a=wp, classes='m-4 text-xl' )
    return wp


jp.justpy(home_page)


```

If you go to http://127.0.0.1:8000/info without having logged in first you are redirected to the home page.
This probably needs more testing, so if you discover some new *features*, let me know.

**Comment by snoodlenay** [comment]
That works. And it looks like redirect_handler() doesn't need to be its own function, if one isn't re-using it. This also works:
```python
def valid_id(f):
   @wraps(f)
   def wrapper(request):
       bool_outcome = test_id(request.session_id)
       if bool_outcome:
           return f(request)
       else:
           wp = jp.WebPage()
           # There will be an error if WebPage instance is empty
           wp.add(jp.Div())
           wp.on('page_ready', page_ready)
           return wp
   return wrapper

def page_ready(self, msg):
   msg.page.redirect = '/'
```

Is there a way to add arbitrary arguments to the msg or to the function call in an event handler? I'm thinking that something like this would add a lot of flexibility:

```python
def page_ready(self, msg):
    msg.page.redirect = msg.function_args['url']

wp.on('page_ready', page_ready, function_args={'url': '/'})
```

**Comment by elimintz** [comment]
When you create a user defined components, you can add field to msg: https://justpy.io/tutorial/custom_components/#handling-the-change-event

You can't do that with page_ready but there is a simple solution:
```python
def page_ready(self, msg):
    msg.page.redirect = msg.page.function_args['url']

wp.function_args = {'url': '/'}
wp.on('page_ready', page_ready)
```

Note: Thank you for this issue following which I made a change. From the next version you won't need to specify the redirect with page_ready. You will be able to assign redirect in the request handler.

**Comment by snoodlenay** [comment]
Thanks, as always, for your help. Here's where I wound up.
```python
def valid_id(f):
   @wraps(f)
   def wrapper(request):
       bool_outcome = test_id(request.session_id)
       if bool_outcome:
           return f(request)
       else:
           return redirect('/')
   return wrapper

def redirect(url):
    wp = jp.WebPage()
    wp.add(jp.Div())
    wp.function_args = {'url': url}
    wp.on('page_ready', page_ready)
    return wp

def page_ready(self, msg):
    msg.page.redirect = msg.page.function_args['url']
```

I'm happy to quit on a win, but I'm also curious to learn more. Any thoughts about why this nested approach doesn't work? 

```python
def valid_id(f):
   @wraps(f)
   def wrapper(request):
       bool_outcome = test_id(request.session_id)
       if bool_outcome:
           return f(request)
       else:
           return redirect('/')
   return wrapper

def redirect(url):
    def page_ready(self, msg):
        msg.page.redirect = url
    wp = jp.WebPage()
    wp.add(jp.Div())
    wp.on('page_ready', page_ready)
    return wp
```

**Comment by snoodlenay** [comment]
Ugh...nevermind. That _does_ work. I had a typo in my running version.  

Maybe this can become justpy.redirect()?
```python
def redirect(url):
    def page_ready(self, msg):
        msg.page.redirect = url
    wp = jp.WebPage()
    wp.add(jp.Div())
    wp.on('page_ready', page_ready)
    return wp
```

**Comment by elimintz** [comment]
Thanks, that is a good idea. I will add it to the next version.
