### ISSUE TITLE
Redirect immediately to Active Directory login

### ISSUE THREAD

**Issue by matthewhoendorf** [elimintz/justpy#127]
Hi,

I'm implementing login via Azure Active Directory. I was able to get it working with a login button. Here's the stripped down code: https://hastebin.com/nugiwukoza.py. 

It imports config.py file with the following variables (real values ommitted): 

```
GRAPH_URL = "https://graph.microsoft.com" 
TENANT = "ourcompany.com"
AUTHORITY_HOST_URL = "https://login.microsoftonline.com"
CLIENT_ID = "Azure application resource ID"
CLIENT_SECRET = "Azure application secret"
```

I was trying to automatically redirect to the authorization_url if a user is not logged in. I've tried ```wp.redirect``` and ```wp.on('page_ready', sign_in_click)``` but neither of these seem to work. Is this possible?

Thanks!

**Comment by elimintz** [comment]
Yes, this is possible to do. 

One initial observation is that `sign_in_click` is defined inside `login_page` so may not be accessible globally.

If you make `sign_in_click` global and add `wp.on('page_ready', sign_in_click)` for the appropriate pages, it should work. 

If it doesn't, let me know and we'll take it from there.


Please take a look at https://github.com/elimintz/justpy/issues/126 
Similar issues are covered.

**Comment by matthewhoendorf** [comment]
Thanks for the reply and for the example in the other ticket. Very helpful.

It turned out that my issue was setting the session_id in  ```sign_in_click``` (which I had changed to a global function):

```
 def sign_in_click(self, msg):
        auth_state = self.session_id
        authorization_url = TEMPLATE_AUTHZ_URL.format(
            config.TENANT,
            config.CLIENT_ID,
            REDIRECT_URI,
            auth_state,
            config.GRAPH_URL)
        msg.page.redirect = authorization_url
```

When using ```wp.on('page_ready', sign_in_click)```, I had to change the code to reference the ```msg``` object rather than ```self``` (i.e. ```auth_state = msg.session_id```).  It wasn't throwing an error in the logs - I only caught it when I added printing + try/except.
