### ISSUE TITLE
ag-grid tree data display mode

### ISSUE THREAD

**Issue by rroyer-xyz** [elimintz/justpy#130]
Hello,
I have a use case for ag-grid's  [tree data display mode](https://www.ag-grid.com/javascript-grid-tree-data/).

The docs say "when providing tree data to the grid you implement the gridOptions.getDataPath(data) callback to tell the grid the hierarchy for each row." Is there a way to do this in JustPy? Or any sort of workaround that could be recommended?

Below is a mocked up example. 

Many thanks!!!

```
import justpy as jp

grid_options = {
    'getDataPath': '''function(data) {
        return data.orgHierarchy;
    }''',
    'treeData': True,
    'defaultColDef': {
        'filter': True,
        'sortable': True,
        'resizable': True,
    }, 
    'columnDefs': [
        {'headerName': "job title", 'field': "jobTitle"},
        {'headerName': "employment type", 'field': "employmentType"},
    ],
    'rowData' : [
        {'orgHierarchy': ['Erica'], 'jobTitle': "CEO", 'employmentType': "Permanent"},
        {'orgHierarchy': ['Erica', 'Malcolm'], 'jobTitle': "VP", 'employmentType': "Permanent"},
        {'orgHierarchy': ['Erica', 'Bob'], 'jobTitle': "SVP", 'employmentType': "Permanent"}
    ]   
}

def grid_test():
    wp = jp.WebPage()
    grid = jp.AgGrid(a=wp, options=grid_options)
    return wp

jp.justpy(grid_test)
```

**Comment by rroyer-xyz** [comment]
Just a quick follow-up... your suggestion worked out great

**Comment by elimintz** [comment]
Version 0.1.4 just released and addresses this problem in a more general fashion:
https://justpy.io/grids_tutorial/field_evaluation/
