### ISSUE TITLE
How to toggle fullscreen mode?

### ISSUE THREAD

**Issue by swevm** [elimintz/justpy#134]
Am trying to get a JustPy app to run in fullscreen mode if I click a button. With Quasar one should be able to call AppFullscreen.toggle() to shift between fullscreen or window mode. When I try calling AppFullscreen.toggle() using run_method on a QuasarPage nothing happens but in Chrome Developer I see below error. 
Guess I´m calling AppFullscreen the wrong way.

Any idea how to do this?

`
Uncaught TypeError: Cannot read property 'AppFullscreen' of undefined
    at eval (eval at <anonymous> ((index):1641), <anonymous>:1:17)
    at WebSocket.<anonymous> ((index):1743)
`

Quasar Fullscreen methods:

`
Boolean) AppFullscreen.isCapable

// Determining if website is in fullscreen mode:
(Boolean) AppFullscreen.isActive

// Requesting fullscreen mode:
AppFullscreen.request()

// Exiting fullscreen mode:
AppFullscreen.exit()

// Toggle fullscreen mode:
AppFullscreen.toggle()
`

**Comment by elimintz** [comment]
Here is an example of how to do this:
```python
import justpy as jp

async def toggle_screen(self, msg):
    await msg.page.run_javascript('Quasar.AppFullscreen.toggle()')

def full_screen_test():
    wp = jp.QuasarPage()
    d = jp.Div(classes='q-pa-md q-gutter-sm', a=wp)
    jp.QBtn(color='primary', label='Toggle Screen', a=d, click=toggle_screen)
    return wp

jp.justpy(full_screen_test)
```

Please let me know if something is not clear or this does not work for you.

**Comment by swevm** [comment]
That was fast! Thanks
Your solution work great 👍 

Being able to do this more programmatically instead of having to send javascript code to frontend would be beneficial imho.
Would you consider adding this as a property to WebPage()?

**Comment by elimintz** [comment]
That is a good idea, thanks. I will add it to QuasarPage as a method.
