### ISSUE TITLE
ag-grid using grid methods

### ISSUE THREAD

**Issue by rroyer-xyz** [elimintz/justpy#135]
Hi - I have a use case that involves a user making selections in ag-grid, then clicking a button. When the button is clicked, I need the selected rows to return to their "unselected" state. In the past, I've done this with gridOptions.api.deselectAll(). What's the recommended way to this in JustPy?

On a related note, I see an upcoming need for using additional grid api methods and creating custom JS cell renderers. I assume I would apply a similar solution as the use case above.

I'm happy to make updates in the aggrid.js template file (or wherever else is needed). Just need a little bit of guidance on where those updates should be made.

Thanks

**Comment by elimintz** [comment]
The end of this week or early next week, I will be releasing a new version of JustPy with improvements for the ag-grid component. For example, there will be a checkbox cell render. You will be able to see the implementation in the JavaScript and it will be clear where additional renderers need to be defined.

As for calling the ag-grid api here is an example of how to do it. I will try to simplify this by adding methods on the Python side in a future version.

```python
import justpy as jp

grid_options = """
{
    rowSelection: 'multiple',
    defaultColDef: {
        filter: true,
        sortable: true,
        resizable: true,
        cellStyle: {textAlign: 'center'},
        headerClass: 'font-bold'
    }, 
      columnDefs: [
      {headerName: "Make", field: "make"},
      {headerName: "Model", field: "model"},
      {headerName: "Price", field: "price"}
    ],
      rowData: [
      {make: "Toyota", model: "Celica", price: 35000},
      {make: "Ford", model: "Mondeo", price: 32000},
      {make: "Porsche", model: "Boxter", price: 72000}
    ]
}
"""

def row_selected(self, msg):
    print(msg.selected, msg)
    wp = msg.page
    if msg.selected:
        wp.selected_rows[msg.rowIndex] = msg.data
    else:
        wp.selected_rows.pop(msg.rowIndex)
    s = f'Selected rows {sorted(list(wp.selected_rows.keys()))}'
    for i in sorted(wp.selected_rows):
        s = f'{s}\n Row {i}  Data: {wp.selected_rows[i]}'
    if wp.selected_rows:
        wp.rows_div.text = s
    else:
        wp.rows_div.text = 'No row selected'


async def select_all_rows(self, msg):
    await msg.page.run_javascript(f"""cached_grid_def['g' + {self.grid.id}].api.selectAll()""")


async def deselect_rows(self, msg):
    await msg.page.run_javascript(f"""cached_grid_def['g' + {self.grid.id}].api.deselectAll()""")


def grid_test():
    wp = jp.WebPage()
    wp.selected_rows = {}  # Dictionary holding selected rows
    grid = jp.AgGrid(a=wp, options=grid_options, style='height: 200px; width: 300px; margin: 0.25em')
    grid.options.columnDefs[0].checkboxSelection = True
    grid.on('rowSelected', row_selected)
    wp.rows_div = jp.Pre(text='Data will go here when you select rows', classes='border text-lg', a=wp)
    btn_deselect = jp.Button(text='Deselect rows', classes=jp.Styles.button_simple+' m-2', a=wp, click=deselect_rows)
    btn_deselect.grid = grid
    btn_select_all = jp.Button(text='Select all rows', classes=jp.Styles.button_simple+' m-2', a=wp, click=select_all_rows)
    btn_select_all.grid = grid
    return wp


jp.justpy(grid_test)
```

**Comment by rroyer-xyz** [comment]
Thanks for your quick response (as always). This works great. Looking forward to the next release. 

JustPy is very impressive framework BTW.
