### ISSUE TITLE
How to use unicode language characters in Highchart ?

### ISSUE THREAD

**Issue by jomosi** [elimintz/justpy#136]
Unicode characters in Hightchart are not displayed at all.
Is there a way to do it ?
Thanks.
![fruit-consumption](https://user-images.githubusercontent.com/6382269/91426154-121fc880-e897-11ea-8cd5-1a35e5f6974a.png)

-------------------------------

import justpy as jp

#Example from https://www.highcharts.com/docs/getting-started/your-first-chart

my_chart_def = """
{
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Fruit Consumption'
        },
        xAxis: {
            categories: ['사과(Korean)', 'Bananas', '橙子(Chinses)']
        },
        yAxis: {
            title: {
                text: 'Fruit eaten'
            }
        },
        series: [{
            name: 'Jane',
            data: [1, 0, 4]
        }, {
            name: 'John',
            data: [5, 7, 3]
        }]
}
"""

def chart_test():
    wp = jp.WebPage()
    my_chart = jp.HighCharts(a=wp, classes='m-2 p-2 border', style='width: 600px')
    my_chart.options = my_chart_def
    return wp

jp.justpy(chart_test)

**Comment by elimintz** [comment]
If you use a Python dict for the options, instead of a string representation of a JavaScript object,  it will work:

```python
import justpy as jp


my_chart_def = {
    'chart': {
        'type': 'bar'
    },
    'title': {
        'text': 'Fruit Consumption 橙子',
    },
    'xAxis': {
        'categories': ['사과(Korean)', 'Bananas', '橙子(Chinses)']
    },
    'yAxis': {
        'title': {
            'text': 'Fruit eaten'
        }
    },
    'series': [{
        'name': 'Jane',
        'data': [1, 0, 4]
    }, {
        'name': 'John',
        'data': [5, 7, 3]
    }]
}


def chart_test():
    wp = jp.WebPage()
    my_chart = jp.HighCharts(a=wp, classes='m-2 p-2 border', style='width: 600px')
    my_chart.options = my_chart_def
    print(my_chart.options)
    return wp


jp.justpy(chart_test)

```
