### ISSUE TITLE
Support for QSideLink components

### ISSUE THREAD

**Issue by matthewhoendorf** [elimintz/justpy#137]
I'm currently using a QDrawer with QItem components to switch page views. However, it seems like I really want to use QSideLink components instead to preserve window history.

Quasar docs: https://v0-14.quasar-framework.org/components/layout-side-links.html

Is their a native way to achieve this? I tried parsing HTML and got the error ```Tag not defined: q-side-link``` so I think not.

**Comment by matthewhoendorf** [comment]
I'm realizing that I'm looking at old docs. So I guess my question is, can QItems link to pages?

**Comment by elimintz** [comment]
A simple option is to assign a click event handler to do this and use the `redirect` attribute:

```python
import justpy as jp


def go_to_other_page(self, msg):
    msg.page.redirect = '/other_page'

def quasar_example():
    wp = jp.QuasarPage()
    c1 = jp.Div(classes='q-pa-md', style='max-width: 350px', a=wp)
    c2 = jp.QList(bordered=True, a=c1)
    c3 = jp.QItem(clickable=True, v_ripple=True, a=c2)
    c4 = jp.QItemSection(avatar=True, a=c3)
    c5 = jp.QIcon(color='primary', name='bluetooth', a=c4)
    c6 = jp.QItemSection(a=c3, text='Icon as avatar')
    c7 = jp.QItem(clickable=True, v_ripple=True, a=c2)
    c8 = jp.QItemSection(avatar=True, a=c7)
    c9 = jp.QAvatar(color='teal', text_color='white', icon='bluetooth', a=c8)
    c10 = jp.QItemSection(a=c7, text='Click to go to other page')
    c11 = jp.QItem(clickable=True, v_ripple=True, a=c2)
    c12 = jp.QItemSection(avatar=True, a=c11)
    c13 = jp.QAvatar(rounded=True, color='purple', text_color='white', icon='bluetooth', a=c12)
    c14 = jp.QItemSection(a=c11, text='Rounded avatar-type icon')

    c7.on('click', go_to_other_page)

    return wp


@jp.SetRoute('/other_page')
def home_page():
    wp = jp.QuasarPage()
    jp.Div(text='Some other page', classes='q-pa-md text-h3', a=wp)
    return wp

jp.justpy(quasar_example)
```

If this does not solve your problem or is not clear, please let me know

**Comment by pabloazurduy** [comment]
Hi, I was trying the same thing with `my_item = jp.QItem(clickable=True, v_ripple=True, a=c2)` is there a way to give a `href` or pass some argument to the click function ? so you could have `msg.page.redirect = f'{self.href}'` or something like that in the `go_to_other_page` function 

Thanks !
