### ISSUE TITLE
How can you use your own css classes in justpy?

### ISSUE THREAD

**Issue by rohezal** [elimintz/justpy#143]
Sorry for the stupid question. Maybe some one will find it via google and can learn something from it stackoverflow style.

How to do I use the custom css with justpy.

"You can also put your own CSS on a page and use your own class definitions by setting the css attribute of a page."
https://justpy.io/tutorial/basic_concepts/

Do I just use:

```
    wp = jp.WebPage(delete_flag=False)
    wp.css("/what/path/to/own/style.css")

```

?

Could you provide an example?

Found a work around :)
  

```
css_string="""
<style>
div.static {
  position: static;
  border: 3px solid #73AD21;
}
</style>
"""


    wp = jp.WebPage()
    #wp.css=css_string #does not work

    wp.head_html = css_string #does work
```

**Comment by elimintz** [comment]
https://justpy.io/reference/webpage/#css

The css way will work also without the style html tags, just the class definition.

**Comment by rohezal** [comment]
Thank you for your reply. I am very grateful for your help and very sorry for wasting your time. Thank you again this wonderful framework :).

**Comment by elimintz** [comment]
You are not wasting my time, thanks for using JustPy!

**Comment by Lefort-Antoine** [comment]
Hy,
Can I have an example for a Quasar element please!
I've trouble to do it.
Thanks very much
