### ISSUE TITLE
replacing grid on event not working 

### ISSUE THREAD

**Issue by jomosi** [elimintz/justpy#145]
Hi, 

What I want to do is replacing gird on div when button is clicked, but code below is not working.

Am I doing wrong? Could you please let me know the right way ?

I am using jp 0.14.

thanks.

==========================

    def btn_click(self, msg):
        self.div.delete_components()
        df = pd.DataFrame([(str(datetime.now()),str(datetime.now()))], columns=['a', 'b'])
        df.jp.ag_grid(a=self.div, style='height: 100px; width: 400px')
        print(self.div.components)
                
    def main_page():
        wp = jp.WebPage()
        btn = jp.Button(text='button', a=wp, click=btn_click)
        div = jp.Div(a=wp)
        btn.div = div
        return wp    
    
    if __name__ == "__main__":
        jp.justpy(main_page)

**Comment by elimintz** [comment]
The recommended way to replace data in a grid is the following:

```python
import justpy as jp
import pandas as pd
from datetime import datetime


def btn_click(self, msg):
    df = pd.DataFrame([(str(datetime.now()), str(datetime.now()))], columns=['a', 'b'])
    temp_grid = df.jp.ag_grid(style='height: 100px; width: 400px')
    self.div.grid.options = temp_grid.options


def main_page():
    wp = jp.WebPage()
    btn = jp.Button(text='button', a=wp, click=btn_click)
    div = jp.Div(a=wp)
    df = pd.DataFrame([(str(datetime.now()), str(datetime.now()))], columns=['a', 'b'])
    div.grid = df.jp.ag_grid(a=div, style='height: 100px; width: 400px')
    btn.div = div
    return wp


jp.justpy(main_page)
```

Please let me know if something is not clear.

**Comment by jomosi** [comment]
Thank you for recommendation. 

But in my environment, components in Div should be dynamic. 
Sometimes, there should be <P, A, "Grid", Table> and then <P, A> for other situation, So I was trying to delete all the previously added components and add new components.
If Grid should be handled differently, I am going to change some parts of the UI.

Thank you.
