### ISSUE TITLE
QSelect with filter

### ISSUE THREAD

**Issue by platinops** [elimintz/justpy#146]
With reference to issue #83: did @knoxvilledatabase ever share his QSelectWithFilter?

I'm trying to implement this myself using the [Quasar filter event](https://quasar.dev/vue-components/select#Native-attributes-with-use-input) (rather than keyup), but am stuck with the JS part.

Test code:

```
import justpy as jp

class QFilter(jp.QSelect):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.use_input = True
        self.fill_input = True
        self.hide_selected = True
        self.input_debounce = 0
        self.options_all = self.options
        self.on('filter', self.filter_options)

    @staticmethod
    def filter_options(self, msg):
        if msg.value=='':
            self.options = self.options_all
        else:
            self.options = [item for item in self.options_all if msg.value.lower() in item.lower()]

def filter_test():
    wp = jp.QuasarPage()
    d = jp.Div(classes="q-pa-md", style="max-width: 300px", a=wp)
    opts = ['Google', 'Facebook', 'Friendster', 'Twitter', 'Apple', 'Oracle']
    jp.QSelect(label='QSelect', a=d, outline=True, options = opts)
    QFilter(label='QFilter', a=d, outline=True, options = opts)
    return wp

jp.justpy(filter_test)
```

I modified quasar_components.js by including the following lines:
```
                case 'filter':
                    fn = this.filterEvent;
                    break;```
```
```
        filterEvent: (function (event) {
            this.eventFunction(event, 'filter');
        }),
```
But I'm guessing that's insufficient to do the trick..

**Comment by knoxvilledatabase** [comment]
@platinops, does this help you?

```
class QSelectWithFilter(jp.QSelect):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.initial_options = kwargs.get('options', [])
        self.use_input = True
        self.allowed_events = ['input', 'remove', 'add', 'new_value', 'filter', 'filter_abort', 'keyup', 'focus', 'blur']
        self.on('keyup', self.filter_function)

    def filter_function(self, msg):
        self.options = list(filter(lambda x: msg.value.lower() in str(x['label']).lower(), self.initial_options))

```

**Comment by platinops** [comment]
That does work, thanks!

I did have to make a small modification:
`self.options = list(filter(lambda x: msg.value.lower() in str(x).lower(), self.initial_options))`
rather than:
`self.options = list(filter(lambda x: msg.value.lower() in str(x['label']).lower(), self.initial_options))`

Also, `self.allowed_events.append('keyup')` seems more future-proof in case the QSelect events would change over time.

@elimintz As you mentioned in the other thread, I imagine this class can be useful to other users as well.

**Comment by elimintz** [comment]
Thanks to both of you! I will add it to the package in a future version.
