### ISSUE TITLE
dependency with h11 causes wrong behaviour of justpy apps

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#148]
Since few days, I got a strange behavior from a justpy application.
It starts looping over the main function, with this error at the console:

    WARNING:  Unsupported upgrade request.
    WARNING h11_impl: Unsupported upgrade request.

I guess is due to some changes in the underlining library h11.

What can I do to downgrade to the previous stable situation?

Thank's.

**Comment by giodegas** [comment]
the problem seem's to be related to the `uvicorn `library upgrade.

can you confirm?

**Comment by giodegas** [comment]
the last "good" version appears to be `uvicorn 0.11.8` .

**Comment by elimintz** [comment]
Is the warning crashing you program or does it still run?

**Comment by giodegas** [comment]
No crash, but it became unusable since it keep refreshing the page.

**Comment by elimintz** [comment]
Did this happen in all your justpy applications or just one?

**Comment by giodegas** [comment]
All, cannot run cleanly even basic examples .
Now I downgraded and I will not upgrade  for a while.

**Comment by platinops** [comment]
I had the same issue after installing a fresh Python 3.8 on Windows and running pip install justpy - even with the [basic hello world routine](https://justpy.io/tutorial/getting_started/).

Below the result of `pip freeze` of the venv to reproduce the issue:

```
addict==2.3.0
aiofiles==0.5.0
certifi==2020.6.20
click==7.1.2
demjson==2.2.4
h11==0.11.0
httpcore==0.12.0
httpx==0.16.0
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
justpy==0.1.4
MarkupSafe==1.1.1
rfc3986==1.4.0
sniffio==1.1.0
starlette==0.13.8
uvicorn==0.12.1
```
Seems to be a [uvicorn/h11/httpcore](https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/http/h11_impl.py) issue.

**Comment by elimintz** [comment]
@platinops Could you please open an issue with this at the uvicorn? Does this problem arise also for starlette applications that are not JustPy?  Any help in understanding what is going on would be much appreciated.

**Comment by platinops** [comment]
Both the [starlette](https://www.starlette.io/) and [uvicorn](https://www.uvicorn.org/) hello world examples are running fine, unlike Justpy. With justpy, the page keeps on asking to be reloaded.

I only saw the error is thrown by uvicorn. I might have jumped the gun on concluding the issue was theirs.

Are you not able to get the same behaviour on a venv with the packages from my pip freeze list?

**Comment by elimintz** [comment]
@platinops Could you please try this with `pip install uvicorn[standard]`? I got this advice on the uvicorn gitter board.
Unfortunately, I am busy doing something else right now and can only get to this next week

**Comment by platinops** [comment]
@elimintz That indeed worked, thanks. More specifically, `websockets` was the missing package. This is no minimal requirement for either unicorn, starlette or justpy. So when you simply run `pip install justpy` on a fresh Python venv, you get the above error.

**Comment by elimintz** [comment]
Thank you very much, I will change the setup file of the project to reflect this early next week.
If I understand correctly  the following is a workaround that works:
`pip install justpy`
and then:
`pip install uvicorn[standard]`

Can you please confirm that?

**Comment by platinops** [comment]
Confirmed, `pip install justpy uvicorn[standard]` works.

But `pip install justpy websockets` also works.

The difference between both are the following packages: `colorama` `python-dotenv` `PyYAML` `watchgod`. This is in line with what's [stated on the uvicorn page](https://www.uvicorn.org/#quickstart).
