### ISSUE TITLE
Letters and flickering and start missing when using keyup / keydown events on input objects.

### ISSUE THREAD

**Issue by rohezal** [elimintz/justpy#149]
There is flickering and letters start missing when and input reacts to a keydown or keyup event. Even with throttling and with debouncing. I just put a button next to chat and people can press Tab and then Enter so send a message via keyboard. Is there a way to capture an "Enter Key was Pressed" message for an input object? Maybe I am just doing it wrong, coming from the signal slot world of QT.

```
class Chat(jp.Div):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.chatinput = jp.Input(a=self, name="chatinput", placeholder="Type here and press Enter", classes="w-full h-8", keydown=self.donothing)

    def donothing(self,msg):
        print(msg)


```

**Comment by elimintz** [comment]
The flickering is caused when the page is updated. If an event handler returns anything but None, the page is not updated.

Here is an example where you would check for the Enter key in an input element:

```python
import justpy as jp


def key_down(self, msg):
    print(msg.key_data.key)
    if msg.key_data.key == 'Enter':
        jp.Div(text='Enter pressed', a=msg.page, classes='m-1 p-2')
        return
    return True  # Doesn't return None so page is not updated


def enter_test():
    wp = jp.WebPage()
    jp.Input(classes='m-2 '+ jp.Styles.input_classes, placeholder='Type here',a=wp, keydown=key_down)
    return wp


jp.justpy(enter_test)
```
