### ISSUE TITLE
AssertionError: Web page is empty, add components

### ISSUE THREAD

**Issue by giodegas** [elimintz/justpy#157]
I got same error as in #57 , probably due to data retrieving function that takes too long.

    assert len(load_page) > 0 or load_page.html, '\u001b[47;1m\033[93mWeb page is empty, add components\033[0m'
    AssertionError: Web page is empty, add components

Since error messages are only from internal functions of the justpy package, I cannot debug my own code to determine the cause of the problem.
Maybe there should a DEBUG mode in which the last name space context of the user application is saved before leaving control to justpy.

**Comment by elimintz** [comment]
This error only happens if the page returned by the request handler is empty. This happens to me when for example I have an outer div that contains all other components and I forget to add it to the page.
