### ISSUE TITLE
deployment with local assets

### ISSUE THREAD

**Issue by infintropy** [elimintz/justpy#16]
Is this feature on the roadmap? To be able to have localized css/js/etc resources for implementations on internet-restricted company environments.

If not, I'm happy to pull request:
- Flag on the page class itself that specifies if local/cdn is desired.
- Separate base html template to identify local assets

**Comment by elimintz** [comment]
Currently you have on of the following option:

1) You can set the template file of the page: https://justpy.io/#/reference/webpage?id=template_file

2) You can change the templates directory. This is undocumented. The configuration line in the code is `TEMPLATES_DIRECTORY = config('TEMPLATES_DIRECTORY', cast=str, default=current_dir + '/templates')`

Do you think this would cover what you suggest or do you have more in mind?

**Comment by infintropy** [comment]
Yes, seems good. I'll reopen if not

**Comment by infintropy** [comment]
Great framework btw!
