### ISSUE TITLE
consider genshi.builder-like element nesting syntax

### ISSUE THREAD

**Issue by eudoxos** [elimintz/justpy#168]
JustPy is currently using a bit cumbersome `wp=jp.WebPage(); jp.Label(a=wp,...), jp.XYZ(a=wp...)` syntax. [genshi.builder](https://genshi.readthedocs.io/en/latest/api/builder/) expresses nesting conveniently as `*args` which can be passed to every element and defines its children. The way, one could write
```
wp=WebPage(
   jp.Label(...),
   jp.XYZ(...),
   jp.P('some text',jp.B('this is bold'),'continues here),
)
```
which is both simpler to write (no repeated `a=wp`) and makes the structure immediately visible, especially when nesting.

**Comment by elimintz** [comment]
The format JustPy currently supports for this: https://justpy.io/reference/htmlcomponent/#children
Does this help?

**Comment by eudoxos** [comment]
Thank you, it helps. I only saw the `a=wp` in the tutorial and thought that we as good as it get; named argument is not as elegant as having `*children` arg in each ctor, but definitely better than `a=wp` everwhere.

`WebPage` could also take `children` (or `*children`) for inuitivness, though one extra `Div` is doable :).

Feel free to close the issue if adding `*children` is deemed a wontfix.
