### ISSUE TITLE
jp.redirect() doesn´t redirect

### ISSUE THREAD

**Issue by swevm** [elimintz/justpy#174]
I´m building a simple Dashboard and am struggling with getting jp.redirect() work.

I this BaseLoginForm component which build a login form, handles click event but depend on having a class that inherit this base component that implement do_auth_work() to hide form implementation details. All is working but jp.redirect, nor msg.redirect work. Nothing happens.

Any idea what might be wrong?

btw. Sorry for the code formatting. No matter what I tried adding code the proper way its formatting got screwed up.

from main app.py
async def login_route(request):
    wp = jp.QuasarPage()
    layout = jp.QLayout(a=wp, view='hHh lpR fFf')
    header = jp.QHeader(a=layout, elevated=True, classes='bg-primary text-white')
    toolbar = jp.QToolbar(a=header)
    page_container = jp.QPageContainer(a=layout)
    loginform = LoginForm(a=page_container, s_id=request.session_id, successful_redirect='/dashboard')

baseloginform.py:
class BaseLoginForm(jp.QPage):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.s_id = None
        self.successful_redirect = None
        if 's_id' in kwargs.keys():
            self.s_id = kwargs['s_id']
        if 'successful_redirect' in kwargs.keys():
            self.successful_redirect = kwargs['successful_redirect']
        root = self
        root.classes = 'window-height window-width row justify-center items-center'
        c2 = jp.Div(classes='column q-pa-lg', a=root)
        c3 = jp.Div(classes='row', a=c2)
        c4 = jp.QCard(square=True, classes='shadow-24', style='width:300px;height:485px;', a=c3)
        c5 = jp.QCardSection(classes='bg-primary text-white', a=c4)
        c6 = jp.H4(classes='text-h5 text-white q-my-md', a=c5, text='My Webapp')
        c7 = jp.Div(classes='absolute-bottom-right q-pr-md', style='transform: translateY(50%);', a=c5)
        c8 = jp.QBtn(fab=True, icon='add', color='grey-6', a=c7, )
        c8a = jp.QTooltip(a=c8, text='Sign up as new user')
        c9 = jp.QCardSection(a=c4)
        c10 = jp.QForm(classes='q-px-sm q-pt-xl', a=c9)
        c11 = jp.QInput(square=True, clearable=True, v_model='email', type='email', label='Email', a=c10, name='userid')
        c12 = jp.QInput(square=True, clearable=True, v_model='password', type='password', label='Password', a=c10, name='password')
        c13 = jp.QCardSection(a=c4)
        c13a = jp.QCardSection(a=c10)
        c14 = jp.Div(classes='text-center q-pa-md q-gutter-md', a=c13)
        c15 = jp.QBtn(round=True, color='indigo-7', a=c14)
        c15a = jp.QTooltip(a=c15, text='Login with Facebook')
        c16 = jp.QIcon(name='fab fa-facebook-f', size='1.2rem', a=c15)
        c17 = jp.QBtn(round=True, color='black', a=c14)
        c17a = jp.QTooltip(a=c17, text='Login with Github')
        c18 = jp.QIcon(name='fab fa-github', size='1.8rem', a=c17)
        c19 = jp.QBtn(round=True, color='light-blue-5', a=c14)
        c15a = jp.QTooltip(a=c19, text='Login with Twitter')
        c20 = jp.QIcon(name='fab fa-twitter', size='1.2rem', a=c19)
        c21 = jp.QCardActions(classes='q-px-lg', a=c4)
        c22 = jp.QBtn(unelevated=True, size='lg', color='light-green-7', classes='full-width text-white',
                      type='submit', label='Login', a=c13a)
        c23 = jp.QCardSection(classes='text-center q-pa-sm', a=c4)
        c24 = jp.P(classes='text-grey-6', a=c23, text='Forgot your password?')
        c10.on('submit', self.submit_baselogin_form)

    async def submit_baselogin_form(self, msg):
        luserid = None
        lpassword = None
        for item in msg.form_data:
            if item['html_tag'] == 'input' and item['name'] == 'userid':
                luserid = item["value"]
            if item['html_tag'] == 'input' and item['name'] == 'password':
                lpassword = item["value"]
        if luserid and lpassword:  # If any of these params are empty, raise an error in the form - TODO
            result = await self.do_auth_work(self.s_id, self.successful_redirect, luserid, lpassword)
            if result:
                print(f'Authenticated, redirecting to, {self.successful_redirect}') #redirect variable populated correctly
                #msg.redirect = self.successful_redirect # Doesn´t work
                jp.redirect(self.successful_redirect) # Doesn´t work

    @abstractmethod
    async def do_auth_work(self, s_id, redirect_to, userid, password):
        pass

**Comment by knoxvilledatabase** [comment]
@swevm, I had problems with this too. 

What you do is put three tildes with #python, press enter twice then three more tildes. 

It looks like this, but with tildes instead of single quotes:

''' python
if true:
    return True
'''

See:

``` python
if true:
    return True

```

**Comment by swevm** [comment]
Thankyou @knoxvilledatabase 

Much more readable code below.

~~~ python


async def login_route(request):
    wp = jp.QuasarPage()
    layout = jp.QLayout(a=wp, view='hHh lpR fFf')
    header = jp.QHeader(a=layout, elevated=True, classes='bg-primary text-white')
    toolbar = jp.QToolbar(a=header)
    page_container = jp.QPageContainer(a=layout)
    loginform = LoginForm(a=page_container, s_id=request.session_id, successful_redirect='/dashboard') # LoginForm inherits from BaseLoginForm and implement do_auth_work()


class BaseLoginForm(jp.QPage):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.s_id = None
        self.successful_redirect = None
        if 's_id' in kwargs.keys():
            self.s_id = kwargs['s_id']
        if 'successful_redirect' in kwargs.keys():
            self.successful_redirect = kwargs['successful_redirect']
        root = self
        root.classes = 'window-height window-width row justify-center items-center'
        c2 = jp.Div(classes='column q-pa-lg', a=root)
        c3 = jp.Div(classes='row', a=c2)
        c4 = jp.QCard(square=True, classes='shadow-24', style='width:300px;height:485px;', a=c3)
        c5 = jp.QCardSection(classes='bg-primary text-white', a=c4)
        c6 = jp.H4(classes='text-h5 text-white q-my-md', a=c5, text='My Webapp')
        c7 = jp.Div(classes='absolute-bottom-right q-pr-md', style='transform: translateY(50%);', a=c5)
        c8 = jp.QBtn(fab=True, icon='add', color='grey-6', a=c7, )
        c8a = jp.QTooltip(a=c8, text='Sign up as new user')
        c9 = jp.QCardSection(a=c4)
        c10 = jp.QForm(classes='q-px-sm q-pt-xl', a=c9)
        c11 = jp.QInput(square=True, clearable=True, v_model='email', type='email', label='Email', a=c10, name='userid')
        c12 = jp.QInput(square=True, clearable=True, v_model='password', type='password', label='Password', a=c10, name='password')
        c13 = jp.QCardSection(a=c4)
        c13a = jp.QCardSection(a=c10)
        c14 = jp.Div(classes='text-center q-pa-md q-gutter-md', a=c13)
        c15 = jp.QBtn(round=True, color='indigo-7', a=c14)
        c15a = jp.QTooltip(a=c15, text='Login with Facebook')
        c16 = jp.QIcon(name='fab fa-facebook-f', size='1.2rem', a=c15)
        c17 = jp.QBtn(round=True, color='black', a=c14)
        c17a = jp.QTooltip(a=c17, text='Login with Github')
        c18 = jp.QIcon(name='fab fa-github', size='1.8rem', a=c17)
        c19 = jp.QBtn(round=True, color='light-blue-5', a=c14)
        c15a = jp.QTooltip(a=c19, text='Login with Twitter')
        c20 = jp.QIcon(name='fab fa-twitter', size='1.2rem', a=c19)
        c21 = jp.QCardActions(classes='q-px-lg', a=c4)
        c22 = jp.QBtn(unelevated=True, size='lg', color='light-green-7', classes='full-width text-white',
                      type='submit', label='Login', a=c13a)
        c23 = jp.QCardSection(classes='text-center q-pa-sm', a=c4)
        c24 = jp.P(classes='text-grey-6', a=c23, text='Forgot your password?')
        c10.on('submit', self.submit_baselogin_form)

    async def submit_baselogin_form(self, msg):
        luserid = None
        lpassword = None
        for item in msg.form_data:
            if item['html_tag'] == 'input' and item['name'] == 'userid':
                luserid = item["value"]
            if item['html_tag'] == 'input' and item['name'] == 'password':
                lpassword = item["value"]
        if luserid and lpassword:  # If any of these params are empty, raise an error in the form - TODO
            result = await self.do_auth_work(self.s_id, self.successful_redirect, luserid, lpassword)
            if result:
                print(f'Authenticated, redirecting to, {self.successful_redirect}') #redirect variable populated correctly
                #msg.redirect = self.successful_redirect # Doesn´t work
                jp.redirect(self.successful_redirect) # Doesn´t work

    @abstractmethod
    async def do_auth_work(self, s_id, redirect_to, userid, password):
        pass
~~~

**Comment by knoxvilledatabase** [comment]
@swevm, here is how I accomplish this:

``` python
class DefaultLogin(jp.WebPage):
    load_spinner = None
    bad_credentials = None

    def __init__(self, **kwargs):
        self.session_id = kwargs['session_id']
        self.login_header_background_color = kwargs['login_header_background_color']
        self.logo_img_src = kwargs['logo_img_src']
        self.bad_credentials_message = kwargs['bad_credentials_message']
        self.screen_background_color = kwargs['screen_background_color']
        self.login_panel_center_styling = kwargs['login_panel_center_styling']
        self.logo_styling = kwargs.get('logo_styling', '')
        self.logo_style = kwargs.get('logo_style', '')
        self.spinner_icon = kwargs['spinner_icon']
        self.spinner_size = kwargs['spinner_size']
        self.spinner_color = kwargs['spinner_color']
        self.spinner_placement_style = kwargs['spinner_placement_style']
        super().__init__(**kwargs)
        self.template_file = 'quasar.html'
        # print('loading login')
        self.page_content()

    def page_content(self):
        root = jp.Div(a=self)
        page = jp.QDiv(a=root, classes=self.screen_background_color, style='height:100vh')
        content = jp.Div(a=page, classes='container mx-auto h-auto flex justify-center items-center')
        center = jp.Div(a=content, classes=self.login_panel_center_styling)

        header = jp.QDiv(
            a=center,
            classes=self.login_header_background_color,
            style='padding:10px;border-top-right-radius: 3px;border-top-left-radius: 3px;'
        )

        self.bad_credentials = jp.Div(
            show=False,
            classes='border border-red-400 rounded bg-red-100 px-4 py-3 text-red-700 m-5',
            text=self.bad_credentials_message,
            a=center
        )

        jp.Img(src=self.logo_img_src, a=header, classes=self.logo_styling, style=self.logo_style)

        form_center = jp.Div(a=center, classes='content-center mt-5 mb-10 ml-10')
        form = jp.Form(
            a=form_center,
            classes='m-1 p-1 w-3/4',
            data={'username': '', 'password': '', 'session_id': self.session_id}
        )

        self.load_spinner = jp.QInnerLoading(showing=False, a=form, style=self.spinner_placement_style)
        jp.QSpinner(
            spinner_type=self.spinner_icon,
            size=self.spinner_size,
            a=self.load_spinner,
            color=self.spinner_color,
        )

        QInputSubmitOnBlur(
            label='Username',
            a=form,
            #hint='*Required' ,
            form=form,
            type='text',
            attname='username',
            input_fn=None,
            style='',
        )

        jp.QInput(
            filled=True,
            label='Password',
            a=form,
            type='password',
            model=[form, 'password'],
            debounce=432,
        )

        jp.Input(value='Submit', type='submit', a=form, classes=button_classes)
        form.on('submit', self.submit_login)

        div = jp.QDiv(a=form_center, style='font-size:9pt;color:#888;margin-left:5px;margin-top:15px')
        div_inner = jp.QDiv(a=div, style='padding: 10px;width: 210px;background-color: #f9f9f9;border-radius: 3px;')
        span1 = jp.Span(a=div_inner, style='padding-right:3px')
        jp.Span(a=div_inner, text='Compatible with Google Chrome')
        jp.QIcon(name='ion-logo-chrome', a=span1)


    @staticmethod
    async def authenticate_user(msg, username, password, session_id):
        if username and password:
                msg.page.redirect = '/'
            else:
                msg.page.bad_credentials.show = True
                msg.page.load_spinner.showing = False
        else:
            msg.page.bad_credentials.show = True
            msg.page.load_spinner.showing = False

    async def submit_login(self, msg):
        await asyncio.sleep(1)
        msg.page.load_spinner.showing = True
        await msg.page.update()
        username = msg.form_data[0]['value']
        password = msg.form_data[1]['value']
        session_id = msg.session_id
        await self.authenticate_user(msg, username.lower(), password, session_id)
```

```python
def login(request):
    return DefaultLogin(
        title='Whatever',
        favicon='/images/favicon.ico',
        display_url='/login',
        logo_img_src='/static/images/logo.png',
        session_id=request.session_id,
        bad_credentials_message='Bad username or password',
        screen_background_color='bg-grey-3',
        login_header_background_color='bg-light-blue-6',
        login_panel_center_styling='w-1/4 sm:w-full xl:w-1/4 mt-20 bg-white',
        logo_style='width:105px',
        spinner_icon='oval',
        spinner_size='50px',
        spinner_color='primary',
        spinner_placement_style='top:-250px',
    )


@jp.SetRoute('/')
async def layout(request):
...
jp.justpy(layout)
```

I hope this helps!

**Comment by elimintz** [comment]
@swevm Could you please check if the following works:
Change
```python
#msg.redirect = self.successful_redirect # Doesn´t work
```
to
```python
msg.page.redirect = self.successful_redirect 
```
and comment out or remove the line after it.

Let me know if this does not work.

**Comment by swevm** [comment]
Thank you @knoxvilledatabase for giving me ideas on how to better structure my code in JustPy.

@elimintz It worked. Thanks
