### ISSUE TITLE
Make `HTMLComponent.classes` a set of strings

### ISSUE THREAD

**Issue by AgarwalPragy** [elimintz/justpy#18]
At present, the classes property is a space-separated list of strings, just like it is in HTML. This makes adding and removing classes cumbersome.

If the classes is a `Set[str]`, one can use the `set.add()` and `set.remove()` methods for the job. Finally, when the classes need to be applied to the elements, JustPy could simply do `' '.join(classes)`

**Comment by elimintz** [comment]
What you say is true and it was an option I considered. The trade off is that providing classes as sets differs from the way people are used to currently and would be less intuitive. Perhaps as a compromise, it would make sense to let users specify strings and convert them internally to sets.
