### ISSUE TITLE
favicon GET for each page update (not all setups?)

### ISSUE THREAD

**Issue by eudoxos** [elimintz/justpy#183]
I am running this simple (persistent) page with periodic updater.

```python
import zipfile, io, sys, asyncio
import justpy as jp

class MainPage(jp.QuasarPage):
    def __init__(self):
        super().__init__(delete_flag=False,title='Favicon test',favicon='fav.png')
        self.label=jp.Label(text='Counter: 0',a=self)
        jp.run_task(self.update_forever())
    async def update_forever(self):
        i=0
        while True:
            i+=1
            await asyncio.sleep(.5)
            self.label.text='Counter: %d'%i
            await self.update()

mainPage=None

@jp.SetRoute('/')
def main_page():
    global mainPage
    if mainPage is None: mainPage=MainPage()
    return mainPage

jp.justpy()
```

When I open network inspector in Firefox (with clean profile, no extensions), I see the favicon being re-downloaded at every refresh (with cache hit):

![image](https://user-images.githubusercontent.com/1029876/100979019-81b2ed00-3543-11eb-91b2-2218ce85ea02.png)

When I run in LAN or at localhost, I don't see this happening.

Is there some explanation for this? Is it normal? Perhaps the icon should be served with some TTL to avoid repeated requests?

The icon is here:![fav](https://user-images.githubusercontent.com/1029876/100979223-c9d20f80-3543-11eb-8ef9-a5798d388ed9.png)

**Comment by elimintz** [comment]
Do you get the same behavior with Chrome?

**Comment by eudoxos** [comment]
I can confirm Chromium fetches the favicon only once.

**Comment by eudoxos** [comment]
This is a [research article on browser tracking via favicon cache](https://www.cs.uic.edu/~polakis/papers/solomos-ndss21.pdf) which specifically mentions that, as a bug, Firefox never actually fetches favicons from the cache:

![image](https://user-images.githubusercontent.com/1029876/108536485-ccd7d300-72dc-11eb-8325-34409282d54b.png)

[This is the bug in Firefox's bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1618257).

I am closing the issue here.

**Comment by elimintz** [comment]
Thank you.
