### ISSUE TITLE
Event Handlers don't work with bound methods

### ISSUE THREAD

**Issue by AgarwalPragy** [elimintz/justpy#19]
JustPy allows you to write custom components as classes.
However, the way it implements event handlers doesn't work with OOP style.

```python
from justpy import Div, WebPage
import justpy


class CustomDiv(Div):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.style = "width: 100px; height: 100px; background: black;"
        self.on('click', self.clicked)

    def clicked(self, event):
        print(event)


def main():
    page = WebPage()
    page.add(CustomDiv())
    return page


if __name__ == '__main__':
    justpy.justpy(main)
```

Clicking the div gives the following error: `INFO:     Event result: Attempting to run event handler:clicked() takes 2 positional arguments but 3 were given`

This is because the `self` attribute of the method `clicked` is already bound to the class instance. Justpy tries to supply the value for the `self` argument as well, which is not needed if you use a OOP style.

**Comment by elimintz** [comment]
In custom elements, you need to define the event handlers inside the class as static methods. The following will work:

```
from justpy import Div, WebPage
import justpy


class CustomDiv(Div):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.style = "width: 100px; height: 100px; background: black;"
        self.on('click', self.clicked)

    @staticmethod
    def clicked(self, event):
        print(event)


def main():
    page = WebPage()
    page.add(CustomDiv())
    return page

justpy.justpy(main)
```

**Comment by jandeneweth** [comment]
Since this also confused me at first, I'd like to suggest that `self` is not the recommended name for the first argument. Even on staticmethods, it implies that self is an instance of the class in which it's defined. 

I'm not sure about alternative names though, 'component' is too long and 'comp' or 'cmp' are often shorthand for 'comparison'. 'item', 'widget' or 'elem' (for element) seem somewhat off.
