### ISSUE TITLE
how to use python vscode debugger

### ISSUE THREAD

**Issue by pabloazurduy** [elimintz/justpy#199]
Hi, first of all, thanks for the library! it is an awesome fast prototyping app tool, very flexible, and with a lot of out-of-the-box components that make it super easy to build something fast.  

In short: I'm currently running the app with the `uvicorn --reload mymodule:app` command in my console (so it can auto-reload on every file change). Is there a way to use the python debugger (in vscode)? is really hard to debug using `print(my_variable)` statements. Thanks!

(a side comment): The documentation is not very clear about some of the architecture on new components, the event_handeler functions, the inheritance, and the way that the documentation is written it's not very clear about what (for example) `self` correspond (in a `@staticmethod`), sometimes is hard to understand who is calling who and what are the arguments. (is there an intensive use of `*args`, and `**kwargs` that makes the understanding of the code hard).

**Comment by elimintz** [comment]
I work with Pycharm so don't have much experience with vscode. I would recommend setting the CRASH = True in justpy.env. The program then halts if there is an error in an event handler. For me it makes debugging easier.

If you have some specific code you are not clear about, I would be happy to explain it. Inside a component self corresponds to the component and the element that the event occurred on is event.target.

**Comment by pabloazurduy** [comment]
Hi @elimintz Thanks for your fast response!, cool, I will try with `CRASH = True`. is there a way to insert breakpoints? using pycharm maybe?. what I want to understand is what are the arguments that are being communicated between components, to do that I would like to make a line break when some code line is executed. Is there a way to do that ?

About the components, Is hard to understand for example 

```
class PillButton(jp.Button):

    def __init__(self, **kwargs): # what are the arguments needed to build this component ? not very readable..
        
        self.some_parameter = val1 # is there a more readable way to initialize on the supper builder parameter?
        super().__init__(**kwargs)  
        self.other_parameter = val2 # this parameter will not be part of the supper build ?, but is part of the instance def
   
   def some_method(self):
         print(self) # what is self here ?
   
   @staticmethod
   def some_other_method(self):
         print(self) # what is self here ?
   
   
pointer = [] # mutable object 
other_component_pointer = jp.Div(a.wp)
pill_instance = PillButton(some_no_explicit_parameter = pointer, # this arg will be passed to the supper builder ?
                                           some_other_no_explicit_parameter = other_component_pointer, # this pointer could modify the other component ?
                                            a = wp)

other_component_pointer.pill_instance_pointer = pill_instance # if I add this therefore pill can modify other_component and the other way around?

```

**Comment by pabloazurduy** [comment]
To anyone that might be interested in using the vscode debugger, just add this configuration to `launch.json` `"configurations"`
```
{ "name": "Python: justpy",
      "type": "python",
      "request": "launch",
      "module": "uvicorn",
      "args": ["run:app","--reload"]
},
```
[reference](https://stackoverflow.com/a/61000306/5318634)
