### ISSUE TITLE
Leading whitespace not rendered

### ISSUE THREAD

**Issue by tyoung-JHUAPL** [elimintz/justpy#2]
With a slight tweak to the tutorial, I'm noticing it's not rendering the leading-whitepace on many of the lines in my browser.

Example code:

import justpy as jp
string = [
'JustPy',
'',
'    What is JustPy?',
'        Introduction',
'        Hello World!',
'        Under the Hood',
'        News and Updates',
'        License',
'    Tutorial',
'        Getting Started',
'        Basic Concepts',
'        Handling Events',
'        HTML Components',
]
def my_click(self, msg):
    self.text = 'I was clicked!'

def hello_world():
    wp = jp.WebPage()
    for sub_str in string:
        print(sub_str)
        d = jp.Div(text=sub_str)
        d.on('click', my_click)
        wp.add(d)
    return wp

jp.justpy(hello_world)

I comes out as:
JustPy
I was clicked!
Introduction
I was clicked!
Under the Hood
News and Updates
License
Tutorial
Getting Started
Basic Concepts
Handling Events
HTML Components

**Comment by elimintz** [comment]
I am not sure I understand the problem. Which white space is ignored?

**Comment by tyoung-JHUAPL** [comment]
Sorry, now github stripped the leading whitespace from the code or there is some special whitespace character going on. 

Attaching the source:
[test_justpy.py.txt](https://github.com/elimintz/justpy/files/4183178/test_justpy.py.txt)

**Comment by tyoung-JHUAPL** [comment]
```
> import justpy as jp

string = [
'JustPy',
'',
'    What is JustPy?',
'        Introduction',
'        Hello World!',
'        Under the Hood',
'        News and Updates',
'        License',
'    Tutorial',
'        Getting Started',
'        Basic Concepts',
'        Handling Events',
'        HTML Components',
]
def my_click(self, msg):
    self.text = 'I was clicked!'

def hello_world():
    wp = jp.WebPage()
    for sub_str in string:
        print(sub_str)
        d = jp.Div(text=sub_str)
        d.on('click', my_click)
        wp.add(d)
    return wp

jp.justpy(hello_world)

```

**Comment by tyoung-JHUAPL** [comment]
i.e. line 6 should have a string with a bunch of leading spaces. Is strip() called somewhere?

**Comment by elimintz** [comment]
If you want the leading spaces use Pre instead of Div:
`d = jp.Pre(text=sub_str)`
