### ISSUE TITLE
Feature Request: Support for handling keypress event on body.

### ISSUE THREAD

**Issue by AgarwalPragy** [elimintz/justpy#20]
Currently, to be able to handle a keypress event on the entire page, we need to have an input element somewhere. Normally, in the absence of any input element, the keypress event gets triggered on `document.body`

Currently, JustPy provides no way of adding event handlers on the document body.

**Comment by elimintz** [comment]
Yes, that makes sense. I will add this feature.

**Comment by AgarwalPragy** [comment]
> Yes, that makes sense. I will add this feature.
> 
> In the meantime, a possible workaround is to put all your elements in one div and capture the keypress event on the div.

Well, divs can't capture focus, so they can't register keypress unless explicitly targetted. ;)
