### ISSUE TITLE
super() builder inconsistent when attributes are defined inside the init 

### ISSUE THREAD

**Issue by pabloazurduy** [elimintz/justpy#201]
Hi, 
I’m struggling a little bit with this code: 

```python
import justpy as jp

class UpperMenu(jp.QDiv):
    def __init__(self,  **kwargs):
        #self.classes = ['grid','grid-cols-7','gap-4'] # this doesn't work
        super().__init__(**kwargs)
       #self.classes = ['grid','grid-cols-7','gap-4'] # this works
        root = self
        country_selector = jp.QSelect(outlined=True, classes='col-span-1', label="Outlined", a = root)
        country_selector2 = jp.QSelect(outlined=True, classes='col-span-2', label="Outlined1", a = root)



def page():
    wp = jp.QuasarPage(tailwind = True)
    menu = UpperMenu(a = wp,
                   #classes = ['grid','grid-cols-7','gap-4' ] #This works 
                    )
    return wp 

app = jp.app
jp.justpy(page, start_server=False)

```

somehow the `classes` argument works when is declared outside the class definition, but when declaring `self.classes = [`something`]` it does not render as it is supposed to. I had a similar problem with `class MyPage(jp.QuasarPage)` and defining `self.tailwind =True`. I'm following [this example](https://justpy.io/tutorial/custom_components/#pill-button-component).

BTW calling ` super().__init__(classes = ['grid','grid-cols-7','gap-4'], **kwargs)` also works

**Comment by elimintz** [comment]
Please try moving the classes assignments after the super().__init__ statement in __init__ and let me know if it works.

**Comment by pabloazurduy** [comment]
yes! that works too

```
class UpperMenu(jp.QDiv):
    def __init__(self,  **kwargs):
        super().__init__(**kwargs)
        self.classes  = ['grid','grid-cols-7','gap-4','m-8']
```
what would be the clearest (and consistent) way to implement this?

**Comment by elimintz** [comment]
Just as you did above.

**Comment by pabloazurduy** [comment]
Many thanks @elimintz !! I would use that then
