### ISSUE TITLE
User Group or Forum? 

### ISSUE THREAD

**Issue by cheak1974** [elimintz/justpy#209]
Hi,
I am actually playing around with justPy and love the way it works. But I was wondering that there is no google goup, Forum, Gitter, Discord or whatsever channel/place for users to help each other. 

Asking recurring questions in github issues might be at a point very exhausting for the maintainer. 

Is there such a place? 

regards
Chris

**Comment by elimintz** [comment]
Hi Chris,

Thank you for using JustPy! GitHub now supports Discussions we is what I think you are looking for. In my user interface they are on the line with Issues to the right of Pull requests.

Eli
