### ISSUE TITLE
Is it possible to insert <script> elements into body?

### ISSUE THREAD

**Issue by oleg-sh** [elimintz/justpy#21]
E. g. if I want to insert Google Adsense or Analytics — can I do it somehow?
I've tried using inner_html for that but with no luck, it breaks the whole page.

**Comment by elimintz** [comment]
Yes, this feature will be available in version 0.0.7 coming out this Monday.
This should work after the new version is uploaded:
```
import justpy as jp

def test_head(): 
    wp = jp.WebPage() 
    wp.head_html = '<script>console.log("Hello there");</script>' 
    jp.Div(text='Testing...', a=wp) return wp

jp.justpy(test_head)
```

Anything in the head_html attribute, the framework will put in the head.

**Comment by oleg-sh** [comment]
No way to put it in the body though?

**Comment by elimintz** [comment]
It would be simple to add a `body_html` attribute also. But is it really needed?

**Comment by oleg-sh** [comment]
I'm not sure. Some external services seem to require to insert js in the body, like Adsense.
Thank you for your hard work. This framework is incredible!

**Comment by elimintz** [comment]
Thank you!

Ok, will add body_html attribute
