### ISSUE TITLE
Own error pages

### ISSUE THREAD

**Issue by cheak1974** [elimintz/justpy#213]
Hi, it's me again.

Is there a way to show custom error pages? 
I fell over the case that I had a typo in the url and justPy reported, that it couldn't find the page.

I don't want people to see which framework I am using. Is there a way to tell justPy to use a string with custom html or a component for occuring errors? I don't even know how much error pages are existing, but It would be nice to have the possibility to modify them. 

regards
Chris

**Comment by elimintz** [comment]
Hi,

The simplest way to do this is to use the default page as the error page. Provide a path for all other pages, and if there is no hit to any path, the error page will be served. For example:

```python
import justpy as jp

@jp.SetRoute('/')
def other_page():
    wp = jp.WebPage()
    jp.Div(text='Good page', classes='text-xl text-green-500 m-4', a=wp)
    return wp

def error_page():
    wp = jp.WebPage()
    jp.Div(text='You have an error', classes='text-xl text-red-500 m-4', a=wp)
    return wp

jp.justpy(error_page)
```

**Comment by cheak1974** [comment]
Thanks. That's great.
