### ISSUE TITLE
Assertion Error on Simple Refresh

### ISSUE THREAD

**Issue by adam820** [elimintz/justpy#214]
Hello! Trying out justpy for a small project, and it seems to throw an assertion error on basic refresh. The first time the file is run, it loads fine, but if you do nothing and simply refresh it throws an assertion error that there are no elements on the page, which is not true.

Here is my minimal example:
```
import justpy as jp

wp = jp.WebPage()
div = jp.Div()
wp.add_component(div)

def main_page(request):
    return wp

jp.justpy(main_page)
```
I also tried:

```
import justpy as jp

wp = jp.WebPage()
div = jp.Div(a=wp)

def main_page(request):
    return wp

jp.justpy(main_page)
```
Running this starts up fine, I can browse to 127.0.0.0:8000; if I then hit refresh, it throws `AssertionError: [47;1m[93mWeb page is empty, add components[0m`

Am I missing something, or is this a bug? Thanks!

_

> OS: Linux, Fedora 33
> Browser: Firefox 85
> IDE: PyCharm (though it also fails through basic command-line)

_

**Comment by elimintz** [comment]
The default is for JustPy to delete a WebPage instance when the page is closed. If you would like to create the page once, set the delete_flag to False as in this example: https://justpy.io/tutorial/basic_concepts/#creating-web-pages-once

Or in your case:

```python
import justpy as jp

wp = jp.WebPage(delete_flag=False)
div = jp.Div()
wp.add_component(div)

def main_page(request):
    return wp

jp.justpy(main_page)
```

**Comment by adam820** [comment]
Okay, re-reading that section, I see what you're saying. Is the reasoning behind this being the default is that the page is supposed to be rendered once, with new data/updates being fetched/pushed via WebSockets or AJAX? If so, that might be a detail to be added to the docs to make the reasoning clearer; my assumption was that, while sub-optimal, a refresh of the page would completely re-build the webpage object and serve that again, instead of re-using the existing object.

Thanks!

**Comment by elimintz** [comment]
If you want the refresh to re-build the page, create the WebPage instance in the request handler which is usually the case and therefore the default is that the instance is deleted when the user closes or refreshes the browser window so as to make sure memory usage is under control.
