### ISSUE TITLE
Framework can't process frontend events in an asynchronous way

### ISSUE THREAD

**Issue by FI-Mihej** [elimintz/justpy#22]
Hello,

**Steps to reproduce:**
1) Create page with several buttons
2) Each button should have it's own async on_click handler. For example:
`
    async def on_click(item, msg):
        print(f'Step 0: {perf_counter()} - {item}')
        item.text = 'Waiting...'
        print(f'Step 1: {perf_counter()} - {item}')
        await msg.page.update()
        print(f'Step 2: {perf_counter()} - {item}')
        await jp.asyncio.sleep(5)
        print(f'Step 3: {perf_counter()} - {item}')
        item.text =  'Done'
        print(f'Step 4: {perf_counter()} - {item}')
        await msg.page.update()
        print(f'Step 5: {perf_counter()} - {item}')
`
3) Start server
4) Try to click on each button on a page without a delay

**Expected behavior:**
1) Each clicked button should get a "Waiting..." text immediately after a click. Server log should have several 0 - 2 Steps logs from an each of the clkicked buttons.
2) Approximately after 5 seconds, an each clicked button will get a "Done" text. Server log should have several 3 - 5 Steps logs from an each of the clkicked buttons.

**Actual behavior:**
1) Only the **first** clicked button is getting "Waiting..." text. Server log has 0 - 2 Steps logs from only the first clicked button.
2) After 5 seconds, only the **first** clicked button is getting "Done" text. Server log has 3 - 5 Steps logs from only the first clicked button.
3) Only the **second** clicked button is getting "Waiting..." text. Server log has additional 0 - 2 Steps logs: from only the second clicked button.
4) After 5 seconds, only the **second** clicked button is getting "Done" text. Server log has additional 3 - 5 Steps logs: from only the secondclicked button.
5) ... third clicked button ...
... and so on.

**Comment by elimintz** [comment]
Thanks for catching this. The blocking it turns out is on the backend, the websocket class was handling events using await instead of creating a task to handle the event. I fixed this and it will be available in version 0.0.8 which will come out Monday.

The reference test for this is:
```
import justpy as jp
import asyncio

async def my_click(self, msg):
    print(f'in event {self.text}')
    self.disabled = True
    for i in range(1,21):
        self.text = f'Step {i}'
        await msg.page.update()
        await asyncio.sleep(1)
    self.text = 'Done'
    self.disabled = False


async def btn_test():
    wp = jp.WebPage()
    for i in range(10):
        jp.Button(text=f'{i}', a=wp, classes=jp.Styles.button_simple + ' m-2', click=my_click)
    return wp

jp.justpy(btn_test)
```

**Comment by Lefort-Antoine** [comment]
Hy,

I'm trying a similar code. 
My aims is to run a function on the back and show logs in front waiting the end of the first on. I've tried many ways without success (multiprocessing, jp.run_task, .... ) . Could you help me ?

Here is one of my try with the "asynchronous way" explained in this discussion: 


```
import time
import justpy as jp
import io
import asyncio
import logging 


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger('basic_logger')
logger.setLevel(logging.DEBUG)
log_capture_string = io.StringIO()
ch = logging.StreamHandler(log_capture_string)
ch.setLevel(logging.DEBUG)
formatter = logging.Formatter('| %(name)s - %(levelname)s - %(message)s')

ch.setFormatter(formatter)

logger.addHandler(ch)


def my_click(self, msg):
    print(f'in event {self.text}')
    self.disabled = True
    for i in range(1,21):
        self.text = f'Step {i}'
        logger.info(f'Step {i}')
        time.sleep(2)
    self.text = 'Done'
    self.disabled = False

async def my_log(self, msg):
    while self.btncalcul.disabled:
        txt = log_capture_string.getvalue().replace("| ", "\n")
        self.logdiv.text = txt
        await asyncio.sleep(2)

async def btn_test():
    wp = jp.WebPage()
    btncalcul = jp.Button(text='calcul', a=wp, classes=jp.Styles.button_simple + ' m-2', click=my_click)
    btnlog = jp.Button(text='log', a=wp, classes=jp.Styles.button_simple + ' m-2', click=my_log)

    logdiv = jp.Div(a=wp, style="white-space: pre-line")
    btnlog.logdiv = logdiv
    btnlog.btncalcul = btncalcul
    return wp

jp.justpy(btn_test)
```

**Comment by Lefort-Antoine** [comment]
I found a way to solve my problem using threading

```
import threading

import logging

import logging 
import io
logger = logging.getLogger('LOGTITLE')
logger.setLevel(logging.DEBUG)
log_capture_string = io.StringIO()
async def myfcn(self, msg):
      t = threading.Thread(target=MYFONCTION, args= (p1, ))
      t.daemon = True
      t.start()

      while t.is_alive():
          self.textdiv.text = log_capture_string.getvalue()
          await msg.page.update()
          await asyncio.sleep(1)

      t.join()
```
