### ISSUE TITLE
Property setter don't work in QCard descendant

### ISSUE THREAD

**Issue by docm64** [elimintz/justpy#223]
I have created my own component as a descendant of QCard which has a property `interval`. My code looks like this:
```
    class TimePicker(jp.QCard):
    ....
    def get_interval(self):
        return self.__interval
    def set_interval(self, val):
        ....
        self.__interval = val
    interval = property(get_interval, set_interval)
    ....
```
When I create an instance `picker = TimePicker()` and I do an assignment, e.g. `picker.interval=5`, **the setter function is not invoked**. No error raised, nothing. Just the function is not called (and the assignment does not happen).
A direct call to `picker.set_interval(5)` produces the desired result. There is no issue with that function.
 
Just to narrow down the issue, I changed the mother class from `jp.QCard` to `jp.Div`. Surprisingly, then the property setter works as it should. So there seems to be a problem in the implementation of `jp.QCard` with the execution of property setter functions.

**Comment by docm64** [comment]
Performed some deeper analysis and found a bug in quasarcomponents.py 

Inside class jp.QDiv, ancestor of jp.QCard, function `__setattr__` is overridden

```
    def __setattr__(self, key, value):
        if key in self.slots:
            q_slot = key[:key.index('_slot')].replace('_', '-')
            self.add_scoped_slot(q_slot, value)
        else:
            super().__setattr__(key, value)
#            self.__dict__[key] = value
```

The last line (which I commented out)  was the problem. Instead of directly writing `value` into `__dict__`, better call the method of the parent class ` super().__setattr__(key, value)`. I inserted that line.
Now property setters work with Quasar classes.

**Comment by elimintz** [comment]
Thank you very much for catching this. I made the change and it will be in the new version.
