### ISSUE TITLE
QRouteTab support

### ISSUE THREAD

**Issue by infintropy** [elimintz/justpy#23]
This framework has introduced me to quasar. I'm currently building out a dashboard and it seems like the way to make a SPA with this is to have QRouteTabs switch between internal pages. Is there a way to support this currently?

**Comment by elimintz** [comment]
There is no direct support for QRouteTabs.

The way to do this with JustPy is to set the `show` attribute of the appropriate page based on a tab click for example. So if you press tab for page 3 out of 5, it sets the show attribute of page 3 to True and the other pages to false.
