### ISSUE TITLE
404's on Tailwind tutorial page

### ISSUE THREAD

**Issue by garyrob** [elimintz/justpy#232]
On https://justpy.io/tutorial/tailwind/ there are two "notes" ending "The reason for this can be found here," where "here" is a link. Clicking on either leads to 404 errors.

**Comment by elimintz** [comment]
Thanks for flagging this.

**Comment by garyrob** [comment]
Are the proper links https://www.tailwindcss.cn/docs/upgrading-to-v1/#6-explicitly-style-any-headings and https://www.tailwindcss.cn/docs/upgrading-to-v1/#7-explicitly-style-any-lists-that-should-have-bullets-numbers?

**Comment by elimintz** [comment]
Yes, these are the correct links, thank you.
