### ISSUE TITLE
Calling a javascript function from python code?

### ISSUE THREAD

**Issue by AgarwalPragy** [elimintz/justpy#24]
I'm trying to embed the Ace Editor in my application.
https://ace.c9.io/#nav=embedding

with the following script in `head_html`, I just need to call the `create_editor` and `destroy_editor` functions with the appropriate strings.

Is there a way to invoke a JS function from the python backend?

```js
<script src="/static/ace-builds/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    window.all_editors = {};
    function create_editor(element_id) {
        var editor = ace.edit(element_id);
        editor.setTheme("ace/theme/monokai");
        editor.session.setMode("ace/mode/markdown");
        window.all_editors[element_id] = editor;
    }
    function destroy_editor(element_id) {
        window.all_editors[element_id].destroy();
        delete window.all_editors[element_id];
    }
</script>
```

**Comment by elimintz** [comment]
No, there is no way to invoke a JavaScript function from the backend. I'll add that as a feature suggestion.

However, in this case there is a workaround that may partially work (you need version 0.0.7). 
Using `body_html` (https://justpy.io/reference/webpage/#head_html-and-body_html ) insert a div with your unique id (just don't use an integer string) and after it insert also the script tag running the function create_editor on that div.

**Comment by elimintz** [comment]
So this enhancement was very simple to implementand I added it to version 0.0.8 (coming out Monday).

I added a method to the WebPage class called `run_javascript`. It accepts as an argument a string with JS code.

This is the test example:

```
import justpy as jp

async def my_click(self, msg):
    await msg.page.run_javascript("""
    for (var i = 0; i<10; i++) {
        console.log('Line: ' + i);
        }
    """)

def javascript_test():
    wp = jp.WebPage()
    d = jp.Div(a=wp, classes='m-2')
    b = jp.Button(text='Run Script', a=d, classes=jp.Styles.button_simple, click=my_click)
    return wp

jp.justpy(javascript_test)

```

**Comment by AgarwalPragy** [comment]
Thanks for the speedy fix ^_^

**Comment by elimintz** [comment]
Please upgrade to version 0.0.8 and let me know how this works for you.

**Comment by AgarwalPragy** [comment]
> Please upgrade to version 0.0.8 and let me know how this works for you.

Works, but a little difficult to use. If I'm in an event handler, I can get the page instance from the msg.
However, I am really looking for calling the JS code when my component has been rendered (so in the `__init__` function).
For this, I need to explicitly pass the current webpage instance into the `__init__` of every component.

It works, but is not the prettiest of solutions :D

**Comment by elimintz** [comment]
The cleanest way to solve this problem I think is to have WebPage events that can be captured, like `page ready` that will fire once the Websocket connection is in place. Then you could run JavaScript from within event handlers for these events.

**Comment by elimintz** [comment]
If you are building a custom element, then you can use the Vue life cycle hooks such as `mounted`.

**Comment by AgarwalPragy** [comment]
> If you are building a custom element, then you can use the Vue life cycle hooks such as `mounted`.

At present, I've simply added the run_javascript call in the event handler, since I want an Ace editor to be added to the page when a particular button is clicked.

I guess I will have to build a Vue component as well if I wish to do anything more complicated. :)

**Comment by elimintz** [comment]
I'll probably add a page loaded event which will fire when the Websocket connection is established.
