### ISSUE TITLE
page.update() not working when websockets=False

### ISSUE THREAD

**Issue by pabloazurduy** [elimintz/justpy#241]
Hi, I'm using some notifications on a page and it works when I use `websockets=True` but fails when `websockets=False`. So the problem is that I'm mounting the app on `google app engine` so, websockets must be false, otherwise it doesn't work. 

I realized that my buttons `loading` state also have the same problem, I'm thinking that must have to do with the 
`await page.update()` interactions. I'm not a expert on websockets, is there a way to replace that `await page.update()` line when `websockets = False` in order to have notifications and buttons `loading` state ?

```python
import asyncio
import re
from typing import Optional
import justpy as jp

def open_dialog(self, msg):
    self.dialog.value = True

async def email_submit(self, msg):
    email_str = msg.value
    if not re.match(r"^[A-Za-z0-9\.\+_-]+@[A-Za-z0-9\._-]+\.[a-zA-Z]*$", email_str):
        notification = jp.QNotify(message='Error in email', a=msg.page, position='bottom', closeBtn='Close', color ='negative', textColor ='white')
        notification.notify = True
        await msg.page.update()
        notification.notify = False
    else:
        notification = jp.QNotify(message='email correct', a=msg.page, position='bottom', closeBtn='Close')
        notification.notify = True
        await msg.page.update()
        notification.notify = False

    await self.a.a.a.run_method('hide()', msg.websocket) # this closes the dialog

def dialog_test():
    wp = jp.QuasarPage(tailwind=True)
    div = jp.QDiv(classes="q-pa-md q-gutter-sm", a =wp)
    alert_btn = jp.QBtn(label='save email', color='primary', a=div)
    dialog = jp.QDialog(name='alert_dialog', persistent=False, a=div)
    card = jp.QCard(a=dialog, classes=['w-2/6'] )
    card_text = jp.QCardSection(a=card, text='Your Email Address')
        
    email_input = jp.QInputChange(dense=True, v_model="address", autofocus=True, a = card_text)
    
    btn_section = jp.QCardActions(a=card, classes=['flex','justify-between'])
    close_btn = jp.QBtn(flat=True, label='Cancel', color='primary', v_close_popup=True, a = btn_section,)
    send_btn = jp.QBtn(flat=True, label='Send', color='primary', v_close_popup=True, a = btn_section)
    
    alert_btn.dialog = dialog
    alert_btn.on('click', open_dialog)
    send_btn.on('click', email_submit)
    email_input.on('change', email_submit)

    return wp

app = jp.app
jp.justpy(dialog_test , start_server=False, websockets=False) # replace by true and notify work 

```
Thanks

**Comment by elimintz** [comment]
Hi,

Unfortunately, without a websocket connection you cannot push data to the webpage and page.update() does not work. The page is updated only by some user initiated event such as 'click'. Please take a look at: https://justpy.io/tutorial/ajax/#ajax-page-reload
Perhaps it can help solve your specific use case.

**Comment by pabloazurduy** [comment]
HI @elimintz 
Thanks for your fast reply (as always 🙏 ). I finally was able to launch websockets on `appengine` it wasn’t hard. There is another issue here that said that a way to deploy justpy on GAE it's to disable websockets, but [now is possible](https://cloud.google.com/appengine/docs/flexible/python/using-websockets-and-session-affinity) 


In case someone is interested on using appengine with websockets (`yaml` file)

1. Use flex env for app engine 
  ```yaml
  env: flex
  runtime: python
  runtime_config:
    python_version: 3.7
  ```
2. deploy the app using `uvicorn`
`entrypoint: uvicorn <yourmodule>:app --host 0.0.0.0 --port $PORT`

3. use a manual scaling instance and keep `session_affinity:true`

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

network:
  name: my_vpc_network # if blank will point out to 'default' network 
  session_affinity: true

4. in your module keep `websockets=True`
`jp.justpy(dialog_test , start_server=False, websockets=True`
