### ISSUE TITLE
Using Highcharts outside of a justpy web app

### ISSUE THREAD

**Issue by multigoodverse** [elimintz/justpy#243]
Hi, I have a question regarding Highcharts for which I couldn't find an answer in the Highcart section of the justpy docs. 

I am building a justpy web app that will contain highcharts, but before I build the web app, I need to do some analysis on a Jupyter notebook and visualize the data inline in Jupyter. 

Is there a way to display highcarts inline in Jupyter (like we do with matplotlib and plotly)? The [Highcharts section of the guide](https://justpy.io/charts_tutorial/introduction/) gives the impression that it might be possible to use Hicharts without a web app - I am quoting the guide: 

> "The Highcharts and JustPy combination is great for creating and sharing interactive charts, even if you don't plan to develop a web application."

I tried this code:
```
import justpy as jp
import pandas as pd

wm = pd.read_csv('https://elimintz.github.io/women_majors.csv'').round(2)
# Create list of majors which start under 20% women students
wm_under_20 = list(wm.loc[0, wm.loc[0] < 20].index)

fig = wm.jp.plot(0, wm_under_20, kind='spline', title='The gender gap is transitory - even for extreme cases',
               subtitle='Percentage of Bachelors conferred to women form 1970 to 2011 in the US for extreme cases where the percentage was less than 20% in 1970',
                classes='m-2 p-2 w-3/4')
fig
```
However, the output of that is a raw HighChart object that looks like this:
`HighCharts(id: 3, vue_type: chart, chart options: {'series': [{'data': [4.23, 5.45, 7.42, 9...
`
The desired output would be a plot showing on Jupyter. I feel my limited knowledge of Javascript is not letting me understand the issue. Do you know of any solution or workaround?

**Comment by elimintz** [comment]
Hi,

What I meant in the guide is that you could send a JustPy program to someone, and they could run it to generate a local web page with the chart. The program could read the data from some web location (github in the example above), so you don't need to send them the data or setup a website they need to go to, you just send them a few lines of python.

I found this: https://towardsdatascience.com/javascript-charts-on-jupyter-notebooks-dd25f794cf6a 
Perhaps it can help you integrate Highcharts with Jupyter.
