### ISSUE TITLE
How do I use the Highacharts online examples?

### ISSUE THREAD

**Issue by multigoodverse** [elimintz/justpy#252]
Hi, I continue to be impressed by the work you have done with justpy. I particularly like how intuitive you have made it. Often I don't even have to refer to documentation - I can just guess the name of an argument and bingo - it works.

I now am using the Highcarts online examples from highcharts.com. In the[ justpy docs](https://justpy.io/charts_tutorial/creating_charts/#using-highcharts-online-examples) you suggest copy-pasting the Javascript code from the online examples to our Python code. Maybe it is a stupid question, but what do you suggest doing next in regard to changing the data to our own data? Did you mean to do something like below?

```
import justpy as jp
import pandas

my_chart_def = """
{
    chart: {
        type: 'bar'
    },
    xAxis: {
        categories: [] # I deleted the data of the example
    },
    legend: {
        layout: 'vertical',
        floating: true,
        backgroundColor: '#FFFFFF',
        align: 'right',
        verticalAlign: 'top',
        y: 60,
        x: -60
    },
    series: [{
        data: [] # I deleted the data of the example from here as well
    }]
}
"""
my_data = pandas.DataFrame({'x':[1,2,3], 'y':[4,5,6]})

def chart_test():
    wp = jp.WebPage()
    my_chart = jp.HighCharts(a=wp, classes='m-2 p-2 border w-1/2', options=my_chart_def)
    my_chart.options.xAxis.categories = list(my_data['x'])
    my_chart.options.series[0].data = list(my_data['y'])

    return wp

jp.justpy(chart_test)
```

What I did after copy-pasting the Javascript code was:

1. Delete the data of the example in lines 10 and 22 above
2. Add my own pandas data in lines 31 and 32.

Is this the correct workflow you have meant users to follow or am I getting this all wrong?

**Comment by elimintz** [comment]
Thank you for using JustPy!
You are doing it exactly right. This is what I do when I need a specific Highcharts chart. I find an example online, and then use my own data data and perhaps later tweak some other parameter. It saves me much time starting from one of the many examples already out there.
