### ISSUE TITLE
advanced components feature not picking up javascript portion of the code

### ISSUE THREAD

**Issue by sandeep-gh** [elimintz/justpy#253]
My final goal is to incorporate chartjs into just py. To this end, I was trying out the advanced components feature. For me, the examples mentioned in the tutorial are not working. I have placed the javascript part in the static/components subdirectory of current running directory. 
Both the signature pad and the fullcalendar example don't load the javascipt code.

**Comment by sandeep-gh** [comment]
Below is picture showing the output from the browser:
![justpy_fullcalendar_output](https://user-images.githubusercontent.com/24786309/114968720-8c3ba680-9e94-11eb-9dac-7d962d75aece.png)

**Comment by elimintz** [comment]
Try creating a directory called components that is directly under your running library and putting the javascript there (not under another directory called static).

**Comment by sandeep-gh** [comment]
Thank you. That works.
