### ISSUE TITLE
Feature Request: Support for drag and drop events

### ISSUE THREAD

**Issue by BurnySc2** [elimintz/justpy#26]
Hello, I am attempting to create components that are drag- and drop-able. However, this proves to be difficult without the actual on_drag_start and on_drag_end events. Will those events be implemented in the future?

So far, I have been able to accomplish a workaround solution:

Task / Problem:
Rearrange the pictures from 
![From](http://i.imgur.com/XzOdqBE.png)
to 
![To](http://i.imgur.com/lRzJsIO.png)

Solution:
```py
import justpy as jp
import time
from typing import List

t = 0
elem = None


def on_mouse_enter(self, msg):
    global elem, t
    if (
        time.time() - t < 0.001
        # Dont swap if source and target element are the same
        and elem != self
    ):
        # Execute drag drop by rearranging elements in the components list: move the source element to the position of the target element
        components: List[jp.Img] = elem.a.components
        # Check if elements have the same parent, only then allow the swap
        if self in components:
            index1: int = components.index(elem)
            e: jp.Img = components.pop(index1)
            index2: int = components.index(self)
            components.insert(index2, e)
            # Without the following, the background colors do not change, so the drag and drop event would not be visible if you are using the same image - is there a better way to do this?
            for i in components:
                i.style = "background: ;"
    elem = self


def on_mouse_out(self, msg):
    global t
    # mouse_out event is fired shortly before mouse_enter of the new element, mark time
    t = time.time()


def drag_drop_test():
    wp = jp.WebPage()
    parent = jp.Div(a=wp, classes="container flex flex-wrap")
    background_colors = ["red", "green", "blue", "orange", "yellow"]
    papillons = [
        "https://i.imgur.com/0FBbeev.jpg",
        "https://i.imgur.com/I9Sgzuy.jpg",
        "https://i.imgur.com/PXtHaBk.jpg",
        "https://i.imgur.com/bKq0HtS.jpg",
        "https://i.imgur.com/tdppr9Z.jpg",
    ]
    for i in range(5):
        jp.Img(
            a=parent,
            classes=f"m-1 p-1 h-48 w-48 bg-{background_colors[i]}-600",
            draggable="true",
            src=f"{papillons[i]}",
            mouseenter=on_mouse_enter,
            mouseout=on_mouse_out,
        )
    return wp


jp.justpy(drag_drop_test)
```

Sideeffects: if you simply move your mouse too quickly over the images (without any actual clicks), they will get rearranged in an unpredictable order.

**Comment by elimintz** [comment]
Yes, drag and drop will be implemented in the future. Thank you for the example.

**Comment by elimintz** [comment]
There is initial support for drag and drop in version 0.0.9: https://justpy.io/tutorial/drag_and_drop/
Please try it and let me know how it works for you.

**Comment by fjbay** [comment]
I tried the tutorial and encountered a problem with dropping the image on the divs of the tutorial page:
I'm using Firefox 87 and the default reaction to an image drop reaction is to open the image itself in the current tab. Going back to the tutorial page of course resets it to the initial state.

To prevent this, the default drop event reaction should be suppressed.
