### ISSUE TITLE
Grid API command with parameter

### ISSUE THREAD

**Issue by p-bogi** [elimintz/justpy#262]
I am trying to replicate this ag-grid example: https://www.ag-grid.com/javascript-grid/row-selection/#example-group-selection
Please look at the javascript source (</> icon at left side). It contains:
```
agGrid
    .simpleHttpRequest({
      url: 'https://www.ag-grid.com/example-assets/olympic-winners.json',
    })
    .then(function (data) {
      gridOptions.api.setRowData(data);
    });
```
I am using python daily for creating command line scripts, but I have little knowledge about async python programming and Javascript. I tried to combine my solution from two examples.

My attempt looks like:
```
import justpy as jp
import urllib.request, json 

grid_options = {
    'columnDefs': [
        {'field': 'country', 'rowGroup': 'true', 'hide': True},
        {'field': 'gold', 'aggFunc': 'sum'},
        {'field': 'silver', 'aggFunc': 'sum'},
        {'field': 'bronze', 'aggFunc': 'sum'},
        {'field': 'age', 'minWidth': 120},
        {'field': 'year', 'maxWidth': 120},
        {'field': 'date', 'minWidth': 150},
    ],
    'defaultColDef': {'flex': 1, 'minWidth': 100},
    'autoGroupColumnDef': {
        'headerName': 'Athlete',
        'field': 'athlete',
        'minWidth': 250,
        'cellRenderer': 'agGroupCellRenderer',
        'cellRendererParams': {'checkbox': True},
    },
    'rowSelection': 'multiple',
    'groupSelectsChildren': True,
    'suppressRowClickSelection': True,
    'suppressAggFuncInHeader': True
}

async def set_row_data(self, msg):
    await self.grid.run_api(f"'setRowData({data})'", msg.page)

def grid_test():
    wp = jp.WebPage()
    grid = jp.AgGrid(a=wp, options=json.dumps(grid_options))
    grid.on('gridReady', set_row_data)
    return wp

with urllib.request.urlopen("https://www.ag-grid.com/example-assets/olympic-winners.json") as url:
    data = url.read().decode()

jp.justpy(grid_test)
```
The data is not loaded into table, so the setRowData() API command doesn't seem to be executed correctly. I didn't know how to launch the API function so I attempted to bind it to 'gridReady' event. Is that suitable and correct that way? If not, could you please show me the right way to make this example working?

**Comment by elimintz** [comment]
No need to call the API. Just load the data directly into the grid_options:

```python
import justpy as jp
import urllib.request, json

with urllib.request.urlopen("https://www.ag-grid.com/example-assets/olympic-winners.json") as url:
    data = json.loads(url.read())

grid_options = {
    'columnDefs': [
        {'field': 'country', 'rowGroup': 'true', 'hide': True},
        {'field': 'gold', 'aggFunc': 'sum'},
        {'field': 'silver', 'aggFunc': 'sum'},
        {'field': 'bronze', 'aggFunc': 'sum'},
        {'field': 'age', 'minWidth': 120},
        {'field': 'year', 'maxWidth': 120},
        {'field': 'date', 'minWidth': 150},
    ],
    'defaultColDef': {'flex': 1, 'minWidth': 100},
    'autoGroupColumnDef': {
        'headerName': 'Athlete',
        'field': 'athlete',
        'minWidth': 250,
        'cellRenderer': 'agGroupCellRenderer',
        'cellRendererParams': {'checkbox': True},
    },
    'rowSelection': 'multiple',
    'groupSelectsChildren': True,
    'suppressRowClickSelection': True,
    'suppressAggFuncInHeader': True,
    'rowData': data
}


def grid_test():
    wp = jp.WebPage()
    grid = jp.AgGrid(a=wp, options=grid_options)
    return wp


jp.justpy(grid_test)
```

**Comment by p-bogi** [comment]
Hi, I tried that already. But it brings different result than the original exazmple I linked. The tree structure on the left side is lost. Therefore I thought that the API function does something more to create the tree.

This is result of the solution you proposed:
![image](https://user-images.githubusercontent.com/84622472/120687745-98121500-c4a2-11eb-9896-33b59ae9b847.png)

Hi, thanks for your interest on my question. This comes out of the original example https://www.ag-grid.com/javascript-grid/row-selection/#example-group-selection
![image](https://user-images.githubusercontent.com/84622472/120688244-27b7c380-c4a3-11eb-8bcd-c5cc79ed6f4a.png)

I would like to have multiselect collapsable tree on the left side and few columns on the right side of the tree, like on the original example. 

The original example contains 

>   autoGroupColumnDef: {
>     headerName: 'Athlete',
>     field: 'athlete',
>     minWidth: 250,
>     cellRenderer: 'agGroupCellRenderer',
>     cellRendererParams: {
>       checkbox: true,
>     },
>   },
>
Please note the line
cellRenderer: 'agGroupCellRenderer',
I think this thing does not function in the python example. I think this 'agGroupCellRenderer' is responsible for creating the tree on the left side.
Please look at columnDefs:

>   columnDefs: [
>     { field: 'country', rowGroup: true, hide: true },
>     { field: 'sport', rowGroup: true, hide: true },
>     { field: 'gold', aggFunc: 'sum' },
>     { field: 'silver', aggFunc: 'sum' },
>     { field: 'bronze', aggFunc: 'sum' },
>     { field: 'age', minWidth: 120, checkboxSelection: true, aggFunc: 'sum' },
>     { field: 'year', maxWidth: 120 },
>     { field: 'date', minWidth: 150 },
> 

'athlete' is the only column which is missing in columnDefs but it is defined as the top level of the autoGroupColumnDef tree.
Please note also that there are 2 columns in columnDefs ('country' and 'sport') which have set hide: true. These don't exist in the original table as normal columns, but are sub elements to the left side tree. It seems that without correct execution of 'agGroupCellRenderer' this feature does not work.

**Comment by elimintz** [comment]
You need to do two things to solve the issue:
1) Add `{'field': 'sport', 'rowGroup': 'true', 'hide': True}` to columnDefs as second item
2) In justpy.env add:
```python
AGGRID = False
AGGRID_ENTERPRISE = True
```

The feature is only available in the enterprise version.

**Comment by p-bogi** [comment]
Thanks, with your suggestions it really works as expected!
I found also alternative approach which is not based on autoGroupColumnDef and agGroupCellRenderer(): https://plnkr.co/edit/vN9tLjMmnjH1AHcH5BEK?preview
The solution in this example is based on setting rowGroupIndex:

> grid_options = {
>     'columnDefs': [
>         {
>             'headerName': 'Countries',
>             'children': [
>                 {'headerName': 'Country', 'field': 'country', 'type': 'dimension', 'rowGroupIndex': 0, 'hide': True},
>                 {'headerName': 'Sport', 'field': 'sport', 'type': 'dimension', 'rowGroupIndex': 1, 'hide': True},
>                 {'headerName': 'Athlete', 'field': 'athlete', 'type': 'dimension', 'rowGroupIndex': 2, 'hide': True}
>             ]
> 

I stripped down the base solution from that example and used it with the data from the above olympics medals example. It works also only with AG Grid enterprise license. Here is the adapted example:
```
import justpy as jp
import urllib.request, json 

grid_options = {
    'columnDefs': [
        {
            'headerName': 'Countries',
            'children': [
                {'headerName': 'Country', 'field': 'country', 'type': 'dimension', 'rowGroupIndex': 0, 'hide': True},
                {'headerName': 'Sport', 'field': 'sport', 'type': 'dimension', 'rowGroupIndex': 1, 'hide': True},
                {'headerName': 'Athlete', 'field': 'athlete', 'type': 'dimension', 'rowGroupIndex': 2, 'hide': True}
            ]
        },
        {'field': 'country'},
        {'field': 'sport'},
        {'field': 'athlete'},
        {'field': 'gold'},
        {'field': 'silver'},
        {'field': 'bronze'},
        {'field': 'age', 'minWidth': 120},
        {'field': 'year', 'maxWidth': 120},
        {'field': 'date', 'minWidth': 150},
    ],
    'columnTypes': {
        'dimension': {
            'enableRowGroup': True,
            'enablePivot': True,
        },
    },
    'defaultColDef': {'flex': 1, 'minWidth': 100},
    'rowSelection': 'multiple',
    'groupSelectsChildren': True,
    'suppressRowClickSelection': True,
    'suppressAggFuncInHeader': True,
    'rowData': [
        {"athlete":"Michael Phelps","age":23,"country":"United States","year":2008,"date":"24/08/2008","sport":"Swimming","gold":8,"silver":0,"bronze":0,"total":8},
        {"athlete":"Michael Phelps","age":19,"country":"United States","year":2004,"date":"29/08/2004","sport":"Swimming","gold":6,"silver":0,"bronze":2,"total":8},
        {"athlete":"Michael Phelps","age":27,"country":"United States","year":2012,"date":"12/08/2012","sport":"Swimming","gold":4,"silver":2,"bronze":0,"total":6},
        {"athlete":"Natalie Coughlin","age":25,"country":"United States","year":2008,"date":"24/08/2008","sport":"Swimming","gold":1,"silver":2,"bronze":3,"total":6},
        {"athlete":"Aleksey Nemov","age":24,"country":"Russia","year":2000,"date":"01/10/2000","sport":"Gymnastics","gold":2,"silver":1,"bronze":3,"total":6},
        {"athlete":"Alicia Coutts","age":24,"country":"Australia","year":2012,"date":"12/08/2012","sport":"Swimming","gold":1,"silver":3,"bronze":1,"total":5},
        {"athlete":"Missy Franklin","age":17,"country":"United States","year":2012,"date":"12/08/2012","sport":"Swimming","gold":4,"silver":0,"bronze":1,"total":5},
        {"athlete":"Ryan Lochte","age":27,"country":"United States","year":2012,"date":"12/08/2012","sport":"Swimming","gold":2,"silver":2,"bronze":1,"total":5},
        {"athlete":"Allison Schmitt","age":22,"country":"United States","year":2012,"date":"12/08/2012","sport":"Swimming","gold":3,"silver":1,"bronze":1,"total":5}
    ]
}

def grid_test():
    wp = jp.WebPage()
    grid = jp.AgGrid(a=wp, options=json.dumps(grid_options))
    return wp

jp.justpy(grid_test)

```
![image](https://user-images.githubusercontent.com/84622472/120709623-5b074c00-c4bd-11eb-9624-33665fabe3c1.png)
