### ISSUE TITLE
issues with current version of  tailwind code in "/templates/local/tailwind"  -- how to update those

### ISSUE THREAD

**Issue by sandeep-gh** [elimintz/justpy#265]
There is a bug in tailwind current version code integrated with justpy. The code below should create a div area of half the size of the screen  but ends up not creating no div element:

```python
def split_screen():
  full_div = jp.Div(
        a=wp, classes="w-screen h-screen bg-pink-100")

    tt = jp.Div(a=full_div, classes="w-1/2 h-1/2 bg-gray-400")
    jp.P(a=tt, text="area1")
    return wp
```
However, if I force to use latest tailwind version
```
wp.head_html = '<link href="https://unpkg.com/tailwindcss/dist/tailwind.min.css" rel="stylesheet">'
```

the above code works as expected.  Also, where can I grab base.css, components.css and other tailwind codes for justpy. 

Thanks.

**Comment by elimintz** [comment]
The current version of JustPy loads the version 1 of Tailwind. The solution is to do what you have done. tailwind.min.css includes all three files so you don't need to load them seperately.

**Comment by sandeep-gh** [comment]
Thank you. Will also look into if can could replace the base.css and related files for the latest version.
