### ISSUE TITLE
Ist it possible QuasarPage combined Webpage?

### ISSUE THREAD

**Issue by Nandreasyan** [elimintz/justpy#275]
Hello,

I am new in justpy, I have the following question.
Is it possible the following scenario?
First I Create a jp.WebPage and some divisions organized with tailwind.
Now the question is  it possible to create QuasarPage or quasar components in a some of this division components?
Or it is only allowed to create WebPage or QuasarPage in the same webpage?

Let take the following example QList and QItem, now the question is it possible to place it let say in the following division in the same webpage:
Layout_for_events_output = jp.Div(text='Dynamic output', a=gridlayout_div, classes=cell_Layout_span_3)

def check_box_clicked(self, msg):
    wp = msg.page

    def my_filter(var):
        for letter in self.value:
            if var.startswith(letter):
                return True
        return False

    filtered_list = list(filter(my_filter, wp.list_item_text))

    for c in wp.q_list.components:
        if c.components[0].text not in filtered_list:
            c.show = False
        else:
            c.show = True

wp = jp.QuasarPage()
d = jp.Div(classes="q-pa-md", style="max-width: 400px", a=wp)
wp.list_item_text = ['apple', 'ad', 'aardvark', 'again', 'bean', 'bath', 'beauty', 'can', 'corner', 'capital']
wp.q_list = jp.QList(dense=True, bordered=True, padding=True, classes="rounded-borders", a=d)
for word in wp.list_item_text:
    q_item = jp.QItem(clickable=True, v_ripple=True, a=wp.q_list)
    jp.QItemSection(text=word, a=q_item)

option_group = jp.QOptionGroup(type='checkbox', color='green', a=d, input=check_box_clicked, value=['a', 'b', 'c'],
                               inline=True, classes='q-ma-lg',
                options=[{'label': 'A words', 'value': 'a'}, {'label': 'B words', 'value': 'b'}, {'label': 'C words', 'value': 'c'}])

def mypage():
    return wp

jp.justpy(mypage)

**Comment by elimintz** [comment]
If you want to use tailwind classes in a Quasar page declare the page the following way:
```python
wp = jp.QuasarPage(tailwind=True)
```

Keep in mind that they are a few color classes that clash between Quasar and Tailwind so there may be a few quirks but it mostly works well.

**Comment by Nandreasyan** [comment]
> If you want to use tailwind classes in a Quasar page declare the page the following way:
> 
> ```python
> wp = jp.QuasarPage(tailwind=True)
> ```
> 
> Keep in mind that they are a few color classes that clash between Quasar and Tailwind so there may be a few quirks but it mostly works well.

aha, the whole page should be QuasarPage? so I can not create WebPage and QuasarPage in the same webpage?

**Comment by elimintz** [comment]
QuasarPage is a class that inherits from WebPage. Basically it uses a different template that loads the Quasar library and CSS. So a QuasarPage with tailwind set to True does all the things a WebPage does.

**Comment by Nandreasyan** [comment]
> QuasarPage is a class that inherits from WebPage. Basically it uses a different template that loads the Quasar library and CSS. So a QuasarPage with tailwind set to True does all the things a WebPage does.

Thank you very much for quick response. I could not figure out why it is not working.
Have nice day.
