### ISSUE TITLE
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?  use-chips=True

### ISSUE THREAD

**Issue by Nandreasyan** [elimintz/justpy#277]
QSelect can not understand   parameter use-chips=True, I checked in the parameters lists use-chips is listed.
Ist it possible to fix this quickly? or it is a big bug problem?

style='width: 350px; margin: 0.25rem; padding: 0.25rem;', use-chips=True,  label="Select the goals")
                                                                                            ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
python-BaseException

@jp.SetRoute('/test')
def test():
    wp = jp.QuasarPage()

    s = jp.QSelect(filled=True,  options=table_names, a=wp, outlined=True, multiple=True, input=selected_event,
                   style='width: 350px; margin: 0.25rem; padding: 0.25rem;', use-chips=True,  label="Select")

    return wp

**Comment by elimintz** [comment]
The options in Python are with the underline, not the hyphen. Try `use_chips=True` instead.

**Comment by Nandreasyan** [comment]
Thank you, that works.
