### ISSUE TITLE
For a QuasarPage the head_html is not working properly

### ISSUE THREAD

**Issue by platinops** [elimintz/justpy#28]
Below code (modified from the justpy homepage) results in the head_html string being shown on the web page. The html tags seem to be escaped. This can be solved by adding the safe keyword to the Jinja tag of the [quasar.html](https://github.com/elimintz/justpy/blob/master/justpy/templates/quasar.html) file.

On line 30, `{{ page_options.head_html }}` should become `{{ page_options.head_html | safe }}` - if I'm not mistaken?

`import justpy as jp`
`def test_head():`
`    wp = jp.QuasarPage()`
`    wp.head_html = '<script>console.log("Hello there from head");</script>'`
`    wp.body_html = '<script>console.log("Hello there from body");</script>'`
`    jp.Div(text='Testing...', a=wp)`
`    return wp`
`jp.justpy(test_head)`

**Comment by elimintz** [comment]
You are right, thank you for catching this.
