### ISSUE TITLE
set_class removes existing classes attribute

### ISSUE THREAD

**Issue by sandeep-gh** [elimintz/justpy#281]
The following code reproduces the bug
```
import justpy as jp

def launcher():
    wp = jp.WebPage()

    d = jp.Div(a=wp, classes="flex flex-col")
    jp.Span(a=d, text="b1")
    jp.Span(a=d, text="b2")
    d.set_class("hidden")
    d.remove_class("hidden")
    print (d.classes)
    return wp


jp.justpy(launcher)
```

After `.set_class("hidden")` and `.remove_class("hidden")` operation, the classes for `d` div element contains only `flex-col`. The `flex` is lost due to the set/remove operation.

**Comment by elimintz** [comment]
This is not a bug. Both `hidden` and `flex` are in the tailwind display category: https://tailwindcss.com/docs/display
The `flex` is lost because if display is set to `hidden` it cannot be `flex`. The way to toggle between hidden and flex is just to use set_class:

```python
import justpy as jp

def launcher():
    wp = jp.WebPage()

    d = jp.Div(a=wp, classes="flex flex-col")
    jp.Span(a=d, text="b1")
    jp.Span(a=d, text="b2")
    d.set_class("hidden")
    d.set_class("flex")
    print (d.classes)
    return wp


jp.justpy(launcher)
```

**Comment by sandeep-gh** [comment]
I see. Missed that in tailwind docs. Thank you for clarifying.
