### ISSUE TITLE
in QSlider vertical varaint is not working

### ISSUE THREAD

**Issue by Nandreasyan** [elimintz/justpy#292]
Hello,

unfortunately in JustPy vertical variant of QSlider is not working
[https://quasar.dev/vue-components/slider#example--vertical-orientation](https://quasar.dev/vue-components/slider#example--vertical-orientation)
```
import justpy as jp

def mypage():
    wp = jp.QuasarPage(delete_flag=True, tailwind=True)
    stylelayouttext = "text-align: center;"
    borderforparamters = "my-4 border-2 border-pink-900 rounded-lg"
    layoutforeventfocus = jp.Div(text='Select test', style=stylelayouttext,
                                 a=wp, classes=borderforparamters)
    jp.QSlider(a=layoutforeventfocus, snap=True, markers=True,  label=True,
           vertical=True, min=1, max=14, step=1, value=5)

    return wp

jp.justpy(mypage)
```

Is it difficult to fix it?
Or what shall I do to get it worked?

Regards
Narek

**Comment by elimintz** [comment]
This will fix the issue:

```python
import justpy as jp

def mypage():
    wp = jp.QuasarPage(delete_flag=True, tailwind=True)
    stylelayouttext = "text-align: center;"
    borderforparamters = "my-4 border-2 border-pink-900 rounded-lg"
    layoutforeventfocus = jp.Div(text='Select test', style=stylelayouttext,
                                 a=wp, classes=borderforparamters)
    s = jp.QSlider(a=layoutforeventfocus, snap=True, markers=True,  label=True,
           vertical=True, min=1, max=14, step=1, value=5)
    s.prop_list.append('vertical')

    return wp

jp.justpy(mypage)
```

In the upcoming version `vertical` will already be part of the prop_list. It was added to Quasar after the previous version of JustPy was released.

**Comment by Nandreasyan** [comment]
Is it working for you?

For me, it is not working.

What is wrong in my configuration? It is still horizontal.

**Comment by elimintz** [comment]
Try running with:
`NO_INTERNET = False`
in justpy.env 
It could be the case that vertical is not supported with the local Quasar version that is currently in JustPy. The option causes the latest version to be downloaded from the net

**Comment by Nandreasyan** [comment]
> NO_INTERNET = False

Thank you, now it has worked.
