### ISSUE TITLE
Do you know any online platform that can deploy justpy Project?

### ISSUE THREAD

**Issue by Nandreasyan** [elimintz/justpy#300]
Hello,

Do you know any online platform that can deploy justpy Project?
2 days I tried pythonanywhere, but it turns out that it is not working.

**Comment by elimintz** [comment]
Hi,
Pythonanywhere does not support websockets. I use digitalocean.com but any service that gives you a Linux VM would do. The simplest droplet works very well for most cases and can support hundreds of requests per second.

**Comment by Nandreasyan** [comment]
Thank you very much.
