### ISSUE TITLE
QSelect not honoring input_style argument

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#31]
Loving JustPy! However, when I add an input_style argument to a QSelect it doesn't honor the input style, it overrides it with the default color. 

For example:
`jp.QSelect(input_style='color:#0088cc !important;text-decoration: underline dotted')`

**Comment by elimintz** [comment]
Thanks for using JustPy and for catching this. 

Not clear why this is not working. There is no evident problem in the code. It treats `input_style` and `input_class` just like any other prop. I'll look further into this.

If you create anything interesting with JustPy that can showcased, please let me know.

**Comment by knoxvilledatabase** [comment]
One of the most fantastic things I love about JustPy is importing the Django ORM to eliminate REST:
`sys.path.append('../path_to_project')`
`os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings')`
`from django import setup`
`setup()`
`from my_django_project.models import MyModel`
`import justpy as jp`
`...`

As for QSelect, when I add regular "style" argument with text decoration it adds the text decoration to topmost label but it appears that the nested 'q-field__native' color styling is overidding the QSelect style. 

When I add an "input_style" argument I don't see the style anywhere. 

Here is an example of QSelect with style argument:

`jp.QSelect(style='color:#0088cc !important;text-decoration: underlinedotted',)`

Style is located on <label style=...>

`<div><label for="f_ea4f8949-f28e-452d-8183-f9253357f2b7" class="q-field row no-wrap items-start q-select q-field--auto-height q-select--without-input q-field--borderless q-field--float q-field--dense" style="color: rgb(0, 136, 204) !important; text-decoration: underline dotted;"><div class="q-field__inner relative-position col self-stretch column justify-center"><div tabindex="-1" class="q-field__control relative-position row no-wrap text-blue"><div class="q-field__control-container col relative-position row no-wrap q-anchor--skip"><div id="24" class="q-field__native row items-center"><span>Building A</span><input tabindex="-1" class="q-select__autocomplete-input no-outline"><div tabindex="0" id="f_ea4f8949-f28e-452d-8183-f9253357f2b7" class="no-outline"></div></div></div><div class="q-field__append q-field__marginal row no-wrap items-center q-anchor--skip"><i aria-hidden="true" role="presentation" class="q-select__dropdown-icon q-icon notranslate"></i></div><!----></div></div></label></div>`

When using QSelect input_style I don't see the style anywhere:

`jp.QSelect(input_style='color:#0088cc !important;text-decoration: underlinedotted',)`

`<div><label for="f_0809afcd-fd7d-416f-879f-ed68f0e3ae57" class="q-field row no-wrap items-start q-select q-field--auto-height q-select--without-input q-field--borderless q-field--float q-field--dense"><div class="q-field__inner relative-position col self-stretch column justify-center"><div tabindex="-1" class="q-field__control relative-position row no-wrap text-blue"><div class="q-field__control-container col relative-position row no-wrap q-anchor--skip"><div id="24" class="q-field__native row items-center"><span>Building A</span><input tabindex="-1" class="q-select__autocomplete-input no-outline"><div tabindex="0" id="f_0809afcd-fd7d-416f-879f-ed68f0e3ae57" class="no-outline"></div></div></div><div class="q-field__append q-field__marginal row no-wrap items-center q-anchor--skip"><i aria-hidden="true" role="presentation" class="q-select__dropdown-icon q-icon notranslate"></i></div><!----></div></div></label></div>`

I also tried the color argument and that doesn't seem to have any effect either, it seems that "q-field__native overrides any font color styling.

**Comment by elimintz** [comment]
Thank you for the work around suggestion.

Could you please explain a little more why you combine Django features and JustPy? What do you mean by "eliminate REST"?  Do you mean you don't need to build a Django backend to serve data using an API to the front-end?

**Comment by knoxvilledatabase** [comment]
Right! Because JustPy is already in Python, there is no longer a need for Django REST, just communicate directly to the ORM without any AJAX/JSON/REST calls.

Just import your Django Project with:

`sys.path.append('../path_to_project')`
`os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'settings')`
`from django import setup`
`setup()`

Import your django models:
`from my_django_project.models import MyModel`

Then with JustPy communicate directly to the Django ORM and viola now you can just turn off Django REST, its no longer needed. Here is a simple example:

`import justpy as jp`
`def layout(request):`
`wp = jp.QuasarPage()`
`....def change_django_model(self, msg, target):
........MyModel.objects.filter(id=self.dj_instance_id).update(some_field=False)`

`....jp.QBtn(text=f'Change Django Model', click=self.change_django_model, a=wp)`

(Dots are spaces, theres probably a better way)

**Comment by elimintz** [comment]
Beautiful! Thanks,
