### ISSUE TITLE
QInnerLoading while loading the data?

### ISSUE THREAD

**Issue by wy1189** [elimintz/justpy#316]
If anyone has an idea how to deal with this situation, that would be helpful.

I'm trying to implement a spinner for loading time, but it doesn't work.

My scenario is: 1) click a chart -> 2) load QDialog as a pop-up window -> 3) show QInnerLoading (spinner) while loading the data -> 4) read and load the data on table -> 5) remove spinner, but I only see the final table without the spinner. My intention is to show the spinner so that something is going on behind the webpage (i.e., data loading).

Here is an example code.

```python3

import justpy as jp
import pandas as pd
import asyncio

my_chart_def = """
{
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Fruit Consumption'
        },
        xAxis: {
            categories: ['Apples', 'Bananas', 'Oranges']
        },
        yAxis: {
            title: {
                text: 'Fruit eaten'
            }
        },
        series: [{
            name: 'Jane',
            data: [1, 0, 4]
        }, {
            name: 'John',
            data: [5, 7, 3]
        }]
}
"""

async def click_point(self, msg):
    self.dialog.value = True
    self.spinner.showing = True
    await asyncio.sleep(3)
    wm = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)
    table.load_pandas_frame(wm)
    self.spinner.showing = False

def spinner_test():
    # set web page
    wp = jp.QuasarPage(tailwind=True, debug=True, delete_flag=False)
    div = jp.QDiv(classes="q-pa-md q-gutter-sm", a=wp)

    # set Qdialog for pop-up window
    dialog = jp.QDialog(name='alert_dialog', persistent=False, a=div, full_width=True, full_height=True)
    card = jp.QCard(a=dialog, classes=['w-2/6'])
    card_text = jp.QCardSection(a=card, text='This is a test message')
    
    # set close button
    btn_section = jp.QCardActions(a=card, classes=['flex', 'justify-between'])
    close_btn = jp.QBtn(flat=True, label='Close', color='primary', v_close_popup=True, a=btn_section)

    # set the data table
    table = jp.QTable(a=card, title='Table test', classes='m-2 p-2 w-3/4', style='height: 500px; width: 1800px',
                    pagination={'rowsPerPage': 10})

    # set the spinner for loading time
    spinner = jp.QInnerLoading(showing=False, a=card)

    # an example chart
    my_chart = jp.HighCharts(a=wp, classes='m-2 p-2 border', style='width: 600px', options=my_chart_def)
    # set chart click interaction to show the data table
    my_chart.on('point_click', click_point)
    my_chart.dialog = dialog
    my_chart.spinner = spinner
    return wp

jp.justpy(spinner_test, port=9999)
```

Here `await asyncio.sleep(3)` and `wm = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)` are used for an example to mimic the loading time, but the actual code have only `pd.read_csv` or equivalent with huge data.

Is there any way to implement a spinner while processing something else?

**Comment by elimintz** [comment]
Hi,
Change click_point to:
```python
async def click_point(self, msg):
    self.dialog.value = True
    self.spinner.showing = True
    await msg.page.update()
    await asyncio.sleep(3)
    wm = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)
    table.load_pandas_frame(wm)
    self.spinner.showing = False
```

You need to update the page for the spinner change to take effect.

**Comment by wy1189** [comment]
Thank you so much for your comments.

It worked well! I appreciate your help. But I slightly changed because time delay is not asynchronous but synchronous what I initially thought.

```python
import time

async def click_point(self, msg):
    self.dialog.value = True
    self.spinner.showing = True
    await msg.page.update()
    time.sleep(3)
    wm = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)
    table.load_pandas_frame(wm)
    self.spinner.showing = False
```

Can I have one following question? I'm wondering why I don't need to update the page again to take effect on spinner change? When `click_point` is done, it's internally (or automatically by the library) updated?

```python
async def click_point(self, msg):
    self.dialog.value = True
    self.spinner.showing = True
    await msg.page.update()
    time.sleep(3)
    wm = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)
    table.load_pandas_frame(wm)
    self.spinner.showing = False
    await msg.page.update()
```

**Comment by elimintz** [comment]
It is better to use async calls to io or sleep functions inside event handlers because otherwise they will block the whole applications. The whole application (all users) will not be responsive. It is like you halted the web server for 3 seconds.

You don't need a page update in an event handler usually because if it returns None, the framework knows it needs to update the page.  If you for example you add the line `return True` to the event handler, it will not update the page.

**Comment by wy1189** [comment]
Oh... I see. I am currently working on it locally, so it doesn't matter, but it could be important to know this at some point. Thank you for the explanations. But, as I mentioned before, `asyncio.sleep()` is intended to show the data loading time as an example, but if the file is too big (e.g, 1GB csv file and read it from `pd.read_csv()`), or, it's a table from Google BigQuery, how can I handle it asynchronously? Maybe it's a dumb question, but I'm wondering if you have any ways to handle blocking functions as an asynchronous function.

Okay, so, if an event handler returns None, the framework automatically updates the page as intended. Thank you for the clarification.

**Comment by elimintz** [comment]
Maybe read the file once on startup and then use the frame as a global variable? 

As for bigquery: https://stackoverflow.com/questions/53065340/python-how-to-big-query-asynchronous-tasks/53073290

**Comment by wy1189** [comment]
That sounds a good plan, but it will take time at first without a startup page.

I will look into the asynchronous BigQuery one. Thank you very much for all of your helps 👍
