### ISSUE TITLE
QStepper without the Carousel

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#32]
![Screen Shot 2020-03-12 at 12 45 38 AM](https://user-images.githubusercontent.com/2231079/76488099-d3867680-63fa-11ea-8fff-224b492f9126.png)
It would be awesome if there was a better way to have the QStepper without the Carousel. 

Below is a workaround using css on QDivs:

`steps=[`
`        {"status": "done", "step": 1, "title": "Submitted"},`
`        {"status": "done", "step": 2, "title": Confirmed"},`
`        {"status": "active", "step": 3, "title": "In Process"},`
`        {"status": "", "step": 4, "title": "Completed"}`
`]`
`Stepper(steps=steps, a=whatever_you_want)`

`class Stepper(jp.QDiv):`

`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        self.steps = kwargs.get('steps', None)`
`        stepper_base = jp.QDiv(`
`            classes='q-stepper q-stepper--horizontal',`
`            color="primary",`
`            a=self,`
`            style='max-width:900px'`
`        )`
`        self.stepper_header = jp.QDiv(`
`            classes='q-stepper__header row items-stretch justify-between` 
`                     q-stepper__header--alternative-labels',`
`            style='text-align:left',`
`            a=stepper_base`
`         )`

`        for step in self.steps:`
`        self.get_step(step['status'], step['step'], step['title'])`

`    def get_step(self, status, step_number, caption):`
`        step_status = ''`
`        if status == 'active':`
`            step_status = 'q-stepper__tab--active'`
`        if status == 'done':`
`            step_status = 'q-stepper__tab--done'`
`        step = jp.QDiv(`
`            classes=f'q-stepper__tab col-grow flex items-left no-wrap` 
`                     relative-position {step_status}',`
`            a=self.stepper_header`
`        )`
`        step_container = jp.QDiv(`
`            classes='q-stepper__dot row flex-center q-stepper__line relative-position',`
`            style='margin-left:40px',`
`            a=step`
`        )`
`        if status == 'done':`
`            done_span = jp.Span(a=step_container)`
`            jp.QIcon(name='check', a=done_span)`
`        else:`
`            jp.Span(text=f"{step_number}", a=step_container)`
`        jp.Div(`
`            text=caption.upper(),`
`            style='margin-top:10px;max-width:100px;text-align:center;`
`                   font-weight:bold;color: #666',`
`            a=step`
`        )`

**Comment by elimintz** [comment]
Very cool!

I will try to make QStepper, QTabPanels, QCarousel work.

**Comment by Lefort-Antoine** [comment]
Hy, 
Do you succed to make QTabPanels work ?
