### ISSUE TITLE
cell visualization within ag-grid

### ISSUE THREAD

**Issue by wy1189** [elimintz/justpy#320]
Hi (again),

I'm wondering it's doable to implement the cell visualization (please see Proficiency column in the screenshot). I excerpted the photo from the ag-grid official webpage, but I have no idea what it is called and how I can show the bar graph within the columns. Any ideas?

![image](https://user-images.githubusercontent.com/9031310/142681096-dcf94af9-c1ff-403a-be6d-86eac559c24c.png)

**Comment by elimintz** [comment]
Not sure but maybe the info is here: https://www.ag-grid.com/javascript-data-grid/integrated-charts/

**Comment by wy1189** [comment]
Thank you for the link. I already checked out the link before, but it seems like integrating charts with the table. I was looking for the cell visualization in the specific cells such as Proficiency column in the screenshot.

I might need to reach out to Ag-grid guys...

**Comment by wy1189** [comment]
I figured it out how to implement cell visualization in AgGrid

```python
import justpy as jp
import pandas as pd

wm_df = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)


def grid_test():
    wp = jp.WebPage()
    grid = jp.AgGrid(a=wp)
    grid.load_pandas_frame(wm_df)
    for row in grid.options.rowData:
        for cell in [*row][1:]:
            row[cell] = f"""<div class="flex m-0">
                <div class="-ml-3 bg-purple-500" style="width: {row[cell]}%"></div>
                <div class="ml-1 text-black">{row[cell]}</div>
            </div>"""
    grid.html_columns = list(range(1, wm_df.shape[1]))
    return wp


jp.justpy(grid_test)

```
