### ISSUE TITLE
Fails in Air-Gap Network

### ISSUE THREAD

**Issue by DeviceNut** [elimintz/justpy#322]
I realize this probably has to do with the uvicorn server or ASGI or whatever else is running underneath your code, but I thought I'd see if you have any ideas on how to make this stack work in a network without access to the internet, which seems to fail in the following way: the server runs, and the browser successfully attaches (the browser tab name/icon gets set), but I just get a blank page.

I've tried using Ajax instead of websockets and that doesn't help.

Any ideas?

**Comment by elimintz** [comment]
Not sure what the problem is. Justpy should work without needing resources from the internet:
https://justpy.io/tutorial/configuration/#quasar-version

Maybe just try the simplest program and see if the problem persists?

**Comment by DeviceNut** [comment]
I'm not saying JustPy does, but the underlying server stack you're using (uvicorn etc.), which I'm not familiar with. It's not the code I'm running.

It appears that something in that stack requires access to the internet to function properly? Just hoping you'd have some insights into what that might be.

**Comment by elimintz** [comment]
Sorry, I did not explain myself well. The way I test this is disconnect my computer from the internet and run a program. This works. The whole stack can work without needing to be connected to the Internet. So the problem I think is probably not with the stack but with settings in your environment.

**Comment by DeviceNut** [comment]
Yeah it was me: I was pulling in a SVG file. How can I serve that as a file using jp.Img?

**Comment by elimintz** [comment]
Please take a look at https://justpy.io/tutorial/static/

**Comment by DeviceNut** [comment]
Tried that, doesn't work: getting a 404.

**Comment by elimintz** [comment]
Please check in which directory you are putting the downloaded file. By default the static directory is the directory the program is run from.

**Comment by DeviceNut** [comment]
Yes. The example in the docs doesn't work for me:

import justpy as jp
def static_test():
    wp = jp.WebPage()
    jp.Img(src='/static/test.jpg', a=wp, classes='m-2 p-2')
    return wp
jp.justpy(static_test)

The file 'test.jpg' is in the same directory as the test.py file above. Chrome says: 

http: Domain: localhost
test.jpg:1 GET http://localhost:8000/static/test.jpg 404 (Not Found)
(index):1812 Webocket opened

The second line expands to:
test.jpg:1 GET http://localhost:8000/static/test.jpg 404 (Not Found)
Image (async)
hr @ vue.js:2
vr @ vue.js:2
dr @ vue.js:2
y @ vue.js:2
f @ vue.js:2
(anonymous) @ vue.js:2
e._update @ vue.js:2
r @ vue.js:2
fn.get @ vue.js:2
fn @ vue.js:2
(anonymous) @ vue.js:2
wn.$mount @ vue.js:2
wn.$mount @ vue.js:2
init @ vue.js:2
(anonymous) @ vue.js:2
f @ vue.js:2
h @ vue.js:2
f @ vue.js:2
(anonymous) @ vue.js:2
e._update @ vue.js:2
r @ vue.js:2
fn.get @ vue.js:2
fn @ vue.js:2
(anonymous) @ vue.js:2
wn.$mount @ vue.js:2
wn.$mount @ vue.js:2
t._init @ vue.js:2
wn @ vue.js:2
(anonymous) @ (index):2005

**Comment by DeviceNut** [comment]
Should I open a new issue for this?

**Comment by WolfgangFahl** [comment]
yes
