### ISSUE TITLE
How to open new tab from page

### ISSUE THREAD

**Issue by DeviceNut** [elimintz/justpy#323]
Trying to open a new tab with a different route from an already opened page using jp.A(), which just redirects. I see the WebPage.open attribute, but setting it seems to have no effect.

**Comment by elimintz** [comment]
Can you please explain the problem in more detail?

This works for example:
```python
import justpy as jp

def link_demo():
    wp = jp.WebPage()
    jp.A(text='Python Org', href='https://python.org', a=wp, classes='m-2 p-2 text-xl text-white bg-blue-500 hover:bg-blue-700')
    return wp

jp.justpy(link_demo)
```

**Comment by DeviceNut** [comment]
I want to have the redirect open in its own tab, leaving the previous page open. Probably need some javascript for that?

**Comment by elimintz** [comment]
No, just add the appropriate target setting:
```python
import justpy as jp

def link_demo():
    wp = jp.WebPage()
    jp.A(text='Python Org', target='_blank', href='https://python.org', a=wp, classes='m-2 p-2 text-xl text-white bg-blue-500 hover:bg-blue-700')
    return wp

jp.justpy(link_demo)
```

**Comment by DeviceNut** [comment]
Of course, right, that works.
