### ISSUE TITLE
Getting 404 for ajax request

### ISSUE THREAD

**Issue by jfitisoff-juul** [elimintz/justpy#325]
I'm thinking/hoping that this is some sort of config issue on my part. I have an app that is using AJAX. The app is working except when an AJAX request, which _consistently_ fails with a 404 error. The URL looks like this:

```
POST: https://server.com/zzz_justpy_ajax 
```

And the failure is occurring at quasar.js line 6.

Here's how I'm starting the app:

```
jp.justpy(channels_page, websockets=False, start_server=False)
uvicorn.run(app, host='0.0.0.0', port=80, log_level='info', log_config='logging_config.conf')
```

Any help appreciated. Thanks!

**Comment by elimintz** [comment]
Could you please run the first example on this page: https://justpy.io/tutorial/ajax/
Let me know if it works for you.

**Comment by jfitisoff-juul** [comment]
Went a little further than that, installed a barebones flask app and even that's having problems. Thanks for responding so quickly
