### ISSUE TITLE
tailwind can't be disabled with justpy.env

### ISSUE THREAD

**Issue by freemant2000** [elimintz/justpy#327]
The doc says tailwind can't be disabled with justpy.env, but actually I have to use:
`
WebPage.tailwind=False
`
to disable it.

**Comment by elimintz** [comment]
If you use QuasarPage, Tailwind is disabled for you already.

**Comment by freemant2000** [comment]
Thanks for the tip :-) Hope the doc is updated too and the code reading the TAILWIND from the config file can also be removed.
