### ISSUE TITLE
Custom Template with no Internet Dependencies

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#33]
A majority of the applications I build are intranet facing and require uptime even when the Internet connection goes down. Last week I had a connection go down for an entire day. 

Would it be possible to add an option to specify a custom template so that I can serve the css and javascript files locally incase the Internet connection goes down? 

Thank you for this consideration.

**Comment by elimintz** [comment]
Yes, that is possible. I will make that available in an upcoming version.

**Comment by AgarwalPragy** [comment]
You can do that even now.
Just point justpy to your custom templates folder, and create your own templates!

```
STATIC_DIRECTORY = static/
TEMPLATES_DIRECTORY = static/templates
```

I didn't want any of the JS addons, so I removed everything like tailwind, quasar, aggrid, highcharts f from my template.

templates/custom.html
```html
{% if not html %}
<!DOCTYPE html>
<html>
<head>
    {% include 'favicon.html' %}
    {% if not html %}
    <script src="/static/vendor/jquery-3.3.1.min.js"></script>
    <script src="/static/vendor/vue.min.js"></script>
    <script src="/static/vendor/ace-builds/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/vendor/mathjax/es5/tex-svg.js" type="text/javascript" id="MathJax-script" async ></script>
    <script src="/static/js/main.js" type="text/javascript" charset="utf-8"></script>
    <link rel="stylesheet" href="/static/css/main.css">
    {% endif %}
</head>
<body style="{{ page_options.body_style }}" class="{{ page_options.body_classes }}">
{{ page_options.body_html | safe }}
<div id="components">

</div>

{% include 'justpy/main.html' %}
</body>
</html>
{% else %}{{ html | safe }}
{% endif %}
```

Just make sure that you set the Webpage.template to "custom.html" or whatever your file name is :)

**Comment by knoxvilledatabase** [comment]
Worked great, thanks! This one can be closed.

**Comment by elimintz** [comment]
I'm glad that worked for you!
