### ISSUE TITLE
Cannot install justpy - "error in demjson setup command: use_2to3 is invalid"

### ISSUE THREAD

**Issue by 1081** [elimintz/justpy#334]
During installation of justpy this error occurs: `error in demjson setup command: use_2to3 is invalid`

[see here](https://exerror.com/error-in-mongoengine-setup-command-use_2to3-is-invalid/)

(tested on MacBook Air M1 with python 3.8 and 3.9)

**Comment by MarkSimUM** [comment]
There is a thread on this.  You need to downgrade setuptools before installing justpy.
pip install setuptools==56.0.0

**Comment by 1081** [comment]
thanks see https://github.com/elimintz/justpy/issues/301
