### ISSUE TITLE
QTooltip "self" prop issue

### ISSUE THREAD

**Issue by fx-991ES** [elimintz/justpy#336]
Came across an odd bug today I thought I should point out.

The quasar component QTooltip has a prop which is "self", but when trying to set that python understandably doesn't like it...

The error thrown is: `TypeError: __init__() got multiple values for argument 'self'`

I assume this will affect all quasar components with a "self" prop (but I haven't tested this), I had a quick search in [quasarcomponents.py](https://github.com/elimintz/justpy/blob/42275e9c6e00373f09affd7d781a278383171807/justpy/quasarcomponents.py) and can see that these components all have that prop:
- QMenu
- QPopupProxy
- QTooltip
- QPopupEdit

**Comment by elimintz** [comment]
Thanks for this. Did you try setting this attribute after initializing the instance?
```python
t = jp.QTooltip(...)
t.self = 'bottom left'
```

I think it should work based on the error you are getting.

**Comment by fx-991ES** [comment]
I hadn't tried that but it works, thank you!
