### ISSUE TITLE
.to_html {AttributeError}'AgGrid' object has no attribute 'to_html'

### ISSUE THREAD

**Issue by elbehery95** [elimintz/justpy#34]
I was trying to use justpy in order to generate interactive HTML reports. Following the [documentation ](https://justpy.io/reference/webpage/#to_htmlself-indent0-indent_step0-formattrue) i wanted to use the `.to_html` method on the generated webpage object as the following

```py
def grid_test():
    wm_df = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)
    wp = jp.WebPage()
    grid = jp.AgGrid(a=wp)
    grid.load_pandas_frame(wm_df)
    return wp.to_html()
```

But the following error is raised `.to_html {AttributeError}'AgGrid' object has no attribute 'to_html'`

Is this expected ?

**Comment by elimintz** [comment]
For this to work in JustPy you just need to return wp.
Change the last line to `return wp` and the page will be served with the grid.

Please take a look at the example in the tutorial: https://justpy.io/grids_tutorial/pandas/

If you need the html presentation for the page this is not available with an AgGrid component since it has no html presentation.

**Comment by elbehery95** [comment]
@elimintz  Thanks for your comment but my intentions was not to return the webpage it self. I wanted to return the `html` content to be dumped later into a `.html` file. I wanted to utilize justpy model for producing reports with pandas but seems this is not supported

Thanks for your time

**Comment by elimintz** [comment]
You can use JustPy to create an interactive page that is the report and send people the link. Is that use case helpful to you?

**Comment by elbehery95** [comment]
Thanks elimintz, i wanted to explore justpy as a pandas renderer ) possibly using ag-grid and plotly. My goal was to export an html that is standalone and can work offline

I tried digging more into the API but seems i can add a `<script></script>`  tags
