### ISSUE TITLE
[feature request]support `pandas.Styler` in `load_pandas_frame` 

### ISSUE THREAD

**Issue by qiuwei** [elimintz/justpy#341]
For people who are familiar with pandas but lack frontend knowledge, this feature would be super handy!

**Comment by elimintz** [comment]
The styler creates html which you can then be passed to parse_html:  https://justpy.io/tutorial/working_with_html/#the-parse_html-function

So if I understand correctly, this is already supported.

**Comment by qiuwei** [comment]
Indeed, it works like a charm! A slight modification of the Justpy ag-grid example renders nicely.
![image](https://user-images.githubusercontent.com/1304505/150470287-b663e71e-505c-4d0f-bb21-5136f393d29c.png)


```
import justpy as jp
import pandas as pd

# Load data showing percent of women in different majors per year
wm = pd.read_csv('https://elimintz.github.io/women_majors.csv').round(2)

def grid_test():
    wp = jp.WebPage()
    html=wm.style.format(formatter="{:.5f}").background_gradient(axis=0, cmap='bwr').highlight_max(axis=0, color="purple").highlight_min(axis=0, color="green")._repr_html_()
    jp.parse_html(html, a=wp)
    return wp

jp.justpy(grid_test)

```

Is it possible to make the styler work with ag-grid?  So I like the look and feel but still want the sorting, filtering etc provided by Justpy ag-grid integration.

**Comment by elimintz** [comment]
What you would need to do is take the CSS classes or styles created by the Styler and apply them to the ag-grid cells. Another way is to take the pandas Styler source code and modify it to create an ag-grid definition instead of html.
