### ISSUE TITLE
Use of JustPy as a GUI framework for desktop applications made using Python

### ISSUE THREAD

**Issue by AgarwalPragy** [elimintz/justpy#35]
Since the client events are send to the server for processing, JustPy doesn't seem like a framework which can scale.

Building GUI applications in the browser is where JustPy shines. Unlike other frameworks like Qt which give you only a watered-down version of a web browser and painful APIs and ugly components, JustPy allows you to use the full power of CSS and JS.

Also, for desktop applications, since no request is being sent out of your system (server is on localhost), it is secure and fast!

If JustPy is remodeled/advertized as a GUI framework for Python applications instead of as a webserver, it can gain a lot of traction! :)

**Comment by elimintz** [comment]
That is an interesting suggestion, thank you. I agree that it is a good idea to emphasize the GUI aspect of JustPy more.

(I think JustPy should scale quite well but that is another discussion)
