### ISSUE TITLE
runtime errors in event handling is silent

### ISSUE THREAD

**Issue by cmungall** [elimintz/justpy#358]
To replicate, take Example 1 from https://justpy.io/tutorial/handling_events/ and add a line that causes a runtime error. I added two print statements around for debugging:

```python
import justpy as jp

def button_click(self, msg):
    print('button is clicked...')
    self.TYPO_num_clicked += 1  ## this causes runtime error
    print('this line is never reached...')
    self.message.text = f'{self.text} clicked. Number of clicks: {self.num_clicked}'
    self.set_class('bg-red-500')
    self.set_class('bg-red-700', 'hover')

def event_demo():
    number_of_buttons = 25
    wp = jp.WebPage()
    button_div = jp.Div(classes='flex m-4 flex-wrap', a=wp)
    button_classes = 'w-32 mr-2 mb-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full'
    message = jp.Div(text='No button clicked yet', classes='text-2xl border m-4 p-2', a=wp)
    for i in range(1, number_of_buttons + 1):
        b = jp.Button(text=f'Button {i}', a=button_div, classes=button_classes, click=button_click)
        b.message = message
        b.num_clicked = 0
    return wp 

jp.justpy(event_demo)
```

Running and selecting buttons gets as far as the first line, but no further. No indication of error on either server console or in browser. This is the output:

```
$ python test.py
JustPy ready to go on http://127.0.0.1:8000
button is clicked...
button is clicked...
```

This can make debugging applications challenging!

justpy version: 0.2.3

System:

Darwin MacBook-Air-7.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

**Comment by elimintz** [comment]
If you set the CRASH configuration variable to True, the program will not be silent.
https://justpy.io/reference/configuration/

**Comment by cmungall** [comment]
Thank you for the prompt response, and thank you for the wonderful framework!

Maybe this config could be made more prominent - perhaps a tip at the bottom of the events page?

**Comment by sandeep-gh** [comment]
concur with @cmungall . I thought uvicorn was controlling this behaviour and couldn't find any quickfixes so have been resorting to inserting try-catch when needed. Glad to know about this option.
