### ISSUE TITLE
Signature Pad Component

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#36]
One of the apps I'm replacing with JustPy requires a signature pad component. I noticed that there is already a Vue Signature Pad Component (https://github.com/neighborhood999/vue-signature-pad). Is this something you would be interested in having within the JustPy framework?

**Comment by elimintz** [comment]
Yes, that would be a good component to have. I have been looking for a component to use as an example in which you need to develop both the Python side and the JavaScript side and document the process. Would you like to give it a go or would you like me to do it? If you take on the project I would be of course happy to help at each step.

It would be simpler to write the JustPy vue component using  https://github.com/szimek/signature_pad directly instead of using the vue component based on it.

**Comment by knoxvilledatabase** [comment]
To be honest, I Reactjs experience but zero Vue experience at all. I would need to spend some time getting familiar with Vue and I would love to learn how to create JustPy components.

**Comment by elimintz** [comment]
Ok, I will take a stab at it over the next couple of weeks.

**Comment by knoxvilledatabase** [comment]
I don't mind taking a stab at it myself. I guess the parts I need to get familiar with is how your are putting the javascript on the page through python then how you are transferring the signature through the websocket to python. Does that sound right?

**Comment by knoxvilledatabase** [comment]
Now, I just need to figure out how to get the signature to python over the websocket, right? 

![Screen Shot 2020-03-15 at 9 46 06 AM](https://user-images.githubusercontent.com/2231079/76702782-f20e9b00-66a2-11ea-996d-4fca80ee50e8.png)

`class Canvas(Div):`
  `    html_tag = 'canvas'`

`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        self.width = 200`
`        self.height = 400`
`        self.id = "signature-pad"`
`        self.classes ="signature-pad"`
`        self.style = """`
`            position: absolute;`
`            left: 0;`
`            top: 0;`
`            width:400px;`
`            height:200px;`
`            background-color: white;`
`            border: 1px solid;`
`        """`

`class SignaturePad(jp.Div):`

`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        wrapper_style = """`
`            position:relative;`
`            width:400px;`
`            height:200px;`
`            -moz-user-select: none;`
`            -webkit-user-select:none;`
`            -ms-user-select:none;`
`            user-select:none;`
`        """`
`        wrapper = Div(style=wrapper_style, a=self)`
`        Canvas(a=wrapper)`
`        buttons_div = Div(a=self, style='margin-top:5px')`
`        jp.QBtn(`
`            text="SAVE", `
`            id="save-png", `
`            unelevated=True, `
`            style='margin-right:5px', `
`            a=buttons_div`
`        )`
`        jp.QBtn(`
`            text='CLEAR',`
`            id='clear',`
`            unelevated=True,`
`            style='margin-right:5px',`
`            a=buttons_div``
`        )`

**Comment by elimintz** [comment]
Very nice! You are basically there. I will play with it this week and add the communication part.

**Comment by knoxvilledatabase** [comment]
Thanks! What would be the best tutorial to learn how to setup that communication?

**Comment by elimintz** [comment]
There is no tutorial yet unfortunately. I need to write it.

**Comment by knoxvilledatabase** [comment]
You're cutting edge! I went through all of the Starlette docs and couldn't find anything on it.

**Comment by elimintz** [comment]
I have a working component but I haven't tested it extensively.

This is the Python part with an example of how to use it:


    
    import justpy as jp
    class SignaturePad(jp.JustpyBaseComponent):
    
        vue_type = 'signaturepad'
    
        def __init__(self, **kwargs):
    
            self.options = jp.Dict()
            self.classes = ''
            self.style = ''
            self.width = 400
            self.height = 200
            self.clear = False
            self.show = True
            self.event_propagation = True
            self.pages = {}
            kwargs['temp'] = False  # Force an id to be assigned to pad
            super().__init__(**kwargs)
            for k, v in kwargs.items():
                self.__setattr__(k, v)
            self.allowed_events = ['onEnd', 'onBegin']
            for e in self.allowed_events:
                for prefix in ['', 'on', 'on_']:
                    if prefix + e in kwargs.keys():
                        fn = kwargs[prefix + e]
                        if isinstance(fn, str):
                            fn_string = f'def oneliner{self.id}(self, msg):\n {fn}'
                            exec(fn_string)
                            self.on(e, locals()[f'oneliner{self.id}'])
                        else:
                            self.on(e, fn)
                        break
            if type(self.options) != jp.Dict:
                self.options = jp.Dict(self.options)
            for com in ['a', 'add_to']:
                if com in kwargs.keys():
                    kwargs[com].add_component(self)
    
        def add_to_page(self, wp: jp.WebPage):
            wp.add_component(self)
    
        def react(self, data):
            pass
    
    
        def convert_object_to_dict(self):
            d = {}
            d['vue_type'] = self.vue_type
            d['id'] = self.id
            d['show'] = self.show
            d['classes'] = self.classes
            d['style'] = self.style
            d['event_propagation'] = self.event_propagation
            d['def'] = self.options
            d['events'] = self.events
            d['width'] = self.width
            d['height'] = self.height
            d['clear'] = self.clear
            d['options'] = self.options
            return d
    
    
    def my_end(self, msg):
        print(msg)
        self.data = msg.data
    
    async def clear_pad(self, msg):
        self.pad.clear = True
        await msg.page.update()
        self.pad.clear = False
        return True
    
    
    def pad_test():
        wp = jp.WebPage()
        pad = SignaturePad(a=wp, style = 'background-color: white; border: 1px solid;', classes='m-2', onEnd=my_end)
        pad.options = {'penColor': 'blue'}
        clear_btn = jp.Button(text='Clear Pad', classes=jp.Styles.button_simple + ' m-2', a=wp, click=clear_pad)
        clear_btn.pad = pad
        return wp
    
    jp.justpy(pad_test)

JavaScript in next comment

**Comment by elimintz** [comment]
And this is the Vue component. Add it to the body.

    var signature_pads = {};
    Vue.component('signaturepad', {
        template:
            `<canvas  v-bind:id="jp_props.id" :class="jp_props.classes"  :style="jp_props.style" :width="jp_props.width" height="jp_props.height"></canvas>`,
        methods: {
            pad_change() {
                var id = this.$props.jp_props.id.toString();
                var canvas = document.getElementById(id);
                var signaturePad = new SignaturePad(canvas, this.$props.jp_props.options);
                signature_pads[id] = signaturePad;
                var events = this.$props.jp_props.events;
                var props = this.$props;

                function onEnd() {
                    if (events.includes('onEnd')) {
                        var data = signaturePad.toDataURL('image/png');
                        var point_data = signaturePad.toData();
                        var e = {
                            'event_type': 'onEnd',
                            'id': props.jp_props.id,
                            'class_name': props.jp_props.class_name,
                            'html_tag': props.jp_props.html_tag,
                            'vue_type': props.jp_props.vue_type,
                            'page_id': page_id,
                            'websocket_id': websocket_id,
                            'data': data,
                            'point_data': point_data
                        };
                        send_to_server(e, 'event');
                    }
                }

                signaturePad.onEnd = onEnd;

            }
        },
        mounted() {
            this.pad_change();
        },
        updated() {

            if (this.$props.jp_props.clear) {
                signature_pads[this.$props.jp_props.id.toString()].clear();
            }
        },
        props: {
            jp_props: Object
        }
    });

**Comment by knoxvilledatabase** [comment]
Wow!!! Very impressive! I will test this over the next few days. Thanks for working on this!

**Comment by knoxvilledatabase** [comment]
Worked like a charm, thank you!

**Comment by knoxvilledatabase** [comment]
Would this be something you would want to include on the next release?

**Comment by elimintz** [comment]
In a sense it is part of the new release (0.0.9). Please take a look at: https://justpy.io/tutorial/advanced_components/

So now you can put the JavaScript file in the components directory and you are good to go.

Thanks again for the great example!
