### ISSUE TITLE
First justpy Exe distributable ... not working

### ISSUE THREAD

**Issue by series0** [elimintz/justpy#361]
My VS Code running from the py file is fine but the dist exe gets this:
(admittedly unfamiliar with the pyinstaller link process)

![image](https://user-images.githubusercontent.com/97316990/157132971-ee084020-daa9-449a-8bea-aef1d421c67f.png)

**Comment by series0** [comment]
What supporting filesystem resources have to be distributed with an exe made from the py file?

**Comment by fx-991ES** [comment]
@series0 you may have already had this fixed but I had a similar issue when using pyinstaller and fixed it by adding the argument `--collect-all justpy` [link to docs](https://pyinstaller.readthedocs.io/en/stable/usage.html#cmdoption-collect-all). The issue I saw was that the templates folder was not being built into the exe by pyinstaller. This argument forces inclusion of all files/folders for a given module name.
