### ISSUE TITLE
Mixed up i and j

### ISSUE THREAD

**Issue by falkoschindler** [elimintz/justpy#365]
Here you fixed `j` in one place but forgot the other one:

https://github.com/elimintz/justpy/commit/4a6364435700f03d96355c05fd5aa812ce4ad33c#diff-4356faa5b78e23b18804b3263ab6e1d1d3f640c9be9f272da141e7a4c76bac68R28

The condition `i < ...` is still wrong:

```
for (let j = 0; i < this.jp_props.attrs[evaluated_prop].length; j++) {
```

**Comment by elimintz** [comment]
Thank you, will make the change.

**Comment by WolfgangFahl** [comment]
is this actually fixed by now ? Since this isn't a PR and the bug reference is not clear I suggest to invite @falkoschindler and let him check.
