### ISSUE TITLE
Problems showing and hiding popup with color picker

### ISSUE THREAD

**Issue by falkoschindler** [elimintz/justpy#368]
I followed the example at https://justpy.io/quasar_tutorial/QColor/ to implement a color picker element for [NiceGUI](https://nicegui.io/). But I struggle with showing and hiding the popup on demand.

**Problem 1:** The following code contains two popups, one for the input field and one standalone which is triggered via show and hide buttons. But when clicking the icon in the input field, both popups are shown. I tried to distinguish them as cleanly as possible with different names - in case the name_dict is mixing them up -, but without success.

**Problem 2:** Both buttons seem to toggle the second popup. So the "show" button hides the popup if it is already visible and vice versa. This doesn't make sense to me.

```python3
import justpy as jp

def color_test():
    wp = jp.QuasarPage()

    in1 = jp.QInput(filled=True, style='width:10em', a=wp)
    j1 = jp.parse_html("""
        <q-icon name="colorize" class="cursor-pointer">
            <q-popup-proxy transition-show="scale" transition-hide="scale" name="popup1">
                <q-color name="color_input1"/>
            </q-popup-proxy>
        </q-icon>
        """)
    in1.add_scoped_slot('append', j1)
    j1.name_dict['color_input1'].on('change', lambda sender, _: print(sender.value))

    j2 = jp.parse_html("""
        <q-popup-proxy transition-show="scale" transition-hide="scale" name="popup2">
            <q-color name="color_input2"/>
        </q-popup-proxy>
        """, a=wp)
    j2.name_dict['color_input2'].on('change', lambda sender, _: print(sender.value))

    def show(): j2.name_dict['popup2'].value = True
    def hide(): j2.name_dict['popup2'].value = False
    jp.Button(text='Show', a=wp, click=lambda *_: show())
    jp.Button(text='Hide', a=wp, click=lambda *_: hide())

    return wp

jp.justpy(color_test)
```

I guess it somehow has to do with changing focus. When clicking on "show" while the popup is visible, it looses focus and, thus, closes. But why can "hide" open it?
And it seems that focussing the input element opens the second popup. This would explain why clicking the icon (which focusses the input) opens both popups. But how can the second popup depend on the input element?

Any help in understanding and improving this behavior is very much appreciated!

**Comment by elimintz** [comment]
This is indeed very weird. I'll take a close look at this next week.

**Comment by falkoschindler** [comment]
Hi Eli, any update on the issue with showing/hiding color picker popups?
I'm still very much looking forward to integrating these elements in our framework for an ongoing project.

**Comment by elimintz** [comment]
Not yet. Unfortunately, I won't have time to look at it this week.

**Comment by falkoschindler** [comment]
It seems like the issue is caused by Quasar's default behavior of triggering popups from parent events. I noticed in a different context that menus would open when clicking next to them.

This can be avoided using the "no-parent-event" prop. In the example above I need to change both popup proxies to

```html
<q-popup-proxy ... no-parent-event>
```

Now we need an explicit trigger for the first popup, e.g.

```python
def show_j1(): j1.name_dict['popup1'].value = True
j1.name_dict['colorize'].on('click', lambda sender, _: show_j1())
```

Although the default behavior is a bit weird, adding `no-parent-event` solves this issue in my point of view.
