### ISSUE TITLE
WebPage.loop, JustPy.loop are now redundant

### ISSUE THREAD

**Issue by AgarwalPragy** [elimintz/justpy#37]
**justpy/justpy.py**

```python
@app.on_event('startup')
async def justpy_startup():
    WebPage.loop = asyncio.get_event_loop()
    JustPy.loop = WebPage.loop
```

Now that `asyncio.get_event_loop()` is guaranteed to always give the currently running event loop (if one is running), we no longer need to save these values.

This also allows us to elegantly execute async functions from sync functions if we do not care about the result immediately.

For example:
```python

def run_javascript(self, javascript_string: str) -> None:
    asyncio.get_event_loop().create_task(
        self.container_page.run_javascript(
            javascript_string=javascript_string
        )
    )

```

**Comment by elimintz** [comment]
Thanks, you are right the loop does not need to be saved. This is just for convenience now.
 
Glad to see you are using the `run_javascript` method, let me know if you have any other features you would like to see.
