### ISSUE TITLE
Setting focus example not working

### ISSUE THREAD

**Issue by abhijitmamarde** [elimintz/justpy#40]
Hi There,

First of all great project/idea. Would love to get involve in it. Found today itself, so was trying to explore the examples and trying it out. While doing that notice the example from link: https://justpy.io/tutorial/input/ which basically shows how to handle the input events - focus in and focus out, setting the focus etc is not working.

Below is the exact program which I tried, and it does prints the lines where I suspected whether control is going or not. But still, on pressing the 'Enter' key the focus is not going to other input control. I checked on Chrome and Edge (I dont have other browser currently) and on both pressing Enter is not doing any action.

Let me know how I can help.

```python
import justpy as jp

def my_blur(self, msg):
        self.focus = False

def key_down(self, msg):
    # print(msg.key_data)
    key = msg.key_data.key
    if key=='Escape':
        self.value=''
        return
    if key=='Enter':
        self.focus = False
        try:
            print("This line prints!")
            next_to_focus = self.input_list[self.num + 1]
        except:
            next_to_focus = self.input_list[0]
        print("And this line too prints!")
        next_to_focus.focus = True
        return
    return True  # Don't update the page


def focus_test():
    wp = jp.WebPage()
    d = jp.Div(classes='flex flex-col  m-2', a=wp, style='width: 600 px')
    input_list = []
    number_of_fields = 5
    for i in range(1, number_of_fields + 1):
        label = jp.Label( a=d, classes='m-2 p-2')
        jp.Span(text=f'Field {i}', a=label)
        in1 = jp.Input(classes=jp.Styles.input_classes, placeholder=f'{i} Type here', a=label, keydown=key_down, spellcheck="false")
        in1.on('blur', my_blur)
        in1.input_list = input_list
        in1.num = i - 1
        input_list.append(in1)
    return wp

jp.justpy(focus_test)
```

**Comment by elimintz** [comment]
Sorry, my bad. I changed `focus` to `set_focus` and did not update the example.
Please see below the program that works.


    import justpy as jp
    
    def my_blur(self, msg):
            self.set_focus = False
    
    def key_down(self, msg):
        print(msg.key_data)
        key = msg.key_data.key
        if key=='Escape':
            self.value=''
            return
        if key=='Enter':
            self.set_focus = False
            try:
                next_to_focus = self.input_list[self.num + 1]
            except:
                next_to_focus = self.input_list[0]
            next_to_focus.set_focus = True
            return
        return True  # Don't update the page
    
    
    def focus_test():
        wp = jp.WebPage()
        d = jp.Div(classes='flex flex-col  m-2', a=wp, style='width: 600 px')
        input_list = []
        number_of_fields = 5
        for i in range(1, number_of_fields + 1):
            label = jp.Label( a=d, classes='m-2 p-2')
            jp.Span(text=f'Field {i}', a=label)
            in1 = jp.Input(classes=jp.Styles.input_classes, placeholder=f'{i} Type here', a=label, keydown=key_down, spellcheck="false")
            in1.on('blur', my_blur)
            in1.input_list = input_list
            in1.num = i - 1
            input_list.append(in1)
        return wp
    
    jp.justpy(focus_test)
