### ISSUE TITLE
How to reduce UI lag

### ISSUE THREAD

**Issue by jannekeskitalo** [elimintz/justpy#43]
Hi

I have deployed a simple Justpy app to Azure App Service. Locally it works great, but in Azure there is significant lag when using input fields. If I type something into a field, characters get erased, selections get reverted etc. I suspect this is due to network lag. The clicked UI components also get this red thin border around them which doesn't happen on local host.

I had to revert to AJAX as the App Service websocket support doesn't seem to work with Justpy.

My app is an Eventhubs test data generator and it uses Justpy functionality to start a background process to generate events. As said, it works beautifully on my local machine.

Are there any tweaks to disable some AJAX functionality to diminish some of the lag? I tried setting "debounce" to 3000 on all input components, but it didn't really help.

**Comment by elimintz** [comment]
Hi,

I am not familiar with Azure App Service. 

Could you please check your browser's dev tools for the network timings for the communication?

Is there an option on Azure to configure a simple Linux instance and use it? This is what I do using Digital Ocean.

Also, to simulate latency on the local host you can set the `LATENCY` variable in justpy.env
https://justpy.io/tutorial/configuration/

Please let me know how things work out for you.

**Comment by jannekeskitalo** [comment]
I had to jump to another task, but I will test this later. I could deploy this to a dedicated VM like you say, but Azure App Services offers some useful features like integrated authentication etc.

In general, do you think network latency can cause weird behaviour in Justpy javacsript components or is this just related to my code and the behaviour of the App Service web gateway?

I really like the Justpy approach, because I'm a database and backend engineer and just need to build some simple UIs from time to time.

**Comment by elimintz** [comment]
It depends on the application, but for most applications with typical latency, there is no problem. The best way to find out is to set the LATENCY variable locally and see if it makes a difference.
