### ISSUE TITLE
QInput misses loading property?!

### ISSUE THREAD

**Issue by tmelgo** [elimintz/justpy#458]
Hi, in QInput there is no "loading" property in the prop_list. When I add it, I can use it.
Has it been left out of the prop_list intentionally?
Kind regards.

**Comment by elimintz** [comment]
The loading property was probably added to QInput after the last version of justpy came out. What you are doing is exactly the right way to do it. 
@WolfgangFahl we should add 'loading' to the list here for the next version:
https://github.com/elimintz/justpy/blob/master/justpy/quasarcomponents.py#L134
