### ISSUE TITLE
Event handlers exceptions are silent

### ISSUE THREAD

**Issue by jandeneweth** [elimintz/justpy#46]
When event handler methods fail, they seem to fail silently. No exceptions are raised to the user, the stdout or stderr of the application, nor the browser log. Obviously I could decorate each method to log errors, but I'd think this is more appropriate on framework level. Not sure if oversight? 

Reproduction script: 'After' is not printed, nor is tthe AttributeError reported anywhere

```python
import justpy as jp

def main_route():
    wp = jp.WebPage()
    input_elem = jp.Input(a=wp, type='number', value=5)
    input_elem.on('input', faulty_handler)
    return wp

def faulty_handler(elem, msg):
    print("Before")
    _ = elem.invalid_attribute
    print("After")

jp.justpy(main_route)
```

**Comment by elimintz** [comment]
Good point. In the new version I will release this week, if you set `LOGGING_LEVEL = DEBUG` in justpy.env you will see the full trace information. With the version you have, if you make this change, you will see that the handler is being attempted to run but won't get the full trace info.
