### ISSUE TITLE
Table body-cell-slot

### ISSUE THREAD

**Issue by wilsonpuddnhead** [elimintz/justpy#47]
Hi, 

Thank you for this amazing module!

I was wondering if you can provide an example of a Qtable with a body-cell-slot like the example here: https://quasar.dev/vue-components/table#Example--Body-cell-%5Bname%5D-slot

What I would really like to do is add some buttons at the end of a table row, but I can't seem to figure out how to use these slots. It looks like part of the problem is that there isn't a Qtr and Qtd classes in justpy? But it's likely I'm just missing something very basic. 

Thanks!

**Comment by elimintz** [comment]
Hi,

Thank you!

You are not missing anything. There are two issues here that I will resolve in future versions.

1) There are not QTr and QTd classes
2) Slots cannot be parameterized meaning that you can put an element in a slot, but you cannot have slots that accepts parameters like in this example.

What I can suggest is using the AgGrid component. It is more versatile though the learning curve is a more steep. It also comes with a material theme so fits quite well on a Quasar page.

**Comment by wilsonpuddnhead** [comment]
Thank you! I will look into AgGrid.
