### ISSUE TITLE
Is there a way to update Table values?

### ISSUE THREAD

**Issue by tomsem** [elimintz/justpy#48]
I'm trying to combine a couple of the examples in the Tutorial: the 'Clock' example in Pushing Data to Web Pages with the Table component example in Creating Your Own Components. In other words, I want to present a table and update the values periodically, so as to have a sort of dashboard of some data I want to display. 

It's not working: I am trying to update the .values property of the table (and then calling update() on the Table instance) but the browser does not update. If I refresh the browser, it has appended the new data to the old data. If call WebPage.update() instead of Table.update() then it is same as the manual refresh browser and again I see the table expand with each update.

I'm just getting started with this so I could use a little guidance. I'm really impressed with the concept and hope to use it for a project I am working on. Thanks.

**Comment by elimintz** [comment]
Thanks for using the framework.
Below is the simple example you requested. 

In QTable you need to update its data attribute to get what you need.
There are many features in the QTable component which are covered here: https://quasar.dev/vue-

Let me know if something is not clear.

The example:

    import justpy as jp
    import asyncio
    
    columns = [{'field': 'first', 'label': 'First Col'}, {'field': 'second', 'label': 'Second Col'}, {'field': 'third', 'label': 'Third Col'}, ]
    data = [{'first': 1, 'second': 2, 'third': 3}]
    
    wp = jp.QuasarPage(delete_flag=False)
    d = jp.Div(classes='q-pa-md', a=wp, style='height: 800px')
    table = jp.QTable(title='Update Example', data=data, columns=columns, a=d, dense=True, pagination={'rowsPerPage': 10})
    counter = 1
    
    async def table_counter():
        global counter
        while True:
            print(counter)
            counter += 1
            table.data[0]['first'] = counter
            table.data.append({'first': 1*counter, 'second': 2*counter, 'third': 3*counter})
            jp.run_task(wp.update())
            await asyncio.sleep(3)
    
    async def table_init():
        jp.run_task(table_counter())
    
   
    def table_test():
        return wp
    
    jp.justpy(table_test, startup=table_init)

**Comment by tomsem** [comment]
Great, that's very helpful!
