### ISSUE TITLE
Websocket Auto-Reconnect After Code Changes

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#49]
Absolutely loving JustPy!!! About to go live with my first justpy application using apache and gunicorn and I'm curious if you know of a way where I can update my application without my clients losing the websocket connection?

**Comment by elimintz** [comment]
Thank you again!

Unfortunately, I don't think there is a way to keep websockets alive between restarts of the server.
I will look into this further.

**Comment by knoxvilledatabase** [comment]
Would it be possible to fire a QDialog prompting the user the refresh if the websocket is broken because of a code change?

**Comment by elimintz** [comment]
Thank you for this suggestion. This would be a great idea to implement.
I'll try getting it into the next version. 
As a first stab at this, would it be ok just to display a message asking the user to reload the page?

**Comment by knoxvilledatabase** [comment]
Absolutely!

**Comment by knoxvilledatabase** [comment]
This worked perfectly with the 0.1.1 version, thank you! The only thing that would set it over the top is having the ability to customize the reload alert to match the theme of the website, but not sure if this is even possible.

**Comment by elimintz** [comment]
It is possible, and will be in one of the next versions.
Thanks again for the great suggestion.
