### ISSUE TITLE
[question/feature request] Accessing MouseEvent and other generic Event information 

### ISSUE THREAD

**Issue by erdmann** [elimintz/justpy#5]
Hi,

I'm interested in accessing the full [MouseEvent](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent) information for a mouse click event.

What is the canonical way to do that?  I've poked around inside the `msg` parameter from the general event template, but it appears to be missing from there (or I'm overlooking it).

Thanks in advance, and many thanks for making justpy!

**Comment by elimintz** [comment]
Which additional information from the MouseEvent do you need?

**Comment by erdmann** [comment]
The mouse coordinates of various flavors as well as the keyboard modifiers.  Specifically, these:

- MouseEvent.altKey
- MouseEvent.button
- MouseEvent.buttons
- MouseEvent.clientX
- MouseEvent.clientY
- MouseEvent.ctrlKey
- MouseEvent.metaKey
- MouseEvent.movementX
- MouseEvent.movementY
- MouseEvent.offsetX
- MouseEvent.offsetY
- MouseEvent.pageX
- MouseEvent.pageY
- MouseEvent.screenX
- MouseEvent.screenY
- MouseEvent.shiftKey
- MouseEvent.which

**Comment by elimintz** [comment]
Ok, I see.  I didn't want to make `msg` too big adding information that most people would not use.
I will add in the upcoming new version an option to request more information per event for an element.

**Comment by fxnut** [comment]
Hi Eli,
I figured out how to get "additional_properties" working, but just wanted to flag that I couldn't see it mentioned in the documentation yet: [https://justpy.io/#/tutorial/handling_events](https://justpy.io/#/tutorial/handling_events)

**Comment by elimintz** [comment]
Check out https://justpy.io/tutorial/handling_events/#additional-event-properties

**Comment by fxnut** [comment]
Great, thanks!
