### ISSUE TITLE
Make .parse_html more useful?

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#53]
Hi 

I find the parse_html method useful for one time conversion of existing html  to code. But even then, it requires quite some work with adding id's and then using name_dict to hook up event handlers. Would it be possible to parse event handlers (like @click) in the html and hook them automatically to event handlers in code?

'''
html='<div @click="do_something/>'

def so_something(...):
   ...

c = jp.parse_html(html)

'''

**Comment by elimintz** [comment]
Hi,

That is a good idea. I have been thinking about this also. I will add in a future version.

**Comment by mjmare** [comment]
Cool! Thx
