### ISSUE TITLE
Enable Fontawesome Pro?

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#54]
Is it possible to enable Fontawesome Pro if one has a license?

**Comment by elimintz** [comment]
Yes. You need to insert the appropriate link to the CDN using  the `head_html` attribute:
https://justpy.io/reference/webpage/#head_html-and-body_html


This is how it would look with the regular fontawesome if it did not come pre-loaded:

    wp.head_html = '<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css"/>'

Just substitute the  correct link. 
Let me know if this works for you.

**Comment by mjmare** [comment]
That was a useful pointer. Note that the FA Pro CDN version is being sunsetted. The current way to go is something called Kits.

Here are the steps to add Fontawesome Pro to Justpy. 
- Log into your FA account
- Click on the avatar (topright corner), click _Kits_
- Click on "Create your first kit"
- Copy the generated code line that is displayed near the top. Something like: 
```<script src="https://kit.fontawesome.com/b2a3c01b31.js" crossorigin="anonymous"></script>``` The code is unique for each kit (and thus user).  
- Paste into your Justpy code:
```
 wp.head_html ='<script src="https://kit.fontawesome.com/b2a3c01b31.js" crossorigin="anonymous"></script>'
```

Note that you can change some settings of the kit, like switching from web fonts to SVG. However the latter did not work for me (did not investigate).
