### ISSUE TITLE
wp.head_html winds up in body

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#56]
```
    wp = jp.QuasarPage(data={'left': False})
    wp.head_html = '<script>console.log("Hello there from head");</script>'
```
becomes:
<img width="625" alt="Screenshot 2020-04-22 at 23 52 06" src="https://user-images.githubusercontent.com/1711378/80037747-7d761a00-84f4-11ea-9585-3e631590b5a9.png">

IOW it gets inserted in the body.
Also not the STYLE section in the body. Shouldn't that be inserted in the HEAD as well?

**Comment by elimintz** [comment]
I am using the following example and it is inserted in the head correctly:

    import justpy as jp
    
    def test_demo():
        wp = jp.QuasarPage(data={'left': False})
        wp.head_html = '<script>console.log("Hello there from head");</script>'
        jp.Div(text='hello', a=wp)
        return wp
    
    jp.justpy(test_demo)

Could you please paste the whole example that is not working for you?

**Comment by mjmare** [comment]
Just checked: justpy 0.0.8 has the bug, but everything is OK in 0.09. 
Also the rogue <style> section is gone. 

Thank you!
