### ISSUE TITLE
How to broadcast wp.update() to all clients on a certain page?

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#59]
We would like to request all clients to reload a page when a user makes a specific change on our database but we don't want to put the entire page in a shared component because it's a lot of data. 

Would you have any ideas for how to solve this?

**Comment by elimintz** [comment]
Could you elaborate a little more? In what sense is it too much data? You need to create a new page anyway, so I am not clear why it matters if it is shared or not.

Would something like in the simple message board example ( https://justpy.io/tutorial/pushing_data/#simple-message-board ) where there is just a shared div solve your problem?

**Comment by knoxvilledatabase** [comment]
We tried the message board example first and noticed that every time we sent a new message it was re-sending all of the messages over the websocket which is fine for a message board.

![Screen Shot 2020-04-27 at 6 44 37 AM](https://user-images.githubusercontent.com/2231079/80363688-96fbc680-8852-11ea-9a03-092b7aba578d.png)

However, the page we are trying to use this on has images, thumbnails, links to pdf downloads, modal popups,  etc (like 10Mb worth of images and data on the page). Therefore, when we put it inside the shared_div and every time someone makes a change was taking a long time to send that 10Mb plus over the websocket to update the page and some really weird behavior like duplicates of stuff. 

We were thinking about putting a small shared div on the page and if something inside of it changed then basically have it call the python function that would initiate a reload of the entire page but couldn't figure out how to make that happen.

**Comment by knoxvilledatabase** [comment]
Another idea that we had was to use the shared clock scenario but, using the code example above, we would need the startup=clock_init to live inside the message demo so we would have access to wp.

**Comment by elimintz** [comment]
I'll study your code and also modify the clock example and post it soon. In the meantime here is an example of how to get a page to reload when a button is clicked using the `run_javascript` method of WebPage:

    import justpy as jp
    
    async def my_click(self, msg):
        await msg.page.run_javascript("location.reload()")
        return True
    
    def javascript_test():
        wp = jp.WebPage()
        d = jp.Div(a=wp, classes='m-2')
        b = jp.Button(text='Run Script', a=d, classes=jp.Styles.button_simple, click=my_click)
        return wp
    
    jp.justpy(javascript_test)

**Comment by elimintz** [comment]
Please see below the modified clock example in which the page is reloaded every few seconds.

The function clock_init now starts two tasks. The first one updates the text of the clock div but does not update the pages.

The second task checks every 5 seconds if the clock div text has changed, and if so, reloads the page. 

Please let me know if this works for you.

    import justpy as jp
    import time
    import asyncio
    
    wp = jp.WebPage(delete_flag=False)
    clock_div = jp.Span(text='Loading...', classes='text-5xl m-1 p-1 bg-gray-300 font-mono', a=wp)
    
    async def clock_counter():
        while True:
            clock_div.text = time.strftime("%a, %d %b %Y, %H:%M:%S", time.localtime())
            await asyncio.sleep(1)
    
    async def check_if_changed():
        clock_div_text = clock_div.text
        await asyncio.sleep(1)
        while True:
            if clock_div.text != clock_div_text:
                jp.run_task(wp.run_javascript("location.reload()"))
                clock_div_text = clock_div.text
            await asyncio.sleep(5)
    
    
    async def clock_init():
        jp.run_task(clock_counter())
        jp.run_task(check_if_changed())
    
    async def clock_test():
        return wp
    
    jp.justpy(clock_test, startup=clock_init)

**Comment by knoxvilledatabase** [comment]
I'm wonder if I put this a different way if it would make more sense, please forgive me if it doesn't. 

For simplicity sake, say I wanted to create a single page facebook like app where there was a wall/feed page, a messages page and a toolbar at the top to let me know when new messages come in. While I'm sitting idle on the wall/feed page a new message comes in and the notification icon at the top of the page changes to let me know there is a new message. 

Of course, when I submit a new feed message I could query something to see if there are any new messages. However, what I'm trying to accomplish is for the notification icon to change at the top even while I'm idle. Here is a code sample:

`import justpy as jp`
` `
`shared_messaging_div = jp.Div(classes='m-2 h-1/2 border overflow-auto', delete_flag=False)`
`shared_feed_div = jp.Div(classes='m-2 h-1/2 border overflow-auto', delete_flag=False)`
` `
`class Messages(jp.QDiv):`
` `
`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        panel_body = jp.QDiv(a=self)`
`        table = jp.Table(a=panel_body, text='Messages')`
`        tr = jp.Tr(a=table)`
`        td1 = jp.Td(a=tr)`
`        td2 = jp.Td(a=tr)`
`        self.message = jp.Textarea(placeholder='Enter message here', a=td1, debounce=500)`
`        jp.QBtn(`
`            a=td2,`
`            label='Send',`
`            color='positive',`
`            text_color='white',`
`            unelevated=True,`
`            classes="full-width",`
`            size='lg',`
`            click=self.send_message,`
`        )`
`  `
`    async def send_message(self, target, msg):`
`        await msg.page.run_javascript('console.log("hello")')`
`        if self.message.value:`
`            d = jp.Div(text=self.message.value)`
`            shared_messaging_div.add_component(d, 0)`
`            self.message.value = ''`
`            await shared_messaging_div.update()`
`  `
`class Feed(jp.QDiv):`
`  `
`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        panel_body = jp.QDiv(a=self, text='Feed')`
`        table = jp.Table(a=panel_body)`
`        tr = jp.Tr(a=table)`
`        td1 = jp.Td(a=tr)`
`        td2 = jp.Td(a=tr)`
`  `
`        self.message = jp.Textarea(placeholder='Whats on your mind?', a=td1, debounce=500)`
`        jp.QBtn(`
`            a=td2,`
`            label='Send',`
`            color='positive',`
`            text_color='white',`
`            unelevated=True,`
`            classes="full-width",`
`            size='lg',`
`            click=self.add_feed,`
`        )`

`    async def add_feed(self, target, msg):`
`        if self.message.value:`
`            d = jp.Div(text=self.message.value)`
`            shared_feed_div.add_component(d, 0)`
`            self.message.value = ''`
`            await shared_feed_div.update()`
`  `
`class DefaultLayout(jp.QuasarPage):`
`    template_file = 'quasar.html'`

`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        notification_div = jp.QDiv(a=self, text='Messages: 0')`
`        outer_div = jp.QDiv(a=self)`
`        table = jp.Table(a=outer_div)`
`        tr = jp.Tr(a=table)`
`        self.left_nav_td = jp.Td(a=tr, style='vertical-align:top')`
`        right_hand_content_td = jp.Td(a=tr, style='vertical-align:top;width:500px;height:500px')`
`        self.content = jp.QDiv(a=right_hand_content_td, style='margin-left:25px')`
`  `
`def messages_and_feed_app():`
`  `
`    def messages(self, msg):`
`        msg.page.content.delete_components()`
`        Messages(a=msg.page.content)`
`        msg.page.content.add(shared_messaging_div)`
`        shared_messaging_div.add_page(msg.page)`
`  `
`    def feed(self, msg):`
`        msg.page.content.delete_components()`
`        Feed(a=msg.page.content)`
`        msg.page.content.add(shared_feed_div)`
`        shared_feed_div.add_page(msg.page)`
`  `
`    wp = DefaultLayout()`
`  `
`    left_nav = jp.QDiv(a=wp.left_nav_td)`
`    jp.QBtn(`
`        a=left_nav,`
`        label='Messages',`
`        color='positive',`
`        text_color='white',`
`        unelevated=True,`
`        classes="full-width",`
`        style='margin-top:10px',`
`        click=messages,`
`    )`
`  `
`    jp.QBtn(`
`        a=left_nav,`
`        label='Feed',`
`        color='positive',`
`        text_color='white',`
`        unelevated=True,`
`        classes="full-width",`
`        style='margin-top:10px',`
`        click=feed,`
`    )`
`  `
`    class msg(object):`
`        page = wp`

`    messages(None, msg)`
`    return wp`


`jp.justpy(messages_and_feed_app)`

**Comment by elimintz** [comment]
Quick clarification: When you send a message, it will show up in the idle user's browsers also. Why not use a similar method to update the message counter?

**Comment by knoxvilledatabase** [comment]
So, I added a shared_notification_div for holding the notifications which both pages use. I update the shared_notification_div.text when adding a message. Works great on the browser where I added the message but doesn't update on the browser where I am on the feed page. 

![Screen Shot 2020-04-27 at 2 04 27 PM](https://user-images.githubusercontent.com/2231079/80404936-ed3b2a80-888f-11ea-9d5a-6d20177b1c2f.png)


`import justpy as jp`
` `
`shared_messaging_div = jp.Div(classes='m-2 h-1/2 border overflow-auto', delete_flag=False)`
`shared_feed_div = jp.Div(classes='m-2 h-1/2 border overflow-auto', delete_flag=False)`
`shared_notification_div = jp.QDiv(text='0')`
` `
`class Messages(jp.QDiv):`
` `
`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        panel_body = jp.QDiv(a=self)`
`        table = jp.Table(a=panel_body, text='Messages')`
`        tr = jp.Tr(a=table)`
`        td1 = jp.Td(a=tr)`
`        td2 = jp.Td(a=tr)`
`        self.message = jp.Textarea(placeholder='Enter message here', a=td1, debounce=500)`
`        jp.QBtn(`
`            a=td2,`
`            label='Send',`
`            color='positive',`
`            text_color='white',`
`            unelevated=True,`
`            classes="full-width",`
`            size='lg',`
`            click=self.send_message,`
`        )`
`  `
`    async def send_message(self, target, msg):`
`        await msg.page.run_javascript('console.log("hello")')`
`        if self.message.value:`
`            d = jp.Div(text=self.message.value)`
`            shared_messaging_div.add_component(d, 0)`
`            self.message.value = ''`
`            old_count = int(shared_notification_div.text)`
`            shared_notification_div.text = f"{old_count + 1}"`
`            await shared_notification_div.update()`
`            await shared_messaging_div.update()`
`            await msg.page.update()`
`  `
`class Feed(jp.QDiv):`
`  `
`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        panel_body = jp.QDiv(a=self, text='Feed')`
`        table = jp.Table(a=panel_body)`
`        tr = jp.Tr(a=table)`
`        td1 = jp.Td(a=tr)`
`        td2 = jp.Td(a=tr)`
`  `
`        self.message = jp.Textarea(placeholder='Whats on your mind?', a=td1, debounce=500)`
`        jp.QBtn(`
`            a=td2,`
`            label='Send',`
`            color='positive',`
`            text_color='white',`
`            unelevated=True,`
`            classes="full-width",`
`            size='lg',`
`            click=self.add_feed,`
`        )`

`    async def add_feed(self, target, msg):`
`        if self.message.value:`
`            d = jp.Div(text=self.message.value)`
`            shared_feed_div.add_component(d, 0)`
`            self.message.value = ''`
`            await shared_feed_div.update()`
`  `
`class DefaultLayout(jp.QuasarPage):`
`    template_file = 'quasar.html'`

`    def __init__(self, **kwargs):`
`        super().__init__(**kwargs)`
`        notification_div = jp.QDiv(a=self)`
`        notification_div.add(shared_notification_div)`
`        outer_div = jp.QDiv(a=self)`
`        table = jp.Table(a=outer_div)`
`        tr = jp.Tr(a=table)`
`        self.left_nav_td = jp.Td(a=tr, style='vertical-align:top')`
`        right_hand_content_td = jp.Td(a=tr, style='vertical-align:top;width:500px;height:500px')`
`        self.content = jp.QDiv(a=right_hand_content_td, style='margin-left:25px')`
`  `
`def messages_and_feed_app():`
`  `
`    def messages(self, msg):`
`        msg.page.content.delete_components()`
`        Messages(a=msg.page.content)`
`        msg.page.content.add(shared_messaging_div)`
`        shared_messaging_div.add_page(msg.page)`
`  `
`    def feed(self, msg):`
`        msg.page.content.delete_components()`
`        Feed(a=msg.page.content)`
`        msg.page.content.add(shared_feed_div)`
`        shared_feed_div.add_page(msg.page)`
`  `
`    wp = DefaultLayout()`
`  `
`    left_nav = jp.QDiv(a=wp.left_nav_td)`
`    jp.QBtn(`
`        a=left_nav,`
`        label='Messages',`
`        color='positive',`
`        text_color='white',`
`        unelevated=True,`
`        classes="full-width",`
`        style='margin-top:10px',`
`        click=messages,`
`    )`
`  `
`    jp.QBtn(`
`        a=left_nav,`
`        label='Feed',`
`        color='positive',`
`        text_color='white',`
`        unelevated=True,`
`        classes="full-width",`
`        style='margin-top:10px',`
`        click=feed,`
`    )`
`  `
`    class msg(object):`
`        page = wp`

`    messages(None, msg)`
`    return wp`


`jp.justpy(messages_and_feed_app)`

**Comment by elimintz** [comment]
Two things I changed and it looks like it is working.
First, you need to add `delete_flag=False` when you create `shared_notification_div`: 

    shared_notification_div = jp.QDiv(text='0', delete_flag=False)

Second, I added the line:

    shared_notification_div.add_page(self)

as the second line of DefaultLayout's `__init__` .
In this specific case it makes no difference but in general it would be better to have all the calls to the `add_page` of the shared components there when the page is created.

You can also remove the last line 

    await msg.page.update()

from the `send_message` method of `send_messages`. It is not needed since when an event handler returns None the page is updated automatically by the framework.

Let me know how this works for you.

I like the way you created a class for you default page that you can now re-use as a template in different projects.

**Comment by knoxvilledatabase** [comment]
That worked perfect for this example, thank you! I do love subclassing jp.QuasarPage, makes for some very cool, easily callable and customizable themes. I'm loving all of JustPy really! If I can just figure out how to integrate this auto update feature it will be absolutely perfect!

As a real world scenario, I'm running with apache and gunicorn with start_server=False and a lot of times I have processes running behind the scenes. For example, a customer gets an order via a pdf in an email, a python imap library will snag the pdf from the email, put it in the database with a png thumbnail then the imap library will need to add the thumbnail to the shared_div and shared_div.update() so the end users automatically receive the updated thumbnail.

Do you see any reason why I wouldn't be able to run commands in a python shell to update clients? 

For example, from a python shell:
`from my_app.layout import shared_notification_div`                                                                                                                                                                                                           
`shared_notification_div.text = 5`                                                                                                                                                                                              
`shared_notification_div.update()`

**Comment by elimintz** [comment]
How did you solve the auto update problem when you were developing with Django or is this a new issue?

Running from the command line may not work but there is another option. Create a specific route for the site only you know about and do the updates through it. So for example:

    @jp.SetRoute('/secret_route')
    async def update_shared_div(request):
        wp = jp.WebPage()
        value = request.query_params.get('value')
        if value:
            shared_notification_div.text = value
            jp.run_task(shared_notification_div.update())
            wp.add(jp.Div(text='Value is being updated'))
        else:
            wp.add(jp.Div(text='Value not provided'))
        return wp

Then you would initiate the update by going to the url:
`http://example.com/secret_route?value=5`

If this is not to your liking, I have other suggestions.

**Comment by knoxvilledatabase** [comment]
That is probably exactly what I was looking for! 

So, the way we solved this problem in the django/react (previous app framework), we created something similar to JustPy but not as powerful, that would take python code like this:

`Div(`
`     Span(text='Hello World'),`
`     Br(),
`     ReactJSSpinner()`
`     style='padding:25px',`
`)`

Serialize this to json through a RestAPI then through a nav click ReactJS would hit the API url and parse the html from json to layout the page. We could call ReactJS Components the same way.  This would allow us to only write Python (once all of the ReactJS components were built) and ReactJS would do all of the work without all of the constant transpiling. 

The way we solved the auto update issue is, we created a django model called Log and a Django channels websocket tied to Log changes. ReactJS would monitor for websocket messages for Log. If Log.model_name == the model_name within the url then ReactJS would re-render the page. Hopefully I explained that clearly enough. 

One other question, what if one user has a QDialog open from a shared_div and I update that shared_div, do you imagine it would close theQDialog?  If so, can you think of any way to pause the update while the QDialog is open?

**Comment by elimintz** [comment]
The value of the QDialog will revert to the value in the instance on the server. 

Can you move the QDialog out of the shared_div? The reason is that if a QDialog is shared, when it is opened and closed it generates an input event which updates it value on the server and so every user's dialog will be open if they load a page while the QDialog is open. Different users opening and closing the QDialog could cause unforeseen problems.

Alternatively, you should set the disable_events attribute of the QDialog to True if you don't care to track whether the QDialog is open or not. Then you could have it in a shared_div but it will still revert to the value you initially set it on update.

**Comment by knoxvilledatabase** [comment]
I could possibly move it out or just use a different page for editing, viewing images, downloading pdfs, etc. 

If you don't mind me asking you one more question: Lets say we expanded on the messaging app and there were 25 users and, for example, user23 sent a message to user14, user3 sent a message to user20, etc. How would I update the notification div dependent upon which user that got a new message? I assume it would no longer be a shared_div at this point.

**Comment by knoxvilledatabase** [comment]
Maybe something like this will work:

```
from django.contrib.auth.models import User
shared_notification_div = jp.Span(text='0', delete_flag=False)`

def build_user_notifications():
    for user in User.objects.filter(is_active=True):
        setattr(shared_notification_div, user.username, jp.Span(text='0'))
```

Then in DefaultLayout:

```
self.notification_div = jp.QDiv(a=self)
jp.Span(
    text=f"Messages: {getattr(shared_notification_div, user.username).text}",
    a=self.notification_div,
)
```

And:

```
jp.justpy(messages_and_feed_app, startup=build_user_notifications)
```

**Comment by elimintz** [comment]
If you want a set of users to communicate instead of all the users, you would need to create a new shared div that is put only on the page sent to these users and then update also the new shared div. 

If you filter messages using only one shared div it will not work since when that shared_div is updated, all the users will get the same result.

If you want to implement one to one messaging, you don't need a shared div. The event handler of the send message button can update the div dedicated to direct message in the appropriate page. In order to do this you need to keep a data structure that tells you which page or pages a user is on and/or which div should be updated. If I want to talk to user 23, from this data structure the event handler can find the page/div corresponding to that user and then update it. Off the top of my head I would probably use the sessions cookie to implement this: https://justpy.io/tutorial/sessions/

You could use this mechanism to also implement a group discussion without shared divs

**Comment by knoxvilledatabase** [comment]
Ok, I thought you had to have a shared_div to push data to clients.

**Comment by knoxvilledatabase** [comment]
Would there be any way to execute a function after x seconds of inactivity? 

For example, a timer that would start after the mouse has stopped moving and after x number of seconds of inactivity a function is executed.
