### ISSUE TITLE
Methods as event handlers not called?

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#61]
It seems that event handling methods on custom components are not called. It seemed only natural (given the function signature) and useful to have methods as method handlers.

This code illustrates the problem:
```
import justpy as jp

class MyInlineHello(jp.Div):

    def __init__(self, **kwargs):
        self.counter = 1
        super().__init__(**kwargs)
        self.classes = 'm-1 p-1 text-2xl text-center text-white bg-blue-500 hover:bg-blue-800 cursor-pointer'
        self.text = 'Inline Hello! (click me)'

        async def click(self, msg):
            print('In INLINE CLICK handler')
            self.text = f'Hello! I was clicked {self.counter} times'
            self.counter += 1

        self.on('click', click)


class MyMethodHello(jp.Div):

    async def click(self, msg):
        print('In METHOD CLICK handler')
        self.text = f'Hello! I was clicked {self.counter} times'
        self.counter += 1

    def __init__(self, **kwargs):
        self.counter = 1
        super().__init__(**kwargs)
        self.classes = 'm-1 p-1 text-2xl text-center text-white bg-orange-500 hover:bg-orange-800 cursor-pointer'
        self.text = 'Method Hello! (click me)'

        self.on('click', self.click)




def hello_test():
    wp = jp.WebPage()
    for i in range(5):
        wp.add(MyInlineHello()) # or jp.Hello(a=wp)
    for i in range(5):
        wp.add(MyMethodHello()) # or jp.Hello(a=wp)
    return wp

jp.justpy(hello_test)
```

**Comment by elimintz** [comment]
You just need to add the decorator `@staticmethod` before the `click` function in MyMethodHello like so:

    class MyMethodHello(jp.Div):
    
        @staticmethod
        async def click(self, msg):
            print('In METHOD CLICK handler')
            self.text = f'Hello! I was clicked {self.counter} times'
            self.counter += 1
    
        def __init__(self, **kwargs):
            self.counter = 1
            super().__init__(**kwargs)
            self.classes = 'm-1 p-1 text-2xl text-center text-white bg-orange-500 hover:bg-orange-800 cursor-pointer'
            self.text = 'Method Hello! (click me)'
    
            self.on('click', self.click)

This is because the event handlers are currently run as functions not methods. I'll look into simplifying this but the down side is that you lose versatility. You don't always want event handlers being methods.

**Comment by mjmare** [comment]
I thought the @staticmethod was just a cosmetic change (no harm in that). However I realised that it even has a disadvantage: it does not have access to self. This was the reason for investigating methods in the first place. 

Partial example:
```
class UserItem(jp.QSlideItem):

    @staticmethod
    async def button_click(comp, msg):  # using comp instead of self to prevent hiding the object's self.
        self.user_state = next_state(self.user_state)


    def __init__(self, **kwargs):
        self.user_name = None
        self.user_state = None
        super().__init__(**kwargs)
        root=self

        async def right_slide_click(comp, msg):
            delete_user(self.user_name)
            self.delete()

        async def button_click(comp, msg):  # using comp instead of self to prevent hiding the object's self.
            self.user_state = next_state(self.user_state)

        root.on('right', right_slide_click)
        root.right_slot = jp.QIcon(name='fal fa-minus-circle')

        c3 = jp.QItem(clickable=True, v_ripple=True, a=root)
        c3.on('click', self.button_click)
```

Note 2 implementations for the button_click (for this example of course). 
Using _c3.on('click', self.button_click)_ would use the static method. Using _c3.on('click', button_click)_ would use the inline function. The first argument to the event handler is the source of the event (as documented). I have named it comp to make the intention clear (to me).
The static method fails because it does not have access to self (currently it still fails silently https://github.com/elimintz/justpy/issues/52).

**Comment by elimintz** [comment]
The first argument to an event handler is the component that generated the event.
In the case above, the first argument's value would be `c3`, not self. 

An easy way to solve this is to provided a reference to `self` in c3.
Add the line `c3.self = self` to `__init__`

Then, change `button_click` to the following:

    @staticmethod
    async def button_click(comp, msg):  # using comp instead of self to prevent hiding the object's self.
        comp.self.user_state = next_state(comp.self.user_state)

Instead of `self` you can use any name you prefer for the c3 attribute.

**Comment by mjmare** [comment]
That construct defeats the purpose of simplicity and I'd be hesitant to use it for fear of not understanding my own code after a few months ;-)
If normal methods would be possible one would get the 'self' reference for free. As it stands now I'll stick to the inline version
```
async def button_click(comp, msg):  # using comp instead of self to prevent hiding the object's self.
        self.user_state = next_state(self.user_state)
```
this had the advantage of simplicity and still have acces to self (if one uses another name than self for the first arg).

**Comment by elimintz** [comment]
@mjmare Based on your suggestions this has changed in verstion 0.1.0

Now, you can define the event handlers in the intuitive way you suggested without the @staticmethod
But, the self you get will be of the component. So if for example a button which is a child of the component is pressed, the event handler's self will be the component. The button will element can be reference via msg.target which is a new field for msg in the new version.

Thanks for helping me improve this.

**Comment by mjmare** [comment]
Your prompt responses encourage suggestion (and nagging)!

I think it would be helpful to document this well. 
I have updated my example code in case you want to use it.

```
import justpy as jp

class MyInlineHelloDiv(jp.Div):

    def __init__(self, **kwargs):
        # self.counter = 1
        super().__init__(**kwargs)

        async def button_click(comp, msg):
            # Note that the first parameter refers to component that raised the event, so the Button not the Div.
            print('In INLINE BUTTON CLICK handler')
            comp.text = f'Hello! I was clicked {comp.counter} times'
            comp.counter += 1

        button_classes = 'border-solid border-1 border-black w-64 mr-2 mb-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4'
        b = jp.Button(text=f'Press me',
                      a=self,
                      classes=button_classes,
                      click=button_click,
                      )
        b.counter = 1



class MyMethodHelloDiv(jp.Div):

    async def button_click(self, msg):
        # Note that self refers to the Div component. The event source can be found with msg.target
        print('In METHOD BUTTON CLICK handler')
        msg.target.text = f'Hello! I was clicked {msg.target.counter} times'
        msg.target.counter += 1

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        button_classes = 'border-solid border-1 border-black w-64 mr-2 mb-2 bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4'
        b = jp.Button(text=f'Press me',
                      a=self,
                      classes=button_classes,
                      click=self.button_click,
                      )
        b.counter = 1




def hello_test():
    wp = jp.WebPage()
    for i in range(5):
        wp.add(MyInlineHelloDiv()) # or jp.Hello(a=wp)
    for i in range(5):
        wp.add(MyMethodHelloDiv()) # or jp.Hello(a=wp)
    return wp

jp.justpy(hello_test)
```

**Comment by elimintz** [comment]
Thank you, and keep the suggestions coming!
