### ISSUE TITLE
msg.page.redirect not reset after redirect: breaks subsequent event handling

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#62]
I have a page (at '/start') that redirects to another page (a form at '/create'). After completion of the form on the second page it redirects back to the first page. 
To redirect I use the msg.page.redirect = '/create' construct. So far so good.

I noticed that when I have returned to the first page, subsequent click handlers (unrelated to the redirection) cause to redirect *again* to the form. Clearly not the intended behaviour. 
In the debugger I noticed that msg.page.redirect of the start page still contains the value '/create', so no wonder I get redirected again.

Am I redirecting in the wrong fashion?

**Comment by elimintz** [comment]
If you are re-using the same WebPage instance then in order to stop the recurring redirection you need to set the page redirect attribute back to None. You can either do it in the event handlers or at the end of the form handler:

    msg.page.redirect = '/something'
    await msg.page.update()
    msg.page.redirect = None
    return True    # So as not to update the page again

Perhaps it is better not to reuse the page. Have a new page created in the request handler.

**Comment by mjmare** [comment]
This works. Isn't this something the framework should do? Or is your code meant as a workaround?

I thought keeping the page around (delete_flag=False) was the way to go if you want different browser windows to show the same synchronised data?

**Comment by elimintz** [comment]
Maybe it is something the framework should do automatically, I'll think it over. The code is not a workaround. It is the standard way you would change something after updating a page. You can also use the 'after' event if you like: https://justpy.io/tutorial/before_after_events/

Yes, keeping the page around for showing the same data to every body is a good idea. Sometimes only parts of the page are the same then it is better to use a shared component like in the simple message example: https://justpy.io/tutorial/pushing_data/#simple-message-board

**Comment by mjmare** [comment]
Please take into consideration that most other frameworks do redirects by returning a special response (object). This response is not stored or something. 

I cannot think of a scenario where not clearing the redirect value would be useful (although that doesn't say very much ;-)

I don't fully understand the before or after handlers. Are they run for any event of a component?

**Comment by elimintz** [comment]
The after and before event handlers run only if they are defined. They are not event specific, they are component specific.

**Comment by mjmare** [comment]
Ah OK. 
Maybe add this to the docs? Come to think of it: I think that I don't have a good mental model of how JustPy operates. I remember finding the lifecycle diagram of Vue.js (https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram) being useful in understanding what happens and what the options for hooking into the framework were. Of course, for JustPy it would be completely different.

**Comment by elimintz** [comment]
Good idea. I put it on my todo list.
