### ISSUE TITLE
Auto-reload on code change?

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#63]
An automatic reload on code change would be very convenient when developing. Something like the _--reload_ flag of Starlette.

**Comment by elimintz** [comment]
I haven't tried it, but the following should work:
Add the line `app = jp.app` like in https://justpy.io/tutorial/deployment/#more-complex-deployment
Then say your program file is called `example.py` run the following:

     $ uvicorn --reload example:app

You should get the result you wanted.

**Comment by mjmare** [comment]
That seems to work. At least for my simple one module program. Thanks.

Logging output is more verbose when running the app this way.

**Comment by knoxvilledatabase** [comment]
This is how we solved this:
```
pipenv install watchdog
pipenv install pyyaml
pipenv install argh
killall python3; watchmedo auto-restart -p "*.py" -R python3 -- my_justpy_app.py
```

**Comment by mjmare** [comment]
I'm not running the app with 
```
uvicorn --reload main.app
```
with the main.py containing:
```
app = jp.app
jp.justpy(create_main_page, start_server=False)
```
This seem to work fine. Nice reloading on source change. Also when changing dependent source files, not only in the main.py file. 

In the docs (https://justpy.io/tutorial/deployment/#more-complex-deployment) there is a note saying "The JustPy configuration file is not applicable in this case. You will need to specify the required configuration in the command line or in the Gunicorn configuration file." 

Is that correct? When stepping through justpy.py it seems that the justpy.env IS read into the config.

**Comment by elimintz** [comment]
Thank you for this example. I will add it to the docs. This is a feature that many people find useful.

The wording in the docs regarding the configuration file is poor. I will change it.
What I meant to say is that you can't specify uvicorn or gunicorn specific config parameters in the file.

**Comment by mjmare** [comment]
Ah OK. Thx

**Comment by pabloazurduy** [comment]
using @mjmare explanation worked for me, but I needed to replace `main.app` by `main:app`
> `uvicorn --reload main:app`
