### ISSUE TITLE
How to use QAjaxBar?

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#66]
@elimintz, would you mind showing me how to call the start and stop events on a QAjaxBar?

Thank you!

**Comment by elimintz** [comment]
Please see the example below.  `run_method` is not documented but is available to use. If something in the example is not clear, please let me know.

    import justpy as jp

    async def start_bar(self, msg):
        wp = msg.page
        await wp.ajax_bar.run_method('start()', msg.websocket)

    async def stop_bar(self, msg):
        wp = msg.page
        await wp.ajax_bar.run_method('stop()', msg.websocket)


    def bar_example():
        wp = jp.QuasarPage()
        d = jp.Div(classes='q-pa-md', a=wp)
        # temp=False is important because this generates an id for the element that is required for run_method to work
        wp.ajax_bar = jp.QAjaxBar(position='bottom', color='accent', size='10px', skip_hijack=True, a=d, temp=False)
        # There is a typo in the prop_list in the package code, this fixes it
        wp.ajax_bar.prop_list = ['skip-hijack', 'reverse', 'position', 'size', 'color']
        btn_start = jp.QBtn(color='primary', label='Start Bar', a=d, click=start_bar, style='margin-right: 20px')
        btn_stop = jp.QBtn(color='primary', label='Stop Bar', a=d, click=stop_bar)
        return wp

    jp.justpy(bar_example)

**Comment by knoxvilledatabase** [comment]
Thank you!
