### ISSUE TITLE
Disable highcharts

### ISSUE THREAD

**Issue by mtoftum** [elimintz/justpy#67]
Running even the basic example in the tutorial, highcharts seem to get included.
Given the license of highcharts, it'd be nice to be able to avoid it altogether when not in use.

**Comment by elimintz** [comment]
Highcharts is free for  individuals using the software for personal use, testing and demonstration https://shop.highsoft.com/faq#Non-Commercial-0

That is why for simplicity sake I decided have the default that it is loaded, to save people experimenting with the framework the step below.

There are two ways to disable loading of Highcharts:
1) Put `HIGHCHARTS = False` in justpy.env https://justpy.io/tutorial/configuration/
2) When you call justpy add the keyword argument `highcharts=False`
so in the basic example this would look like this:


      import justpy as jp
      
      def hello_world():
          wp = jp.WebPage()
          jp.Hello(a=wp)
          return wp
       
      jp.justpy(hello_world, highcharts=False)

**Comment by mtoftum** [comment]
Thanks, I couldn't find that in the highcharts documentation. Perhaps it'd be good to put this note next to the part about licensing?
