### ISSUE TITLE
Would there be any way to execute a function after x seconds of inactivity?

### ISSUE THREAD

**Issue by elimintz** [elimintz/justpy#68]
Would there be any way to execute a function after x seconds of inactivity? 

For example, a timer that would start after the mouse has stopped moving and after x number of seconds of inactivity a function is executed.

_Originally posted by @knoxvilledatabase in https://github.com/elimintz/justpy/issues/59#issuecomment-622236707_

**Comment by knoxvilledatabase** [comment]
Just to make sure I'm saying this right. Lets say I have the following code:

```
class DefaultLayout(jp.QuasarPage):
    template_file = 'quasar.html'

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        outer_div = jp.QDiv(a=self)
        table = jp.Table(a=outer_div)
        tr = jp.Tr(a=table)
        self.left_nav_td = jp.Td(a=tr, style='vertical-align:top')
        right_hand_content_td = jp.Td(a=tr, style='vertical-align:top;width:500px;height:500px')
        self.content = jp.QDiv(a=right_hand_content_td, style='margin-left:25px')

def messages_and_feed_app():
  
    def messages(self, msg):
        msg.page.content.delete_components()
        Messages(a=msg.page.content)
  
    wp = DefaultLayout()
  
    left_nav = jp.QDiv(a=wp.left_nav_td)
    jp.QBtn(
        a=left_nav,
        label='Messages',
        color='positive',
        text_color='white',
        unelevated=True,
        classes="full-width",
        style='margin-top:10px',
        click=messages,
    )
  
    class msg(object):
        page = wp

    messages(None, msg)
    return wp

jp.justpy(messages_and_feed_app)
```

With this code, is there any way I could execute the messages function after 30 seconds of inactivity.

**Comment by elimintz** [comment]
Please see the example below.
It works well but I have to make a change to the framework to be able to debounce/throtle  mouse events also. It is a waste that the mousemove event gets sent to the server every time it happens and an application will not scale well. If the number of users you have is not too large there will not be an issue. I will make the necessary change in the next version.

Please let me know if anything in the example is not clear. Basically, you need to create a div that is the whole screen and make it the encapsulating element for all others. Then you monitor mousemove on this div and reset the idle start time each time the mouse moves. The monitor_timer function needs to be specific for each page and that is why it is defined inside the request handler.

    import justpy as jp
    import time
    import asyncio
    
    
    def mouse_moved(self, msg):
        print('mouse moved')
        msg.page.start_time = time.perf_counter()
        return True
    
    async def idle_test():
        wp = jp.WebPage()
        wp.start_time = time.perf_counter()
        d = jp.Div(style='height: 100vh', a=wp)
        d.add_event('mousemove')
        d.on('mousemove', mouse_moved)
        wp.idle_div = jp.Div(text='Idle time', classes='m-4 text-lg', a=d)
    
        async def monitor_timer():
            idle_threshold = 5
            while True:
                await asyncio.sleep(5)
                idle_time = time.perf_counter() - wp.start_time
                if idle_time > idle_threshold:
                    wp.idle_div.text = f'Idle for {idle_time} seconds'
                    jp.run_task(wp.update())
    
        jp.run_task(monitor_timer())
    
        return wp
    
    jp.justpy(idle_test)

**Comment by knoxvilledatabase** [comment]
You're Brilliant! I'm thinking about creating a shared div that does the following:

1. The shared div changes.
2. Kicks off the timer looking for inactivity.
3. X number of seconds passes and a function is executed the re-queries the db and reloads the page.
4. Kills the timer until the next shared div change. 

Does this sound feasible?

**Comment by elimintz** [comment]
Yes it is feasible. The simplest way to do this I think is to keep the current example and have a 
 global variable (you can put it also in the JustPy or WebPage classes as a class attribute) that is incremented each time shared_div div is updated, call it shared_div_version . 

So monitor_timer would change to:

    async def monitor_timer():
        keep_monitoring = True
        idle_threshold = 5
        while keep_monitoring:
            try:
                await asyncio.sleep(5)
                idle_time = time.perf_counter() - wp.start_time
                if idle_time > idle_threshold and global_shared_div_version > wp.local_shared_div_version:
                    return await wp.run_javascript('location.reload()')
            except:
                keep_monitoring = False

You would also need to add the following line to the request handler (idle_test in my example):

    wp.local_shared_div_version = global_shared_div_version
    
Let me know if anything is not clear.

**Comment by knoxvilledatabase** [comment]
That is perfectly clear, I will do some testing with it this weekend and let you know how it goes.

**Comment by knoxvilledatabase** [comment]
Working like a charm. Big thanks!

**Comment by knoxvilledatabase** [comment]
I do think we need to have the debounce/throttle mouse events to make it scale like you said.

**Comment by elimintz** [comment]
Absolutely agree. Already implemented it. It will be part of the next version coming out in a week or so.

**Comment by knoxvilledatabase** [comment]
Sounds great, can't wait to see it. If you don't mind just letting me know how to call it.

**Comment by elimintz** [comment]
It is a keyword argument addition to the `on` method. 

This is the test program:

    import justpy as jp
    
    def mouse_event(self, msg):
        try:
            self.counter += 1
        except:
            self.counter = 1
        msg.page.info_div.add_first(jp.Div(text=f'{self.counter}) {msg.event_type}'))
    
    
    def debounce_test():
        wp = jp.WebPage()
        d = jp.Div(style='height: 100vh', a=wp)
        d.add_event('mousemove')
        d.on('mousemove', mouse_event, throttle=1000)
        d.on('click', mouse_event, debounce=2000, immediate=True)
        wp.info_div = jp.Div(text='Recent mouse events', classes='m-4 text-lg', a=d)
    
        return wp
    
    jp.justpy(debounce_test)
    
    
Notice that it can't be done as part of the keyword arguments when creating an element. You first need to create it and then apply `on`. The debounce and throttle values are in milliseconds. The `immediate` argument specifies leading edge debounce and the default is `False`.

In your case I would use debounce with a large value.

**Comment by knoxvilledatabase** [comment]
Ok, I look forward to being able to use it!

**Comment by knoxvilledatabase** [comment]
Is there anyway i could temporarily subclass jp.Div() and add throttle, debounce, and immediate to use until you release the next version? 

I tried the following but with no luck:

```
import justpy as jp

class TempDivWithThrottle(jp.Div):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.attributes = ['id', 'vue_type', 'show', 'events', 'classes', 'style', 'set_focus',
                  'html_tag', 'class_name', 'event_propagation', 'inner_html', 'animation', 'debug',
                  'throttle', 'debounce', 'immediate']

def mouse_event(self, msg):
    try:
        self.counter += 1
    except:
        self.counter = 1
    msg.page.info_div.add_first(jp.Div(text=f'{self.counter}) {msg.event_type}'))

def debounce_test():
    wp = jp.WebPage()
    d = TempDivWithThrottle(style='height: 100vh', a=wp)
    d.add_event('mousemove')
    d.on('mousemove', mouse_event, throttle=1000)
    d.on('click', mouse_event, debounce=2000, immediate=True)
    wp.info_div = jp.Div(text='Recent mouse events', classes='m-4 text-lg', a=d)

    return wp

jp.justpy(debounce_test)
```

![Screen Shot 2020-05-05 at 3 54 23 AM](https://user-images.githubusercontent.com/2231079/81045429-2ec96800-8e84-11ea-8311-50c8aed0e1f9.png)

**Comment by elimintz** [comment]
No, as this change required changes also in the JavaScript specifically in event_handler.js 

I'll release a version this weekend that supports this feature. If that is not soon enough let me know.

**Comment by knoxvilledatabase** [comment]
I figured it was more involved lol. Yes, this weekend would be perfect, I'm trying to go live with an application this weekend.

**Comment by elimintz** [comment]
@knoxvilledatabase  New version is out. Please test it out and let me know how it goes.

**Comment by knoxvilledatabase** [comment]
Awesome! Will do, big thanks!!!

**Comment by knoxvilledatabase** [comment]
Thank you for the new release. 

I do have a question, previously when I subclassed a JustPy QDiv component for example, like below from the messages_and_feed app, from a jp.QBtn I would use self, target, msg. However, now its telling me "add_feed() missing 1 required positional argument: 'msg'":

```
class Feed(jp.QDiv):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        panel_body = jp.QDiv(a=self, text='Feed')
        table = jp.Table(a=panel_body)
        tr = jp.Tr(a=table)
        td1 = jp.Td(a=tr)
        td2 = jp.Td(a=tr)

        self.message = jp.Textarea(placeholder='Whats on your mind?', a=td1, debounce=500)
        jp.QBtn(
            a=td2,
            label='Send',
            color='positive',
            text_color='white',
            unelevated=True,
            classes="full-width",
            size='lg',
            click=self.add_feed,
        )

    async def add_feed(self, target, msg):
        print(target)
        if self.message.value:
            d = jp.Div(text=self.message.value)
            shared_feed_div.add_component(d, 0)
            self.message.value = ''
            await shared_feed_div.update()
```

I use target throughout my entire existing code base but its like target is no longer sent to the click function.

**Comment by elimintz** [comment]
@knoxvilledatabase 
Please add @staticmethod right before the definition of add feed and let me know if this works.

      @staticmethod
      async def add_feed(self, target, msg):
        print(target)
        if self.message.value:
            d = jp.Div(text=self.message.value)
            shared_feed_div.add_component(d, 0)
            self.message.value = ''
            await shared_feed_div.update()
This is related to issue https://github.com/elimintz/justpy/issues/61

Another option is to use msg.target which is the QBtn

What happens in the new version is that if a function is already a bound method as in your case, it is not remade into a method before attaching and its self is the Feed instance instead of the button instance.
I apologize for the breaking change, it is hard to think of all the consequences.

**Comment by knoxvilledatabase** [comment]
I totally understand. I think msg.target might do the trick, I just need to go back through all of my custom components and make that change.

**Comment by knoxvilledatabase** [comment]
So far so good, I will be testing live this weekend, thank you!

**Comment by knoxvilledatabase** [comment]
This is what I ended up with:

```
    def mouse_moved(self, msg):
        print('mouse moved')
        msg.page.start_time = time.perf_counter()
        return True

    wp.start_time = time.perf_counter()
    wp.container.add_event('mousemove')
    wp.container.on('mousemove', mouse_moved, throttle=1000, debounce=5000, immediate=True)
```

Out of curiosity, what is throttle? What does throttle do?

**Comment by elimintz** [comment]
Throttling means running the event no more than once in a period. So if the number is one second, the event is not fired more than once in a second.

The debounce alone will work fine. You can't debounce and throttle an event in the same time and if both are spedicifed just debouncing occurs.

**Comment by knoxvilledatabase** [comment]
Awesome! Thank you! I think you can close this issue anytime you see fit.
