### ISSUE TITLE
Multimedia

### ISSUE THREAD

**Issue by uetacog** [elimintz/justpy#70]
Is there anyway to play audio either from a file or device? I saw quasar has an extension, but wasnt sure if it was supported.

**Comment by elimintz** [comment]
Yes, see example below taken from the Quasar docs. Please bear in mind that it will not work in a localhost environment https://stackoverflow.com/questions/51424578/embed-youtube-code-is-not-working-in-html (You will see the youtube interface but will get a download error when you try plating it)


    import justpy as jp
    
    html_string = """
    <div class="q-pa-md">
        <div class="q-video">
          <iframe
            src="https://www.youtube.com/embed/k3_tw44QsZQ?rel=0"
            frameborder="0"
            allowfullscreen
          />
        </div>
      </div>
    """
    
    
    def video_test():
        wp = jp.QuasarPage()
        v = jp.parse_html(html_string, a=wp)
        return wp
    
    jp.justpy(video_test)
