### ISSUE TITLE
Fire (custom) events?

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#74]
Would it be possible to fire (custom) events? I suppose not, and that only events from the UI are handled. 

I ran into a situation where I wanted to call some async function in the (synchronous) __init__ of a custom component. I thought a workaround would be to generate an "initialised" event that could be listened to with an async handler.  

PS I realise that questions like these are not real issues. Have you considered creating a forum perhaps?

**Comment by elimintz** [comment]
What JustPy currently has is the [run_event](https://justpy.io/tutorial/custom_components/#handling-the-change-event) method which you can use to implement custom events for components. But I am not sure this is what you are thinking about. 

If triggering an event is checking if it is defined and then calling run_event, then I can add that. Currently it is a two step process. You need to use the has_event_function method and then the run_event method like in the snippet below:
```python
            if calc.has_event_function('change'):
                calc_msg = msg
                calc_msg.event_type = 'change'
                calc_msg.id = calc.id
                calc_msg.button_text = self.text
                calc_msg.value = calc.value
                calc_msg.class_name = calc.__class__.__name__
                return await calc.run_event_function('change', calc_msg)
```
Please let me know your thoughts so I can make this more intuitive.

Soon Github will have a feature called "Discussions" and we will be able to use that, it is currently in beta. In the meantime it is fine opening an issue with any question you may have.

If you don't need to await the result of the async function in __init__ you could use jp.run_task(task) which is just:
```python
def run_task(task):
    """
    Helper function to facilitate running a task in the async loop
    """
    loop = asyncio.get_event_loop()
    loop.create_task(task)
```

Here is a more general discussion about this issue: https://stackoverflow.com/questions/33128325/how-to-set-class-attribute-with-await-in-init/33134213

I also found this package which may be of interest: https://github.com/kchmck/pyasyncinit

**Comment by mjmare** [comment]
This is interesting since it demonstrates on how to create a custom event. It would be useful to document the process in addition to the example. The docs should ideally show how to prepare the msg (because in the example the msg is 'borrowed' from the default click handler). 

Thx for the pointers with respect to the async init.

**Comment by elimintz** [comment]
msg can be any dictionary like data structure, either plain Python dictionary or Dict (dictionary where you can access keys using dot notation). I will update the docs to make this clear.

**Comment by mjmare** [comment]
Still trying, almost there (I think)

Since I was unsuccessful with the event triggering I decided to try the run_task approach. 
This almost works: the model is populated with the data (in the post_init function); I have verified this in the debugger.
However the change to the model is not visible on the page.  
When I press the button, even though the click handler does nothing, the change becomes visible. 
So it seems I'm doing something wrong with the model or component updating. 

NB Note the BasePage is derived from jp.QPage, NOT QuasarPage. IOW it is meant to be used in a QLayout.

```
class BasePage(jp.QPage):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.padding = True

class MoviesPage(BasePage):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        self.data = {'movies': []}

        async def on_click(comp, msg):
            print('IN CLICK')

        btn = jp.QButton(a=self, text='update', click=on_click)
        p = jp.P(model=[self, 'movies'], a=self)

        async def post_init():
            print('POST_INIT')
            self.data['movies'] = await get_all_movies()
            await self.update()

        jp.run_task(post_init())
```

**Comment by elimintz** [comment]
What I think is happening is that the page is being sent to the browser before the post_init() task ends as it is not being awaited (it runs in parallel instead).  You can test if this is true by putting the request handler to sleep for a second. Add `await asyncio.sleep(1)` before the `return wp`

A better option is to do the await not in the `__init__` but in the request handler. So if your page is `wp` you would add the line `await wp.post_init()` before `return wp`

You don't need the `await self.update()` line. It won't work  because the websocket connection has not been established yet at this stage.

Don't forget to make the request handler an `async` function.

Let me know if this is clear.

**Comment by mjmare** [comment]
> Add await asyncio.sleep(1) before the return wp

Yes, that circumvented the problem. 

Using the request handler is not an option in my case. Since I am using the QLayout page to swap QPages in and out. So the request handler is only called once per browser window (right?).
I want to have custom QPage derived components that are swapped on demand. Hence my need to do something, like load data from a database, in the __init__. With synchronous code that is no problem, just call it. 
However async code cannot be called in the __init__. Some on_load event or post_init overridable method would be very useful. 

I also tried the class method approach as suggested in one of the links you provided:

```
    @classmethod
    async def create(cls, **kwargs):
        obj = cls(**kwargs)
        await obj.load_data()
        await obj.update()


    async def load_data(self):
        self.data['movies'] = await get_all_movies()
        print(self.data

```
and then instantiating the page with:
```
fp = jp.run_task(MoviesPage.create(a=self.container))
```
but I ran into the same refresh problem: the page needs at least one interaction (like clicking any button) to properly update.

**Comment by elimintz** [comment]
Unrelated, am I correct to assume that a QPage is created in some event handler?

Try changing:
`fp = jp.run_task(MoviesPage.create(a=self.container))`
to 
`fp = await MoviesPage.create(a=self.container)`

and add `return obj` to the end of `create`

**Comment by mjmare** [comment]
No, the QuasarPage instantiates a QLayout which contains a QLayoutContainer. This happens in the QuasarPage's __init__. The content is displayed with QPage derived classes. These QPages are swapped in and out of the QLayoutContainer on demand (eg when the user clicks on a menu). For the initial view however I want the QuasarPage's __init__ to instantiate the first QPage.
So all in all I have just 1 route/webpage.
All this works fine if you call synchronous code in the __init__. My first QPage derived component wants to load data from a database to display on the page. As soon as I want to call async database access code I get the described problems (which as you pointed out is probably related to the separate threads).

I think this is a good use case in favour of JustPy component life cycle hooks/events. I've always found  Vue.js lifecycle events very useful to plug in custom behaviour (the red boxes on https://vuejs.org/v2/guide/instance.html#Lifecycle-Diagram). 

PS if you prefer another way of discussing all this I'm all for it.

**Comment by elimintz** [comment]
Would be happy to discuss more directly. This is an interesting use case.
Please contact me at eli.mintz@gmail.com
