### ISSUE TITLE
Add option on input field to only send message to the server on blur instead of on change

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#76]
When my users enter information into input fields, if they type at different speeds some characters get dropped. Would it be possible to only send the message on blur?

**Comment by elimintz** [comment]
Yes that is possible, but could you please try first making debounce larger, perhaps try `debounce=1000`
For example:
`jp.QInput(label='Standard', a=c2, debounce=1000)`

The dropping of characters happens only when the connection latency is larger than the debounce. To get a sense of the latency have your users ping your server. 

Let me know if this helps. I would be curious to know also what the latency is that causes the issue.

**Comment by knoxvilledatabase** [comment]
Yes, I have tested everything from 100 ms up to 1000 ms and 1000 ms solves the problem of it dropping characters when typing at variable speeds but then the customer complains that the field goes completely blank after tabbing to the next field (of course you and I know that this is because of the debounce of 1 second).

**Comment by elimintz** [comment]
Thanks. I'll look into this today to find the best solution.

**Comment by elimintz** [comment]
@knoxvilledatabase 
This turned out to be a little trickier than I thought for QInput.
So I just released a new version (0.1.1) that enables this. After you upgrade, please try:

```python
import justpy as jp

def my_blur(self, msg):
    # IMPORTANT!!! Otherwise the value on the backend will not reflect value on frontend
    self.value = msg.value
    # If you don't need the page to update:
    return True


def blur_test():
    wp = jp.QuasarPage()
    d = jp.Div(classes='q-pa-md', a=wp, style='width: 300px')
    in1 = jp.QInput(label='Standard', a=d, blur=my_blur, disable_input_event=True)
    return wp

jp.justpy(blur_test)
```

QInput now has a new attribute `disable_input_event` that you need to set to True.

**Very important**: Because the input event is disabled, the value in the backend is not automatically in sync with the frontend value. You need to take care of this yourself in the blur event handler like in the example above.

Please let me know how this works for you.

**Comment by knoxvilledatabase** [comment]
Awesome, thank you, I will give it a try shortly!

**Comment by elimintz** [comment]
@knoxvilledatabase 
To simplify things, I have added the following component to the package:

```python
class QInputBlur(QInput):

    def before_event_handler(self, msg):
        logging.debug('%s %s %s %s %s', 'before ', self.type, msg.event_type, msg.input_type, msg)
        if hasattr(self, 'model'):
            self.model[0].data[self.model[1]] = msg.value
        self.value = msg.value


    def convert_object_to_dict(self):
        d = super().convert_object_to_dict()
        d['disable_input_event'] = True
        if 'blur' not in self.events:
            self.events.append('blur')
        return d
```

It will be in the next version but you can start using it by inserting the code above in your program. This component disables the input event and activates the blur event so whenever a blur event occurs at least the before_event_handler is run which updates the value on the server side before the user defined event handler is run if it defined (so there is no need to update the value yourself).

You can test it with the following program :

```python
import justpy as jp


class QInputBlur(QInput):

    def before_event_handler(self, msg):
        logging.debug('%s %s %s %s %s', 'before ', self.type, msg.event_type, msg.input_type, msg)
        if hasattr(self, 'model'):
            self.model[0].data[self.model[1]] = msg.value
        self.value = msg.value

    def convert_object_to_dict(self):
        d = super().convert_object_to_dict()
        d['disable_input_event'] = True
        if 'blur' not in self.events:
            self.events.append('blur')
        return d

def my_blur(self, msg):
    self.div.text = self.value

def input_demo(request):
    wp = jp.QuasarPage()
    c1 = jp.Div(classes='q-pa-md', a=wp)
    c2 = jp.Div(classes='q-gutter-md', style='max-width: 300px', a=c1)
    in1 = QInputBlur(a=c2,placeholder='Please type here', label='QInputBlur')
    in1.div = jp.Div(text='What you type will show up here only when Input element loses focus',
                      classes='text-h6', a=c2)
    in1.on('blur', my_blur)
    return wp

jp.justpy(input_demo)
```

**Comment by knoxvilledatabase** [comment]
Works perfectly, thank you!

**Comment by elimintz** [comment]
Happy to hear. Your input helped me think this issue through.
In the next version there will also be a pre-defined QInput derived component called QInputChange that will not fire the input event but only the change event which occurs when the component loses focus or the user presses the Enter key. Basically, a change occurs when the user commits the value of the field.
