### ISSUE TITLE
How to handle multiple row (de)selection in ag.Grid?

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#77]
In the grid options I have enabled multiple selection:
```
'rowSelection': 'multiple',
```
For one one the columns I have enabled checkbox selection:
```
 'columnDefs': [
                {'headerName': "Title", 'field': 'title', 'checkboxSelection': True},
:
```
I have setup an event handler for the selectionChanged event. And indeed it gets called when one or more rows are selected. 
However, I'm at a loss on how to get the selected rows. According to the ag.Grid docs I have to call api.getSelectedNodes() or api.getSelectedRows() to get them. 

I have tried to do something like this (and some variations):
```
result = await comp.run_method('this.api.getSelectedNodes()', msg.websocket)
```
but that only returns True. 

Any suggestions?

**Comment by elimintz** [comment]
I have not implemented yet the `run_method` for ag-grid, but in this case you don't need it. Please see example below.

```python
import justpy as jp

grid_options = """
{
    rowSelection: 'multiple',
    defaultColDef: {
        filter: true,
        sortable: true,
        resizable: true,
        cellStyle: {textAlign: 'center'},
        headerClass: 'font-bold'
    }, 
      columnDefs: [
      {headerName: "Make", field: "make"},
      {headerName: "Model", field: "model"},
      {headerName: "Price", field: "price"}
    ],
      rowData: [
      {make: "Toyota", model: "Celica", price: 35000},
      {make: "Ford", model: "Mondeo", price: 32000},
      {make: "Porsche", model: "Boxter", price: 72000}
    ]
}
"""

def row_selected(self, msg):
    print(msg.selected, msg)
    wp = msg.page
    if msg.selected:
        wp.selected_rows[msg.rowIndex] = msg.data
    else:
        wp.selected_rows.pop(msg.rowIndex)
    s = f'Selected rows {sorted(list(wp.selected_rows.keys()))}'
    for i in sorted(wp.selected_rows):
        s = f'{s}\n Row {i}  Data: {wp.selected_rows[i]}'
    if wp.selected_rows:
        wp.rows_div.text = s
    else:
        wp.rows_div.text = 'No row selected'


def grid_test():
    wp = jp.WebPage()
    wp.selected_rows = {}  # Dictionary holding selected rows
    grid = jp.AgGrid(a=wp, options=grid_options, style='height: 200px; width: 300px; margin: 0.25em')
    grid.options.columnDefs[0].checkboxSelection = True
    grid.on('rowSelected', row_selected)
    wp.rows_div = jp.Pre(text='Data will go here when you select rows', classes='border text-lg', a=wp)
    return wp

jp.justpy(grid_test)
```

The basic idea is to keep a dictionary of the selected rows. Note that `msg.selected` is True if the row is selected and False if it is deselected.

Let me know if something is not clear.

**Comment by mjmare** [comment]
Keeping track of the selected items oneself is a fine solution. Thx.

Is the call_method something that has to be supported on the Vue side?

**Comment by elimintz** [comment]
Yes. Also, the added twist is that you need to communicate back again with the server. It is doable, but I haven't gotten around to it yet.

**Comment by mjmare** [comment]
So even where the call_method is implemented it does not return anything?

**Comment by elimintz** [comment]
When I implement it, it will return a value via some event handler. I have not thought out all the details yet.

**Comment by mjmare** [comment]
OK, thx
