### ISSUE TITLE
QToolbar instead QToolBar

### ISSUE THREAD

**Issue by maciejmatczak** [elimintz/justpy#8]
Hello, project is really fun to play around, congrats!

Found a discrepancy in one of the Quasar classes:
https://github.com/elimintz/justpy/blob/186aeaacc92fe42f29bc56798e208d5b100fa5a9/justpy/quasarcomponents.py#L413
applies as well for `QToolBarTitle` (should be rather `QToolbarTitle`).

Cheers!

**Comment by elimintz** [comment]
Thank you , I am glad you like playing around with it!

And thank you again for catching this, I will fix in upcoming version
