### ISSUE TITLE
Add a header?

### ISSUE THREAD

**Issue by johnmudd** [elimintz/justpy#97]
I naively tried to add a header to a webpage by using `H1`, `H2` etc. and all of the text is the same size. Are these outdated concepts?

Should I use Tailwind instead like this? My only problem with this is I'm unsure how to pick a font size in absolute pixels that will be an appropriate header.

`P(text='Hello World!', style=f'font-size: 30px')
`

**Comment by elimintz** [comment]
Tailwind overrides the default h tags styles. 

I would recommend using one of the tailwind classes for font size:
https://tailwindcss.com/docs/font-size/

The appropriate font size is a design issue. Try experimenting with the different tailwind classes and go with the option that you like best.
