### ISSUE TITLE
How to decipher Tailwind?

### ISSUE THREAD

**Issue by johnmudd** [elimintz/justpy#98]
Your examples display great and I want to follow your lead. But when I see `classes` strings such as this I get distracted by the cryptic value.

`my_paragraph_design = "w-64 bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"`

So I wrote this code to decipher it. 

```
my_paragraph_design = "w-64 bg-blue-500 m-2 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded"
for i in my_paragraph_design.split():
    try:
        print (jp.Tailwind.tw_reverse_dict[i], i)
    except KeyError:
        print('????', i)
```

Output:
```
width w-64
background_color bg-blue-500
margin m-2
???? hover:bg-blue-700
text_color text-white
font_weight font-bold
padding-y py-2
padding-x px-4
border-radius rounded
```

That helps me make sense of it. But `hover:bg-blue-700` is an exception. Where can I find a list that covers items such as `hover`? I want to see what other features can be specified.

**Comment by elimintz** [comment]
You can find it here: https://tailwindcss.com/docs/pseudo-class-variants

JustPy supports all the pseudo class variants that come as a default with the tailwind CDN version.
