### ISSUE TITLE
Add SVG image?

### ISSUE THREAD

**Issue by johnmudd** [elimintz/justpy#99]
I want to use [this lock image](https://github.com/tabler/tabler-icons/blob/master/icons/lock.svg). I downloaded it into `images/lock.svg`. 

My goal is to display it large, in red with a heavy stroke. So far I was only to display it in default size using `jp.Div`. I failed with `Svg` & `Img`. `Div` displays an image and I was able to set the size of the `Div` and change the background color but not the color used in the drawing. How would you start this?

```
    d = jp.Div(classes='w-7/8 m-2 p-3 border rounded-lg ', a=wp)
    jp.Svg(image='images/lock.svg', a=d)
    jp.Svg(svg='images/lock.svg', a=d)
    jp.Svg(script='images/lock.svg', a=d)
    jp.Img(src='images/lock.svg', a=d)
    lock = jp.Div(a=d, inner_html=open('images/lock.svg').read())
    lock.height = 100  # Copied from [Specific Attributes](https://justpy.io/tutorial/html_components/#specific-attributes) 
    lock.width = 100
    lock = jp.Div(a=d, inner_html=open('images/lock.svg').read(), classes='w-64 h-64 fg-red-700 bg-blue-500 hover:bg-blue-700')
```

**Comment by elimintz** [comment]
The simplest way to do this is the following:

```python
import justpy as jp

svg_html = """
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-lock" 
     color="red" width="240" height="240" 
     viewBox="0 0 24 24" stroke-width="2" 
     stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z"/>
  <rect x="5" y="11" width="14" height="10" rx="2" />
  <circle cx="12" cy="16" r="1" />
  <path d="M8 11v-4a4 4 0 0 1 8 0v4" />
</svg>

"""

def svg_example():
    wp = jp.WebPage()
    d = jp.Div(a=wp)
    d.inner_html = svg_html
    return wp

jp.justpy(svg_example)
```

Another more general way that allows you more flexibility is to use the [parse_html](https://justpy.io/tutorial/working_with_html/#the-parse_html-function) function:

```python
import justpy as jp

svg_html = """
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-lock" 
     viewBox="0 0 24 24" stroke-width="2" 
     stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z"/>
  <rect x="5" y="11" width="14" height="10" rx="2" />
  <circle cx="12" cy="16" r="1" />
  <path d="M8 11v-4a4 4 0 0 1 8 0v4" />
</svg>

"""

def svg_example():
    wp = jp.WebPage()
    for i in range(5, 500, 50):
        svg_element = jp.parse_html(svg_html, a=wp)
        svg_element.width = i
        svg_element.height = i
        svg_element.color = 'red'
    return wp

jp.justpy(svg_example)
```

**Comment by johnmudd** [comment]
Thanks.

Now I'm trying to size the SVG image to combine with some header text. Below I force it to match the header size by manually translating the Tailwinds text size `'text-3xl'` used for the header to `'1.875rem'` used for the lock image. I got the translation from the [Tailwinds Font Size doc](https://tailwindcss.com/docs/font-size/). 

Is there a better way to match the size of the header so that if I change the header size then the lock image will automatically adjust? Can I interrogate the header to find out it's height in pixels?

    d = jp.Div(classes='w-7/8 m-2 p-3 border rounded-lg ', a=wp)
    header = jp.P(text='Six month history', a=d, classes='text-3xl')
    svg_html = open('images/lock.svg').read()
    svg_element = jp.parse_html(svg_html, classes='hover:bg-blue-200', a=d)
    #svg_element.width = svg_element.height = 'text-3xl'  # Fail, gigantic.
    svg_element.width = svg_element.height = '1.875rem' 
    header = jp.P(text='Six month history for '+phone_number, a=d, classes=f'text-3xl')

**Comment by elimintz** [comment]
If this is something you would reuse then you can make the header and the svg element a custom component. If this is of interest to you I can show you how to do this.

Another simple solution is to add your own attribute to the header, call it font_size for example:
```python
    d = jp.Div(classes='w-7/8 m-2 p-3 border rounded-lg ', a=wp)
    header = jp.P(text='Six month history', a=d)
    header.font_size = '1.875rem' 
    header.style = f'font-size: {header.font_size}'
    svg_html = open('images/lock.svg').read()
    svg_element = jp.parse_html(svg_html, classes='hover:bg-blue-200', a=d)
    #svg_element.width = svg_element.height = 'text-3xl'  # Fail, gigantic.
    svg_element.width = svg_element.height = header.font_size
```

You can parse a file to html directly using parse_html_file('images/lock.svg')

**Comment by johnmudd** [comment]
Thanks, that works. And thanks for the `parse_html_file()` tip.

Now I'm trying to add support for SVG images in a table. I was using `jp.AutoTable`. It treats all elements as text so I tried to modify it.  Here's an example that didn't work. I don't know what arguments are allowed for table cell so I'm guessing. How can I find what arguments are support for `Td`?

```
                for item in row:
                    #Td(text=item, classes=self.td_classes, a=tr)  # Original code.
                    #Td(src='images/lock.svg', classes=self.td_classes, a=tr)  # Fails
                    Td(http_src='images/lock.svg', classes=self.td_classes, a=tr)  # Fails
```

**Comment by elimintz** [comment]
Td is equivalent to the HTML td tag https://www.w3schools.com/tags/tag_td.asp which is just a cell in the table. You can add elements to it like you add to a Div. 

The example below creates a simple table with the svg element in the cells. Just so that it is not too boring, I made the svg size dependent on the column:
```python
import justpy as jp

svg_html = """
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-lock" 
     viewBox="0 0 24 24" stroke-width="2" 
     stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z"/>
  <rect x="5" y="11" width="14" height="10" rx="2" />
  <circle cx="12" cy="16" r="1" />
  <path d="M8 11v-4a4 4 0 0 1 8 0v4" />
</svg>

"""

def svg_table_example():
    wp = jp.WebPage()
    table = jp.Table(a=wp)
    thead = jp.Thead(a=table)
    tr = jp.Tr(a=thead)
    for item in ['Header 1', 'Header 2', 'Header 3']:
        jp.Th(text=item, classes='', a=tr)
    tbody = jp.Tbody(a=table)
    for row in range(5):
        tr = jp.Tr(a=tbody)
        for col in range(1, 4):
            td = jp.Td(a=tr)
            svg_element = jp.parse_html(svg_html, a=td)
            svg_element.width = col * 10
            svg_element.height = col * 10
            svg_element.color = 'red'
    return wp

jp.justpy(svg_table_example)
```

**Comment by johnmudd** [comment]
So simple. Thanks.
